import React,{useEffect,useMemo,useState} from 'react';
import axios from 'axios';
import SearchableSelect from '../components/SearchableSelect';
import './Ahbrd1301UretimAgaci.css';
const API='http://localhost:5000/api';
const STAGES=[
 {key:'TABLA',title:'TABLA GRUBU',output:'Tabla Grubu',note:'1250×2500×1 H1050 levha → 1250×500 tabla blankı. 1 levha = 5 blank.'},
 {key:'AYAK',title:'AYAK GRUBU',output:'Ayak Grubu',note:'20×40 profil 110 cm + 254 cm yuvarlak profil 42 cm + delik/kaynak/şapka/galvaniz/perçin/göbek.'},
 {key:'KADEME',title:'KADEME MEKANİZMASI',output:'Kademe Mekanizması',note:'Kurt ağzı kademe demiri + 8 mm dolu demir + büküm/kaynak/galvaniz + yay + segman.'},
 {key:'KILIF',title:'KILIF GRUBU',output:'Kılıf Grubu',note:'Kumaş + biye + ip + stoper + uç + keçe → fason dikim.'},
 {key:'AKSESUAR',title:'ÜST AKSESUAR GRUBU',output:'Üst Aksesuar Grubu',note:'Plastik tabla + baskı + 9 cm silikon + 6/8 mm demir + plastik başlık.'},
 {key:'MONTAJ',title:'SON MONTAJ',output:'Son Montaj',note:'Tabla + ayak + kademe + kılıf + üst aksesuar.'},
 {key:'PAKET',title:'PAKETLEME',output:'Paketleme',note:'Son montaj + ön etiket + shelling + koli.'},
 {key:'MAMUL',title:'AHBRD 1301 MAMUL',output:'AHBRD 1301',note:'Paketleme çıktısı mamul stokuna girer.'}
];
const RAW=[
 ['Alüminyum levha H1050 1250x2500x1 mm','TABLA','0.20','Levha','1 levha = 5 blank'],['Kanal sacı','TABLA','','Adet','Delik + kaynak'],['Kesim hizmeti','TABLA','','Hizmet','Fason kesim'],['Baskı hizmeti','TABLA','','Hizmet','Fason baskı'],['Nakliye','TABLA','','Hizmet','Kesim/baskı taşıması'],['20x40x1 mm kutu profil 221 cm','AYAK','','Adet','110 cm kesim'],['254 cm yuvarlak profil 1 mm','AYAK','','Adet','42 cm kesim'],['Şapka','AYAK','','Adet','Fason'],['8 mm dolu demir','AYAK','','Adet','Kaynak + galvaniz'],['Perçin','AYAK','','Adet','4 perçin / ayak'],['Göbek civata','AYAK','','Adet','Plastik parça ile'],['Plastik ayak parçası','AYAK','','Adet','Fason baskı'],['Kurt ağzı kademe demiri','KADEME','','Adet','Fason baskı'],['8 mm dolu demir','KADEME','','Adet','Özel büküm'],['Yay','KADEME','','Adet','Satın alma'],['8 mm segman','KADEME','','Adet','Satın alma'],['Kumaş','KILIF','','Metre','Fason dikim'],['Biye','KILIF','','Metre','Fason dikim'],['İp','KILIF','','Metre','Fason dikim'],['Stoper','KILIF','','Adet','Fason dikim'],['Uç','KILIF','','Adet','Fason dikim'],['Keçe','KILIF','','Adet','Fason dikim'],['Plastik tabla','AKSESUAR','','Adet','Fason baskı'],['Silikon','AKSESUAR','','Adet','9 cm kesim'],['6/8 mm demir','AKSESUAR','','Adet','Tabla üzerine'],['Plastik başlık','AKSESUAR','','Adet','Fason/tedarik'],['Ön etiket','PAKET','','Adet','Paketleme'],['Koli','PAKET','','Adet','Paketleme']
];
const blank=()=>RAW.map((r,i)=>({id:i,name:r[0],stage:r[1],qty:r[2],unit:r[3],note:r[4],urunId:'',cost:0,fason:false}));
const norm=v=>String(v||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[×x*.,;:/\\()\[\]_-]+/g,' ').replace(/\s+/g,' ').trim();
const alias={
 'Alüminyum levha H1050 1250x2500x1 mm':['aluminyum','h1050','1250 2500','levha','sac'],
 '20x40x1 mm kutu profil 221 cm':['20 40','kutu profil','221'],
 '254 cm yuvarlak profil 1 mm':['254','yuvarlak profil'],
 'Kurt ağzı kademe demiri':['kurt agzi','kademe'],
 'Plastik ayak parçası':['plastik','ayak'],
 'Plastik tabla':['plastik','tabla'],
 'Plastik başlık':['plastik','baslik'],
 'Kanal sacı':['kanal','sac'],
 'Göbek civata':['gobek','civata'],
 'Ön etiket':['etiket'],Koli:['koli']
};
function match(list,name){const n=norm(name),a=(alias[name]||[]).map(norm);let best=null,score=0;for(const p of list){const t=norm(`${p.UrunKodu||''} ${p.UrunAdi||''}`);if(!t)continue;let s=t===n?100:0;if(t.includes(n))s+=70;const words=n.split(' ').filter(Boolean);s+=words.filter(w=>t.split(' ').includes(w)).length*12;for(const x of a)if(t.includes(x))s+=18;if(s>score){score=s;best=p;}}return score>=30?best:null;}
export default function Ahbrd1301UretimAgaciV2(){
 const [urunler,setUrunler]=useState([]),[receteler,setReceteler]=useState([]),[inputs,setInputs]=useState(blank),[outputs,setOutputs]=useState({}),[active,setActive]=useState('TABLA'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{const [u,r]=await Promise.all([axios.get(`${API}/urunler`),axios.get(`${API}/recete-yonetim`)]);const products=u.data||[];setUrunler(products);setReceteler(r.data||[]);const out={},ins=inputs.map(x=>{const h=match(products,x.name);return h?{...x,urunId:h.UrunId}:x});for(const s of STAGES){const h=match(products,s.key==='MAMUL'?'AHBRD 1301':s.output);if(h)out[s.key]=h.UrunId;}setOutputs(out);setInputs(ins);};
 useEffect(()=>{load().catch(e=>setMessage(e.response?.data?.error||'Ürün/reçete listesi alınamadı.'));},[]);
 const productOptions=useMemo(()=>urunler.filter(u=>u.Tur!=='Hizmet').map(u=>({value:u.UrunId,label:u.UrunAdi,sublabel:u.UrunKodu})),[urunler]);
 const allOptions=useMemo(()=>urunler.map(u=>({value:u.UrunId,label:u.UrunAdi,sublabel:u.UrunKodu})),[urunler]);
 const recipeByCode=useMemo(()=>Object.fromEntries(receteler.map(r=>[r.ReceteKodu,r])),[receteler]);
 const stage=STAGES.find(s=>s.key===active), rows=inputs.filter(x=>x.stage===active);
 const setInput=(id,key,value)=>setInputs(v=>v.map(x=>x.id===id?{...x,[key]:value}:x));
 const auto=()=>{const out={},ins=inputs.map(x=>x.urunId?x:{...x,urunId:match(urunler,x.name)?.UrunId||''});for(const s of STAGES){const h=match(urunler,s.key==='MAMUL'?'AHBRD 1301':s.output);if(h)out[s.key]=h.UrunId;}setOutputs(v=>({...v,...out}));setInputs(ins);setMessage('Gerçek ürün kartları eşleştirildi; bulunamayanlar boş bırakıldı.');};
 const build=(key)=>inputs.filter(x=>x.stage===key&&(Number(x.qty)>0||Number(x.cost)>0)).map(x=>({kalemTipi:x.unit==='Hizmet'?'Hizmet':'Malzeme',hammaddeUrunId:x.urunId||null,hammaddeAdi:x.name,miktar:Number(x.qty||0),birim:x.unit,girdiMiktari:Number(x.qty||0),girdiBirimi:x.unit,ciktiMiktari:null,ciktiBirimi:x.unit,verimOrani:100,fireOrani:0,donusumAciklama:x.note,fasonMu:x.fason,hizmetBirimFiyati:Number(x.cost||0),nakliyeMaliyeti:0,iscilikDakika:0,makineDakika:0,iscilikBirimMaliyeti:0,makineBirimMaliyeti:0,depo:'Merkez Depo',aciklama:x.note}));
 const save=async(s,children)=>{const id=outputs[s.key];if(!id)throw new Error(`${s.title}: çıktı ürün kartını seçmelisin.`);let items=build(s.key);for(const c of children)items.push({kalemTipi:'Yarı Mamul',hammaddeUrunId:null,hammaddeAdi:c.name,miktar:c.qty,birim:'Adet',girdiMiktari:c.qty,girdiBirimi:'Adet',ciktiMiktari:1,ciktiBirimi:'Adet',verimOrani:100,fireOrani:0,altReceteId:c.id,donusumAciklama:'AHBRD 1301 alt reçete bağlantısı',depo:'Merkez Depo',istasyonAdi:'Son Montaj',aciklama:'Alt reçete'});const existing=recipeByCode[`AHBRD1301-${s.key}`];const name=urunler.find(u=>String(u.UrunId)===String(id))?.UrunAdi||s.output;const payload={form:{receteKodu:`AHBRD1301-${s.key}`,receteAdi:s.output,mamulUrunId:id,mamulAdi:name,aciklama:`AHBRD 1301 · ${s.note}`,versiyon:existing?.Versiyon||1,uretimBirimi:'Adet',durum:'Aktif',receteTipi:s.type,ciktiMiktari:1,ciktiBirimi:'Adet',standartFireOrani:0},items,operations:[]};const r=await axios.post(`${API}/recete-agaci`,payload);return{ReceteId:r.data.receteId,MamulAdi:name};};
 const apply=async()=>{setBusy(true);setMessage('');try{const created={};for(const s of STAGES){let c=[];if(s.key==='MONTAJ')for(const k of ['TABLA','AYAK','KADEME','KILIF','AKSESUAR']){const r=created[k]||recipeByCode[`AHBRD1301-${k}`];if(r?.ReceteId)c.push({id:r.ReceteId,name:r.MamulAdi||k,qty:1});}if(s.key==='PAKET'){const r=created.MONTAJ||recipeByCode['AHBRD1301-MONTAJ'];if(r?.ReceteId)c.push({id:r.ReceteId,name:r.MamulAdi||'Son Montaj',qty:1});}if(s.key==='MAMUL'){const r=created.PAKET||recipeByCode['AHBRD1301-PAKET'];if(r?.ReceteId)c.push({id:r.ReceteId,name:r.MamulAdi||'Paketleme',qty:1});}created[s.key]=await save(s,c);}await load();setMessage('AHBRD 1301 üretim ağacı başarıyla oluşturuldu/güncellendi. 8 reçete kartı hazır.');}catch(e){setMessage(e.response?.data?.detail||e.response?.data?.error||e.message||'Kurulum hatası.');}finally{setBusy(false);}};
 return <div className="ahbrd-wizard"><header><div><span>ÜRETİM ŞABLONU</span><h1>AHBRD 1301 · Üretim Ağacı</h1><p>Tabla → Ayak → Kademe → Kılıf → Aksesuar → Son Montaj → Paketleme → Mamul</p></div><div className="ahbrd-actions"><button className="secondary" onClick={auto} disabled={busy}>↻ Otomatik Eşleştir</button><button onClick={apply} disabled={busy}>{busy?'Kuruluyor…':'⚙ Ağacı Kur / Güncelle'}</button></div></header><div className="ahbrd-alert"><b>Gerçek ürün kartları kullanılır.</b> ID uydurulmaz. Emin olunmayan kartlar boş bırakılır.</div><div className="ahbrd-stagebar">{STAGES.map(s=><button key={s.key} className={active===s.key?'active':''} onClick={()=>setActive(s.key)}><b>{s.key}</b><span>{s.title}</span></button>)}</div><main><section className="ahbrd-card"><div className="ahbrd-card-head"><div><span>ÇIKTI</span><h2>{stage.title}</h2></div><label>Çıktı ürünü<SearchableSelect options={productOptions} value={outputs[active]||''} onChange={id=>setOutputs(v=>({...v,[active]:id}))} placeholder="Mevcut ürün kartını seç…"/></label></div><p className="ahbrd-note">{stage.note}</p><div className="ahbrd-table"><div className="ahbrd-tr ahbrd-th"><span>Girdi</span><span>Miktar</span><span>Birim</span><span>Ürün kartı</span><span>Fason</span><span>Maliyet</span></div>{rows.map(x=><div className="ahbrd-tr" key={x.id}><span><b>{x.name}</b><small>{x.note}</small></span><input type="number" step="0.0001" value={x.qty} onChange={e=>setInput(x.id,'qty',e.target.value)} placeholder="Miktar"/><input value={x.unit} onChange={e=>setInput(x.id,'unit',e.target.value)}/><SearchableSelect options={allOptions} value={x.urunId} onChange={id=>setInput(x.id,'urunId',id)} placeholder="Ürün / hizmet eşleştir…"/><label className="check"><input type="checkbox" checked={x.fason} onChange={e=>setInput(x.id,'fason',e.target.checked)}/> Fason</label><input type="number" step="0.01" value={x.cost} onChange={e=>setInput(x.id,'cost',e.target.value)} placeholder="0.00"/></div>)}</div></section><aside className="ahbrd-side"><div><span>BAĞLANTI</span><h3>Üretim ağacı</h3></div>{STAGES.map((s,i)=><div className={`ahbrd-link ${active===s.key?'active':''}`} key={s.key}><b>{i+1}</b><span>{s.title}</span><small>{outputs[s.key]?'✓ Ürün eşlendi':'⚠ Ürün seç'}</small></div>)}<div className="ahbrd-cost"><span>YAPI</span><strong>8 reçete</strong><small>Montaj 5 alt grubu tüketir; paketleme montajı, mamul paketlemeyi tüketir.</small></div></aside></main>{message&&<div className="ahbrd-message">{message}</div>}<div className="ahbrd-footer"><span>{receteler.filter(r=>String(r.ReceteKodu||'').startsWith('AHBRD1301-')).length} / 8 AHBRD reçete kartı mevcut</span><span>Sevkiyat maliyeti üretim reçetesinden ayrı tutulur.</span></div></div>;
}