import React,{useEffect,useMemo,useState}from'react';
import axios from'axios';
import ExportToolbar from'../components/ExportToolbar';
import'./InvoiceListPage.css';

const API=process.env.REACT_APP_API_URL||'http://localhost:5000/api';
const WORKSPACE=`${API}/invoice-workspace`;
const ACTIONS=`${API}/kolaybi/faturalar`;
const STATUS_VALUES=['Onaylandı','İptal Edilen E-Fatura','İptal Edildi','Teslim Edildi','Yeni','Bekliyor','Hazırlandı','Hazırlanıyor','Reddedildi','Sevk Edildi','Dönüşüm İptal Edildi','Onay Bekliyor'];
const currency=v=>String(v||'TRY').toUpperCase()==='TL'?'TRY':String(v||'TRY').toUpperCase();
const money=(v,c='TRY')=>{try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency:currency(c),maximumFractionDigits:2}).format(Number(v||0))}catch(_){return`${Number(v||0).toLocaleString('tr-TR')} ${c||'TRY'}`}};
const date=v=>v?new Date(v).toLocaleDateString('tr-TR'):'—';
const errText=e=>e?.response?.data?.error||e?.response?.data?.detail||e?.message||'İşlem başarısız.';

export default function InvoiceListPage(){
 const[faturalar,setFaturalar]=useState([]),[filters,setFilters]=useState({search:'',yon:'Hepsi',durum:'Hepsi',start:'',end:'',min:'',max:''}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState(''),[openMenu,setOpenMenu]=useState(null),[busy,setBusy]=useState(false),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25);
 const load=async()=>{setLoading(true);setError('');try{const r=await axios.get(WORKSPACE);setFaturalar(Array.isArray(r.data)?r.data:[])}catch(e){setError(errText(e))}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const q=filters.search.trim().toLocaleLowerCase('tr-TR');return faturalar.filter(f=>{const hay=`${f.FaturaKodu||''} ${f.CariKodu||''} ${f.CariAdi||''}`.toLocaleLowerCase('tr-TR'),d=f.FaturaTarihi?String(f.FaturaTarihi).slice(0,10):'',t=Number(f.GenelToplam||0);return(!q||hay.includes(q))&&(filters.yon==='Hepsi'||f.Yon===filters.yon)&&(filters.durum==='Hepsi'||(f.Durum||'Bekliyor')===filters.durum)&&(!filters.start||d>=filters.start)&&(!filters.end||d<=filters.end)&&(filters.min===''||t>=Number(filters.min))&&(filters.max===''||t<=Number(filters.max))})},[faturalar,filters]);
 useEffect(()=>setPage(1),[filters,pageSize]);
 const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=filtered.slice((page-1)*pageSize,page*pageSize),totalAmount=filtered.reduce((s,f)=>s+Number(f.GenelToplam||0),0);
 const openDetail=async invoice=>{setOpenMenu(null);setSelected(null);setDetailError('');setDetailLoading(true);try{const r=await axios.get(`${WORKSPACE}/${invoice.FaturaId}/detay`);setSelected(r.data);syncRemoteStatus(r.data,false)}catch(e){setDetailError(errText(e))}finally{setDetailLoading(false)}};
 const syncRemoteStatus=async(invoice,refresh=true)=>{if(!invoice?.KolaybiExternalId)return;try{const r=await axios.post(`${ACTIONS}/${invoice.FaturaId}/sync-status`);setSelected(x=>x&&x.FaturaId===invoice.FaturaId?{...x,KolaybiDurum:r.data.status,KolaybiEtTN:r.data.uuid||x.KolaybiEtTN,KolaybiFaturaNo:r.data.no||x.KolaybiFaturaNo}:x);setFaturalar(rows=>rows.map(x=>x.FaturaId===invoice.FaturaId?{...x,KolaybiDurum:r.data.status}:x))}catch(e){if(refresh)window.alert(`KolayBi durumu alınamadı: ${errText(e)}`)}};
 const localStatus=async(status)=>{if(!selected)return;setBusy(true);try{const r=await axios.post(`${ACTIONS}/${selected.FaturaId}/islem`,{action:'status',status});setSelected(x=>({...x,Durum:r.data.status}));setFaturalar(rows=>rows.map(x=>x.FaturaId===selected.FaturaId?{...x,Durum:r.data.status}:x));setOpenMenu(null)}catch(e){window.alert(errText(e))}finally{setBusy(false)}};
 const sendEDocument=async()=>{if(!selected)return;setBusy(true);try{const r=await axios.post(`${ACTIONS}/${selected.FaturaId}/e-belge-gonder`,{});setSelected(x=>({...x,KolaybiExternalId:r.data.kolaybiExternalId,KolaybiEtTN:r.data.uuid,KolaybiFaturaNo:r.data.no,KolaybiDurum:r.data.status,EbelgeSenaryo:r.data.scenario}));await load();window.alert('Fatura KolayBi üzerinden e-belgeye gönderildi.')}catch(e){window.alert(`E-belge gönderilemedi: ${errText(e)}`)}finally{setBusy(false);setOpenMenu(null)}};
 const remoteAction=async(action)=>{if(!selected)return;setBusy(true);try{let payload={action};if(action==='proceed'){const vaultId=window.prompt('KolayBi kasa/banka vault_id değerini girin:');if(!vaultId){setBusy(false);return}payload.vaultId=vaultId}const r=await axios.post(`${ACTIONS}/${selected.FaturaId}/islem`,payload);if(action==='delete'){setSelected(null);await load()}else if(action==='resend'){setSelected(x=>({...x,KolaybiDurum:r.data?.data?.status||x.KolaybiDurum}))}else{await syncRemoteStatus(selected,false)}window.alert(action==='proceed'?'Tahsilat KolayBi’ye işlendi.':action==='cancel'?'E-belge iptal edildi.':action==='resend'?'E-belge yeniden gönderildi.':'İşlem tamamlandı.')}catch(e){window.alert(errText(e))}finally{setBusy(false);setOpenMenu(null)}};
 const emailInvoice=()=>{const email=selected?.CariEposta||selected?.Eposta||selected?.Email||selected?.CariEmail;if(!email){window.alert('Bu faturada cari e-posta adresi bulunamadı.')}else window.location.href=`mailto:${email}?subject=${encodeURIComponent(`Fatura ${selected.FaturaKodu||''}`)}`;setOpenMenu(null)};
 const copyInvoice=async()=>{try{await navigator.clipboard.writeText(selected?.FaturaKodu||'');window.alert('Fatura numarası panoya kopyalandı.')}catch(_){window.prompt('Fatura numarası:',selected?.FaturaKodu||'')}setOpenMenu(null)};
 const columns=[{key:'FaturaKodu',label:'Fatura No'},{key:'Yon',label:'Yön'},{key:'CariKodu',label:'Cari Kodu'},{key:'CariAdi',label:'Cari'},{key:'FaturaTarihi',label:'Tarih'},{key:'VadeTarihi',label:'Vade'},{key:'GenelToplam',label:'Genel Toplam'},{key:'Durum',label:'Durum'}];
 return <div className="invoice-list-page">
  <section className="invoice-list-header"><div><span className="invoice-eyebrow">FATURA YÖNETİMİ</span><h1>Fatura Listesi</h1><p>KolayBi bağlantılı fatura detayları ve işlemleri.</p></div><button className="invoice-refresh" onClick={load}>Yenile</button></section>
  <section className="invoice-summary"><div><span>Filtrelenen kayıt</span><strong>{filtered.length.toLocaleString('tr-TR')}</strong></div><div><span>Toplam tutar</span><strong>{money(totalAmount)}</strong></div><div><span>Satış</span><strong>{filtered.filter(f=>f.Yon==='Satış').length}</strong></div><div><span>Alış</span><strong>{filtered.filter(f=>f.Yon==='Alış').length}</strong></div></section>
  <section className="invoice-filters"><div className="invoice-filter invoice-search"><label>Arama</label><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Fatura no, cari kodu veya cari adı"/></div><div className="invoice-filter"><label>Yön</label><select value={filters.yon} onChange={e=>setFilters({...filters,yon:e.target.value})}><option>Hepsi</option><option>Satış</option><option>Alış</option></select></div><div className="invoice-filter"><label>Durum</label><select value={filters.durum} onChange={e=>setFilters({...filters,durum:e.target.value})}><option>Hepsi</option>{STATUS_VALUES.map(x=><option key={x}>{x}</option>)}</select></div><div className="invoice-filter"><label>Başlangıç</label><input type="date" value={filters.start} onChange={e=>setFilters({...filters,start:e.target.value})}/></div><div className="invoice-filter"><label>Bitiş</label><input type="date" value={filters.end} onChange={e=>setFilters({...filters,end:e.target.value})}/></div><div className="invoice-filter"><label>En az tutar</label><input type="number" value={filters.min} onChange={e=>setFilters({...filters,min:e.target.value})}/></div><div className="invoice-filter"><label>En çok tutar</label><input type="number" value={filters.max} onChange={e=>setFilters({...filters,max:e.target.value})}/></div><button className="invoice-reset" onClick={()=>setFilters({search:'',yon:'Hepsi',durum:'Hepsi',start:'',end:'',min:'',max:''})}>Filtreleri Temizle</button></section>
  <section className="invoice-table-card"><div className="invoice-table-toolbar"><ExportToolbar data={filtered} columns={columns} filename="fatura-listesi"/><label>Sayfa başına<select value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}><option value="25">25</option><option value="50">50</option><option value="100">100</option></select></label></div>{error&&<div className="invoice-error">{error}</div>}{loading?<div className="invoice-loading">Faturalar yükleniyor…</div>:<div className="invoice-table-scroll"><table><thead><tr><th>Fatura No</th><th>Yön</th><th>Cari</th><th>Tarih</th><th>Vade</th><th>Toplam</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{visible.map(f=><tr key={f.FaturaId}><td><button className="invoice-code" onClick={()=>openDetail(f)}>{f.FaturaKodu||`#${f.FaturaId}`}</button></td><td><span className={`invoice-badge ${f.Yon==='Alış'?'purchase':'sale'}`}>{f.Yon||'—'}</span></td><td><strong>{f.CariAdi||'—'}</strong><small>{f.CariKodu||''}</small></td><td>{date(f.FaturaTarihi)}</td><td>{date(f.VadeTarihi)}</td><td className="invoice-amount">{money(f.GenelToplam,f.ParaBirimi)}</td><td>{f.Durum||'Bekliyor'}</td><td><button className="invoice-row-action" onClick={()=>openDetail(f)}>Görüntüle</button></td></tr>)}{!visible.length&&<tr><td colSpan="8" className="invoice-empty">Fatura bulunamadı.</td></tr>}</tbody></table></div>}<div className="invoice-pagination"><span>{filtered.length?`${(page-1)*pageSize+1}-${Math.min(page*pageSize,filtered.length)} / ${filtered.length}`:'0 kayıt'}</span><div><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Önceki</button><strong>{page} / {pageCount}</strong><button disabled={page>=pageCount} onClick={()=>setPage(v=>v+1)}>Sonraki</button></div></div></section>
  {(detailLoading||detailError||selected)&&<div className="invoice-drawer-backdrop" onMouseDown={()=>{setSelected(null);setOpenMenu(null)}}><aside className="invoice-drawer" onMouseDown={e=>e.stopPropagation()}><button className="invoice-drawer-close" onClick={()=>setSelected(null)}>×</button>{detailLoading&&<div className="invoice-loading">Fatura detayı yükleniyor…</div>}{detailError&&<div className="invoice-error">{detailError}</div>}{selected&&<>
   <div className="invoice-detail-top"><div><span>{selected.Yon||'Fatura'}</span><h2>{selected.FaturaKodu||`Fatura #${selected.FaturaId}`}</h2><p>{selected.CariAdi||'Cari bilgisi yok'}</p></div><div className="invoice-detail-menus">
    <div className="invoice-menu-wrap"><button className="invoice-main-button status" onClick={()=>setOpenMenu(openMenu==='status'?null:'status')}>Durum Değiştir ▾</button>{openMenu==='status'&&<div className="invoice-menu">{STATUS_VALUES.map(s=><button key={s} disabled={busy} onClick={()=>localStatus(s)}>{s}</button>)}</div>}</div>
    <button className="invoice-main-button collect" disabled={busy} onClick={()=>remoteAction('proceed')}>Tahsilata Kapat</button>
    <div className="invoice-menu-wrap"><button className="invoice-main-button actions" onClick={()=>setOpenMenu(openMenu==='actions'?null:'actions')}>İşlemler ▾</button>{openMenu==='actions'&&<div className="invoice-menu action-menu"><button onClick={emailInvoice}>✉ e-Fatura'ya e-Posta Gönder</button><button onClick={()=>remoteAction('proceed')}>▣ Tahsilata Kapat</button><button onClick={copyInvoice}>⧉ Kopyala</button><button className="danger" onClick={()=>remoteAction('delete')}>▢ Sil</button></div>}</div>
   </div></div>
   <div className="invoice-detail-sync"><span>KolayBi durumu: <strong>{selected.KolaybiDurum||'Bağlanmadı'}</strong></span><button onClick={()=>syncRemoteStatus(selected,true)} disabled={busy}>KolayBi'den Yenile</button>{selected.KolaybiExternalId?<button onClick={()=>remoteAction('resend')} disabled={busy}>Yeniden Gönder</button>:<button onClick={sendEDocument} disabled={busy}>e-Belge Gönder</button>}{selected.KolaybiExternalId&&<button onClick={()=>remoteAction('cancel')} disabled={busy}>E-Belge İptal</button>}</div>
   <div className="invoice-detail-grid"><div><span>Fatura tarihi</span><strong>{date(selected.FaturaTarihi)}</strong></div><div><span>Vade tarihi</span><strong>{date(selected.VadeTarihi)}</strong></div><div><span>Cari kodu</span><strong>{selected.CariKodu||'—'}</strong></div><div><span>Ödeme şekli</span><strong>{selected.OdemeSekli||'—'}</strong></div><div><span>Durum</span><strong>{selected.Durum||'Bekliyor'}</strong></div><div><span>ETTN</span><strong>{selected.KolaybiEtTN||'—'}</strong></div></div>
   <h3>Ürün / Hizmet Satırları ({selected.items?.length||0})</h3><div className="invoice-detail-lines"><table><thead><tr><th>Kod</th><th>Ürün / Hizmet</th><th>Miktar</th><th>Birim Fiyat</th><th>KDV</th><th>Satır Toplamı</th></tr></thead><tbody>{(selected.items||[]).map((line,i)=><tr key={line.FaturaDetayId||i}><td>{line.UrunKodu||'—'}</td><td>{line.UrunAdi||'—'}</td><td>{Number(line.Miktar||0).toLocaleString('tr-TR')} {line.Birim||''}</td><td>{money(line.BirimFiyat,selected.ParaBirimi)}</td><td>%{Number(line.KdvOrani||0)}</td><td>{money(line.SatirToplam||Number(line.Miktar||0)*Number(line.BirimFiyat||0),selected.ParaBirimi)}</td></tr>)}{!selected.items?.length&&<tr><td colSpan="6" className="invoice-empty">Satır bulunamadı.</td></tr>}</tbody></table></div><div className="invoice-detail-totals"><div><span>Ara toplam</span><strong>{money(selected.AraToplam,selected.ParaBirimi)}</strong></div><div><span>KDV</span><strong>{money(selected.KdvToplam,selected.ParaBirimi)}</strong></div><div className="grand"><span>Genel toplam</span><strong>{money(selected.GenelToplam,selected.ParaBirimi)}</strong></div></div>
  </>}</aside></div>}
 </div>
}