import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import SearchableSelect from '../components/SearchableSelect';
import './ReceteYonetimPage.css';

const API_URL='http://localhost:5000/api';
const TYPES=['Malzeme','Yarı Mamul','Hizmet','Fason','Nakliye','Ambalaj'];
const emptyForm={receteKodu:'',receteAdi:'',mamulUrunId:'',mamulAdi:'',aciklama:'',versiyon:1,uretimBirimi:'Adet',durum:'Aktif',receteTipi:'Mamul',ciktiMiktari:1,ciktiBirimi:'Adet',standartFireOrani:0};
const emptyItem={kalemTipi:'Malzeme',hammaddeUrunId:'',hammaddeAdi:'',altReceteId:'',girdiMiktari:'',girdiBirimi:'Adet',ciktiMiktari:'',ciktiBirimi:'',verimOrani:100,fireOrani:0,donusumAciklama:'',tedarikciCariId:'',fasonMu:false,hizmetBirimFiyati:0,nakliyeMaliyeti:0,iscilikDakika:0,makineDakika:0,iscilikBirimMaliyeti:0,makineBirimMaliyeti:0,depo:'Merkez Depo',operasyonSira:'',istasyonAdi:'',aciklama:''};
const emptyOp={istasyonAdi:'',islemAdi:'',tahminiSureDk:'',iscilikDakika:'',makineDakika:'',fasonMu:false,tedarikciCariId:'',hizmetMaliyeti:0,nakliyeMaliyeti:0,girdiMiktari:'',ciktiMiktari:'',ciktiBirimi:'',depo:'Merkez Depo',aciklama:''};
const money=n=>Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;

export default function ReceteYonetimPage(){
 const [urunler,setUrunler]=useState([]),[receteler,setReceteler]=useState([]),[cariler,setCariler]=useState([]);
 const [form,setForm]=useState({...emptyForm,receteKodu:`REC-${Date.now().toString().slice(-7)}`});
 const [item,setItem]=useState(emptyItem),[items,setItems]=useState([]),[op,setOp]=useState(emptyOp),[operations,setOperations]=useState([]);
 const [selected,setSelected]=useState(null),[tree,setTree]=useState(null),[cost,setCost]=useState(null),[need,setNeed]=useState(null);
 const [search,setSearch]=useState(''),[productionQty,setProductionQty]=useState(1),[activeTab,setActiveTab]=useState('agac');
 const [loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[treeLoading,setTreeLoading]=useState(false);

 const load=async()=>{setLoading(true);try{const [u,r,c]=await Promise.all([axios.get(`${API_URL}/urunler`),axios.get(`${API_URL}/recete-yonetim`),axios.get(`${API_URL}/cariler`).catch(()=>({data:[]}))]);setUrunler(u.data||[]);setReceteler(r.data||[]);setCariler(c.data||[]);}catch(e){alert(e.response?.data?.error||'Reçete verileri alınamadı.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const newCode=()=>`REC-${Date.now().toString().slice(-7)}`;
 const reset=()=>{setForm({...emptyForm,receteKodu:newCode()});setItems([]);setOperations([]);setSelected(null);setTree(null);setCost(null);setNeed(null);setItem(emptyItem);setOp(emptyOp);setProductionQty(1);};
 const mamulOptions=useMemo(()=>urunler.filter(u=>u.Tur!=='Hizmet').map(u=>({value:u.UrunId,label:u.UrunAdi,sublabel:u.UrunKodu})),[urunler]);
 const productOptions=useMemo(()=>urunler.map(u=>({value:u.UrunId,label:u.UrunAdi,sublabel:u.UrunKodu})),[urunler]);
 const recipeOptions=useMemo(()=>receteler.filter(r=>!form.mamulUrunId||String(r.MamulUrunId)!==String(form.mamulUrunId)).map(r=>({value:r.ReceteId,label:r.ReceteAdi||r.MamulAdi,sublabel:`${r.ReceteKodu} · ${r.MamulAdi}`})),[receteler,form.mamulUrunId]);
 const cariOptions=useMemo(()=>cariler.map(c=>({value:c.CariId,label:c.CariAdi,sublabel:c.CariKodu})),[cariler]);
 const filtered=receteler.filter(r=>`${r.ReceteKodu} ${r.MamulAdi} ${r.ReceteAdi||''}`.toLocaleLowerCase('tr-TR').includes(search.toLocaleLowerCase('tr-TR')));
 const selectedProduct=urunler.find(u=>String(u.UrunId)===String(item.hammaddeUrunId));

 const loadAnalysis=async(id=selected?.ReceteId,qty=productionQty)=>{if(!id)return;try{const [c,n]=await Promise.all([axios.get(`${API_URL}/recete-agaci/${id}/maliyet?miktar=${qty}`),axios.get(`${API_URL}/recete-agaci/${id}/malzeme-ihtiyaci?miktar=${qty}`)]);setCost(c.data);setNeed(n.data);}catch(e){console.warn(e);}};
 const loadTree=async(id=selected?.ReceteId)=>{if(!id)return;setTreeLoading(true);try{const {data}=await axios.get(`${API_URL}/recete-agaci/${id}/agac`);setTree(data);}catch(e){setTree(null);console.warn(e);}finally{setTreeLoading(false);}};
 const openRecipe=async r=>{try{const {data}=await axios.get(`${API_URL}/recete-yonetim/${r.ReceteId}`);setSelected(data);setForm({receteKodu:data.ReceteKodu||'',receteAdi:data.ReceteAdi||'',mamulUrunId:data.MamulUrunId||'',mamulAdi:data.MamulAdi||'',aciklama:data.Aciklama||'',versiyon:data.Versiyon||1,uretimBirimi:data.UretimBirimi||'Adet',durum:data.Durum||'Aktif',receteTipi:data.ReceteTipi||'Mamul',ciktiMiktari:data.CiktiMiktari||1,ciktiBirimi:data.CiktiBirimi||data.UretimBirimi||'Adet',standartFireOrani:data.StandartFireOrani||0});setItems((data.items||[]).map((x,i)=>({...fromDbItem(x),id:`db-${i}`})));setOperations((data.operations||[]).map((x,i)=>({...fromDbOp(x),id:`op-${i}`})));setProductionQty(1);await loadTree(r.ReceteId);await loadAnalysis(r.ReceteId,1);}catch(e){alert(e.response?.data?.error||'Reçete detayı alınamadı.');}};
 const fromDbItem=x=>({kalemTipi:x.KalemTipi||'Malzeme',hammaddeUrunId:x.HammaddeUrunId||'',hammaddeAdi:x.HammaddeAdi||'',altReceteId:x.AltReceteId||'',girdiMiktari:x.GirdiMiktari??x.Miktar??'',girdiBirimi:x.GirdiBirimi||x.Birim||'Adet',ciktiMiktari:x.CiktiMiktari??'',ciktiBirimi:x.CiktiBirimi||x.Birim||'',verimOrani:x.VerimOrani??100,fireOrani:x.FireOrani??0,donusumAciklama:x.DonusumAciklama||'',tedarikciCariId:x.TedarikciCariId||'',fasonMu:!!x.FasonMu,hizmetBirimFiyati:x.HizmetBirimFiyati??0,nakliyeMaliyeti:x.NakliyeMaliyeti??0,iscilikDakika:x.IscilikDakika??0,makineDakika:x.MakineDakika??0,iscilikBirimMaliyeti:x.IscilikBirimMaliyeti??0,makineBirimMaliyeti:x.MakineBirimMaliyeti??0,depo:x.Depo||'Merkez Depo',operasyonSira:x.OperasyonSira||'',istasyonAdi:x.IstasyonAdi||x.Istasyon||'',aciklama:x.Aciklama||''});
 const fromDbOp=x=>({istasyonAdi:x.IstasyonAdi||'',islemAdi:x.IslemAdi||'',tahminiSureDk:x.TahminiSureDk??'',iscilikDakika:x.IscilikDakika??'',makineDakika:x.MakineDakika??'',fasonMu:!!x.FasonMu,tedarikciCariId:x.TedarikciCariId||'',hizmetMaliyeti:x.HizmetMaliyeti??0,nakliyeMaliyeti:x.NakliyeMaliyeti??0,girdiMiktari:x.GirdiMiktari??'',ciktiMiktari:x.CiktiMiktari??'',ciktiBirimi:x.CiktiBirimi||'',depo:x.Depo||'Merkez Depo',aciklama:x.Aciklama||''});
 const setProduct=id=>{const u=urunler.find(x=>String(x.UrunId)===String(id));setItem(v=>({...v,hammaddeUrunId:id,hammaddeAdi:u?.UrunAdi||'',girdiBirimi:u?.Birim||'Adet',ciktiBirimi:u?.Birim||'Adet'}));};
 const addItem=()=>{const type=item.kalemTipi;if(type==='Yarı Mamul'&&!item.altReceteId)return alert('Yarı mamul için Alt Reçete seçin.');if(type!=='Nakliye'&&!item.hammaddeUrunId&&!item.hammaddeAdi)return alert('Ürün/hizmet seçin.');if(num(item.girdiMiktari)<=0&&type!=='Nakliye')return alert('Girdi miktarı 0 olamaz.');if(type==='Nakliye'&&num(item.nakliyeMaliyeti)<=0)return alert('Nakliye maliyeti girin.');const u=urunler.find(x=>String(x.UrunId)===String(item.hammaddeUrunId));setItems(v=>[...v,{...item,hammaddeAdi:u?.UrunAdi||item.hammaddeAdi,id:crypto.randomUUID()}]);setItem({...emptyItem,kalemTipi:item.kalemTipi,depo:item.depo});};
 const addOp=()=>{if(!op.istasyonAdi)return alert('İstasyon adı girin.');setOperations(v=>[...v,{...op,id:crypto.randomUUID()}]);setOp(emptyOp);};
 const save=async()=>{if(!form.mamulUrunId)return alert('Mamul ürün seçin.');if(!items.length)return alert('En az bir reçete kalemi ekleyin.');setSaving(true);try{const payload={form,items,operations};const url=selected?.ReceteId?`${API_URL}/recete-yonetim/${selected.ReceteId}`:`${API_URL}/recete-yonetim`;await (selected?.ReceteId?axios.put(url,payload):axios.post(url,payload));alert(selected?'Reçete güncellendi.':'Reçete başarıyla kaydedildi.');await load();reset();}catch(e){alert(e.response?.data?.detail||e.response?.data?.error||'Reçete kaydedilemedi.');}finally{setSaving(false);}};
 const createRevision=async()=>{if(!selected?.ReceteId)return;if(!window.confirm(`V${form.versiyon} reçetesinden yeni revizyon oluşturulsun mu?`))return;try{const {data}=await axios.post(`${API_URL}/recete-yonetim/${selected.ReceteId}/revizyon`);alert(data.message||'Revizyon oluşturuldu.');await load();const r=receteler.find(x=>x.ReceteId===data.receteId);if(r)await openRecipe(r);}catch(e){alert(e.response?.data?.error||'Revizyon oluşturulamadı.');}};
 const simulate=async()=>{const q=Math.max(0,num(productionQty,1));setProductionQty(q);if(selected?.ReceteId)await loadAnalysis(selected.ReceteId,q);};
 const typeChange=t=>setItem(v=>({...v,kalemTipi:t,fasonMu:t==='Fason'||v.fasonMu}));
 const itemLabel=x=>x.hammaddeAdi||x.HammaddeAdi||x.AltReceteAdi||'Tanımsız kalem';
 const typeClass=t=>String(t||'Malzeme').toLowerCase().replace(' ','-');

 return <div className="recete-v2">
  <header className="recete-v2-title"><div><span>ÜRETİM MÜHENDİSLİĞİ</span><h1>Reçete Yönetimi · Üretim Ağacı</h1><p>Çok seviyeli yarı mamul, fason, hizmet, dönüşüm, operasyon ve gerçek üretim maliyeti</p></div><div className="rv2-title-actions">{selected?.ReceteId&&<button className="rv2-secondary" onClick={createRevision}>↗ Yeni Revizyon</button>}<button className="rv2-primary" onClick={reset}>+ Yeni Reçete</button></div></header>
  <div className="rv2-layout">
   <aside className="rv2-list"><div className="rv2-list-head"><strong>Reçete Kartları</strong><span>{receteler.length}</span></div><input className="rv2-search" placeholder="Kod, mamul veya reçete ara..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="rv2-scroll">{loading?<div className="rv2-empty">Yükleniyor...</div>:filtered.map(r=><button className={`rv2-recipe ${selected?.ReceteId===r.ReceteId?'active':''}`} key={r.ReceteId} onClick={()=>openRecipe(r)}><b>{r.ReceteKodu}</b><span>{r.MamulAdi}</span><small>{r.ReceteTipi||'Mamul'} · Çıktı {r.CiktiMiktari||1} {r.CiktiBirimi||r.UretimBirimi||'Adet'} · V{r.Versiyon||1}</small></button>)}{!filtered.length&&!loading&&<div className="rv2-empty">Reçete bulunamadı.</div>}</div></aside>
   <main className="rv2-main">
    <section className="rv2-card"><div className="rv2-section-title"><div><span>01</span><h2>Reçete Kartı</h2></div><label className="rv2-status"><input type="checkbox" checked={form.durum==='Aktif'} onChange={e=>setForm({...form,durum:e.target.checked?'Aktif':'Pasif'})}/> Aktif</label></div>{selected&&<div className="rv2-edit-banner"><b>Düzenleme modu</b><span>{form.receteKodu} · V{form.versiyon}</span><button onClick={reset}>Düzenlemeyi bırak</button></div>}<div className="rv2-grid">
     <label>Reçete Kodu<input value={form.receteKodu} onChange={e=>setForm({...form,receteKodu:e.target.value})}/></label><label>Reçete Adı<input value={form.receteAdi} onChange={e=>setForm({...form,receteAdi:e.target.value})} placeholder="Örn. AHBRD 1301 Ana Reçete"/></label>
     <label className="wide">Üretilecek Mamul<SearchableSelect options={mamulOptions} value={form.mamulUrunId} onChange={id=>{const u=urunler.find(x=>String(x.UrunId)===String(id));setForm({...form,mamulUrunId:id,mamulAdi:u?.UrunAdi||''})}} placeholder="Mamul ürün seçin..."/></label>
     <label>Reçete Tipi<select value={form.receteTipi} onChange={e=>setForm({...form,receteTipi:e.target.value})}><option>Mamul</option><option>Yarı Mamul</option><option>Alt Montaj</option><option>Proses</option></select></label><label>Revizyon<input type="number" min="1" value={form.versiyon} onChange={e=>setForm({...form,versiyon:e.target.value})}/></label>
     <label>Çıktı Miktarı<input type="number" min="0.0001" step="0.0001" value={form.ciktiMiktari} onChange={e=>setForm({...form,ciktiMiktari:e.target.value})}/></label><label>Çıktı Birimi<input value={form.ciktiBirimi} onChange={e=>setForm({...form,ciktiBirimi:e.target.value})}/></label><label>Standart Fire %<input type="number" min="0" step="0.01" value={form.standartFireOrani} onChange={e=>setForm({...form,standartFireOrani:e.target.value})}/></label><label>Üretim Birimi<input value={form.uretimBirimi} onChange={e=>setForm({...form,uretimBirimi:e.target.value})}/></label>
     <label className="wide">Açıklama<input value={form.aciklama} onChange={e=>setForm({...form,aciklama:e.target.value})} placeholder="Proses, kalite, özel uygulama veya ürün notu"/></label>
    </div></section>

    <section className="rv2-card"><div className="rv2-section-title"><div><span>02</span><h2>Üretim Kalemleri</h2></div><b>{items.length} kalem</b></div>
     <div className="rv2-typebar">{TYPES.map(t=><button key={t} className={item.kalemTipi===t?'active':''} onClick={()=>typeChange(t)}>{t}</button>)}</div>
     <div className="rv2-entry rv2-item-entry">
       <select value={item.kalemTipi} onChange={e=>typeChange(e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select>
       {item.kalemTipi==='Yarı Mamul'?<SearchableSelect options={recipeOptions} value={item.altReceteId} onChange={id=>{const r=receteler.find(x=>String(x.ReceteId)===String(id));setItem({...item,altReceteId:id,hammaddeAdi:r?.MamulAdi||r?.ReceteAdi||''})}} placeholder="Alt reçete / yarı mamul seçin..."/>:<SearchableSelect options={productOptions} value={item.hammaddeUrunId} onChange={setProduct} placeholder={item.kalemTipi==='Nakliye'?'Ürün/rota seçin...':'Malzeme veya hizmet seçin...'}/>} 
       <input placeholder="Girdi miktarı" type="number" min="0" step="0.0001" value={item.girdiMiktari} onChange={e=>setItem({...item,girdiMiktari:e.target.value})}/><input placeholder="Birim" value={item.girdiBirimi} onChange={e=>setItem({...item,girdiBirimi:e.target.value})}/><input placeholder="Fire %" type="number" min="0" step="0.01" value={item.fireOrani} onChange={e=>setItem({...item,fireOrani:e.target.value})}/><button className="rv2-add" onClick={addItem}>+ Ekle</button>
     </div>
     <div className="rv2-advanced"><div><label>Çıktı Miktarı<input type="number" min="0" step="0.0001" value={item.ciktiMiktari} onChange={e=>setItem({...item,ciktiMiktari:e.target.value})}/></label><label>Verim %<input type="number" min="0" max="100" step="0.01" value={item.verimOrani} onChange={e=>setItem({...item,verimOrani:e.target.value})}/></label><label>İstasyon<input value={item.istasyonAdi} onChange={e=>setItem({...item,istasyonAdi:e.target.value})} placeholder="Kesim / Baskı / Kaynak..."/></label><label>Depo<input value={item.depo} onChange={e=>setItem({...item,depo:e.target.value})}/></label></div><div><label>Fason Cari<SearchableSelect options={cariOptions} value={item.tedarikciCariId} onChange={id=>setItem({...item,tedarikciCariId:id,fasonMu:item.kalemTipi==='Fason'||item.fasonMu})} placeholder="Tedarikçi / fason firma"/></label><label>Hizmet Birim Fiyatı<input type="number" min="0" step="0.0001" value={item.hizmetBirimFiyati} onChange={e=>setItem({...item,hizmetBirimFiyati:e.target.value})}/></label><label>Nakliye Maliyeti<input type="number" min="0" step="0.0001" value={item.nakliyeMaliyeti} onChange={e=>setItem({...item,nakliyeMaliyeti:e.target.value})}/></label><label>İşçilik dk<input type="number" min="0" step="0.01" value={item.iscilikDakika} onChange={e=>setItem({...item,iscilikDakika:e.target.value})}/></label><label>Makine dk<input type="number" min="0" step="0.01" value={item.makineDakika} onChange={e=>setItem({...item,makineDakika:e.target.value})}/></label></div><div><label>Dönüşüm Notu<input value={item.donusumAciklama} onChange={e=>setItem({...item,donusumAciklama:e.target.value})} placeholder="1250x2500 → 5 adet 1250x500"/></label><label>Satır Açıklaması<input value={item.aciklama} onChange={e=>setItem({...item,aciklama:e.target.value})}/></label></div></div>
     {selectedProduct&&<div className="rv2-note">Ürün: <b>{selectedProduct.UrunKodu}</b> · Birim: <b>{selectedProduct.Birim||'Adet'}</b> · Alış fiyatı: <b>{money(selectedProduct.AlisFiyati)} TL</b></div>}
     <div className="rv2-table-wrap"><table><thead><tr><th>#</th><th>Tip</th><th>Kalem</th><th>Girdi</th><th>Çıktı</th><th>Fire/Verim</th><th>Fason/Hizmet</th><th>Maliyet</th><th></th></tr></thead><tbody>{items.map((x,i)=><tr key={x.id}><td>{i+1}</td><td><span className={`rv2-type ${typeClass(x.kalemTipi)}`}>{x.kalemTipi}</span></td><td><b>{itemLabel(x)}</b>{x.altReceteId&&<small className="rv2-subline">Alt reçete #{x.altReceteId}</small>}</td><td>{x.girdiMiktari??x.Miktar} {x.girdiBirimi||x.Birim}</td><td>{x.ciktiMiktari||'—'} {x.ciktiBirimi||''}</td><td>{num(x.fireOrani).toFixed(2)}% / {num(x.verimOrani,100).toFixed(2)}%</td><td>{x.tedarikciCariId?'✓ Cari':''}{x.fasonMu?' · Fason':''}</td><td>{x.kalemTipi==='Nakliye'?money(x.nakliyeMaliyeti):money(x.hizmetBirimFiyati)} TL</td><td><button className="rv2-del" onClick={()=>setItems(v=>v.filter(y=>y.id!==x.id))}>Sil</button></td></tr>)}{!items.length&&<tr><td colSpan="9" className="rv2-empty">Henüz kalem eklenmedi. AHBRD 1301 için tabla, ayak, kademe, kılıf, aksesuar ve ambalaj grupları burada ayrı ayrı kurulacak.</td></tr>}</tbody></table></div>
    </section>

    <section className="rv2-card"><div className="rv2-section-title"><div><span>03</span><h2>Operasyon Rotası</h2></div><b>{operations.length} operasyon</b></div>
      <div className="rv2-entry rv2-op"><input placeholder="İstasyon" value={op.istasyonAdi} onChange={e=>setOp({...op,istasyonAdi:e.target.value})}/><input placeholder="İşlem" value={op.islemAdi} onChange={e=>setOp({...op,islemAdi:e.target.value})}/><input type="number" placeholder="Süre dk" value={op.tahminiSureDk} onChange={e=>setOp({...op,tahminiSureDk:e.target.value})}/><input type="number" placeholder="İşçilik dk" value={op.iscilikDakika} onChange={e=>setOp({...op,iscilikDakika:e.target.value})}/><input type="number" placeholder="Makine dk" value={op.makineDakika} onChange={e=>setOp({...op,makineDakika:e.target.value})}/><button className="rv2-add" onClick={addOp}>+ Ekle</button></div>
      <div className="rv2-op-advanced"><label>Fason Cari<SearchableSelect options={cariOptions} value={op.tedarikciCariId} onChange={id=>setOp({...op,tedarikciCariId:id,fasonMu:true})} placeholder="Fason firma"/></label><label>Hizmet Maliyeti<input type="number" min="0" step="0.01" value={op.hizmetMaliyeti} onChange={e=>setOp({...op,hizmetMaliyeti:e.target.value})}/></label><label>Nakliye Maliyeti<input type="number" min="0" step="0.01" value={op.nakliyeMaliyeti} onChange={e=>setOp({...op,nakliyeMaliyeti:e.target.value})}/></label><label>Depo<input value={op.depo} onChange={e=>setOp({...op,depo:e.target.value})}/></label></div>
      <div className="rv2-route">{operations.map((x,i)=><div className="rv2-op-chip" key={x.id}><strong>{i+1}</strong><span>{x.istasyonAdi}</span>{x.islemAdi&&<small>{x.islemAdi}</small>}<em>{x.tahminiSureDk||0} dk</em>{x.fasonMu&&<i>FASON</i>}<button onClick={()=>setOperations(v=>v.filter(y=>y.id!==x.id))}>×</button></div>)}{!operations.length&&<div className="rv2-empty">Operasyon rotası henüz oluşturulmadı.</div>}</div>
    </section>

    <section className="rv2-card rv2-analysis"><div className="rv2-analysis-head"><div><span>04</span><h2>Üretim Simülasyonu</h2><p>Üretim adedini değiştir; çok seviyeli malzeme ihtiyacı ve maliyet anında hesaplanır.</p></div><div className="rv2-sim"><input type="number" min="0.0001" step="1" value={productionQty} onChange={e=>setProductionQty(e.target.value)}/><span>{form.ciktiBirimi||form.uretimBirimi||'Adet'}</span><button className="rv2-primary" disabled={!selected||treeLoading} onClick={simulate}>Hesapla</button></div></div>
      <div className="rv2-tabs">{[['agac','Üretim Ağacı'],['ihtiyac','Malzeme İhtiyacı'],['maliyet','Maliyet']].map(([k,t])=><button key={k} className={activeTab===k?'active':''} onClick={()=>setActiveTab(k)}>{t}</button>)}</div>
      {activeTab==='agac'&&<div className="rv2-tree-panel">{!selected?<div className="rv2-empty">Ağaç görünümü için kayıtlı bir reçete seçin.</div>:treeLoading?<div className="rv2-empty">Ağaç yükleniyor...</div>:tree?<RecipeTree tree={tree} receteler={receteler}/>:<div className="rv2-empty">Ağaç okunamadı. Migration 006 ve backend rotasını kontrol edin.</div>}</div>}
      {activeTab==='ihtiyac'&&<div className="rv2-table-wrap">{need?<table><thead><tr><th>Seviye</th><th>Kalem</th><th>Tip</th><th>İhtiyaç</th><th>Fire</th></tr></thead><tbody>{(need.items||[]).map((x,i)=><tr key={i}><td>{x.seviye}</td><td><b>{x.urunAdi}</b></td><td>{x.kalemTipi}</td><td>{money(x.miktar)} {x.birim}</td><td>{money(x.fireOrani)}%</td></tr>)}</tbody></table>:<div className="rv2-empty">Üretim miktarı hesaplamak için kayıtlı reçete seçin.</div>}</div>}
      {activeTab==='maliyet'&&<div className="rv2-cost-grid"><Cost title="Hammadde" value={cost?.materialCost}/><Cost title="Hizmet / Fason" value={cost?.serviceCost}/><Cost title="Nakliye" value={cost?.transportCost}/><Cost title="İşçilik" value={cost?.laborCost}/><Cost title="Makine" value={cost?.machineCost}/><Cost title="Birim Maliyet" value={cost?.unitCost}/><div className="total"><small>TOPLAM ÜRETİM MALİYETİ</small><strong>{money(cost?.totalCost)} TL</strong><span>{money(productionQty)} {form.ciktiBirimi||'Adet'}</span></div></div>}
      {cost&&<div className="rv2-analysis-footer">İşçilik: <b>{money(cost.iscilikDakika)} dk</b> · Makine: <b>{money(cost.makineDakika)} dk</b> · Tahmini rota: <b>{money(cost.tahminiSureDk)} dk</b></div>}
    </section>
    <div className="rv2-actions"><button className="rv2-secondary" onClick={reset}>Temizle</button><button className="rv2-primary" disabled={saving} onClick={save}>{saving?'Kaydediliyor...':selected?'✓ Değişiklikleri Kaydet':'✓ Reçeteyi Kaydet'}</button></div>
   </main>
  </div>
 </div>;
}

function Cost({title,value}){return <div><small>{title}</small><strong>{money(value)} TL</strong></div>}
function RecipeTree({tree}){const h=tree.recipe||{};const rows=tree.items||[];return <div className="rv2-tree"><div className="tree-root"><span>ANA ÜRÜN</span><b>{h.MamulKodu||h.ReceteKodu}</b><strong>{h.MamulAdi}</strong><em>Çıktı: {h.CiktiMiktari||1} {h.CiktiBirimi||h.UretimBirimi||'Adet'}</em></div>{rows.map((x,i)=><div className="tree-row" key={x.ReceteDetayId||i}><div className="tree-line"/><span className={`rv2-type ${typeClass(x.KalemTipi)}`}>{x.KalemTipi||'Malzeme'}</span><div><b>{x.HammaddeAdi||x.AltMamulAdi||x.AltReceteAdi||'Kalem'}</b><small>{x.UrunKodu||x.AltReceteKodu||''} · Girdi {x.GirdiMiktari??x.Miktar??0} {x.GirdiBirimi||x.Birim||''}</small>{x.AltReceteId&&<div className="tree-alt">↳ Alt reçete: {x.AltReceteKodu||x.AltReceteAdi||x.AltReceteId}</div>}</div><strong>{x.FasonMu?'FASON':x.IstasyonAdi||x.Istasyon||''}</strong></div>)}</div>}
function typeClass(t){return String(t||'Malzeme').toLowerCase().replace(' ','-');}
function money(n){return Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});}
