const express=require('express');const{createAuthMiddleware,requirePermission}=require('./security');const{assertPeriodOpen,nextDocumentNumber,writeAudit}=require('./coreService');
const fail=(res,e)=>res.status(e.statusCode||500).json({success:false,error:e.message});
const err=(m,s=400)=>Object.assign(new Error(m),{statusCode:s});
module.exports=function(app,poolPromise,sql){const r=express.Router();r.use(createAuthMiddleware({poolPromise,sql}));
r.get('/overview',requirePermission('erp.read'),async(req,res)=>{try{const p=await poolPromise,q=await p.request().input('C',sql.Int,req.companyId).query(`SELECT DepartmanId,DepartmanKodu,DepartmanAdi,YoneticiPersonelId,IsActive FROM dbo.IkDepartmanlar WHERE CompanyId=@C ORDER BY DepartmanAdi;SELECT g.GorevId,g.GorevKodu,g.GorevAdi,g.DepartmanId,d.DepartmanAdi,g.IsActive FROM dbo.IkGorevler g JOIN dbo.IkDepartmanlar d ON d.CompanyId=g.CompanyId AND d.DepartmanId=g.DepartmanId WHERE g.CompanyId=@C ORDER BY d.DepartmanAdi,g.GorevAdi;SELECT TOP(200)* FROM dbo.IkMesailer WHERE CompanyId=@C ORDER BY Tarih DESC,MesaiId DESC;SELECT TOP(200)* FROM dbo.IkAvanslar WHERE CompanyId=@C ORDER BY TalepTarihi DESC,AvansId DESC;SELECT TOP(200)* FROM dbo.IkPerformansDegerlendirmeleri WHERE CompanyId=@C ORDER BY DegerlendirmeId DESC;SELECT TOP(100)* FROM dbo.IkEgitimler WHERE CompanyId=@C ORDER BY BaslangicTarihi DESC;SELECT (SELECT COUNT(*) FROM dbo.IkDepartmanlar WHERE CompanyId=@C AND IsActive=1)Departman,(SELECT COUNT(*) FROM dbo.IkMesailer WHERE CompanyId=@C AND OnayDurumu=N'Bekliyor')BekleyenMesai,(SELECT COUNT(*) FROM dbo.IkAvanslar WHERE CompanyId=@C AND Durum=N'Bekliyor')BekleyenAvans,(SELECT COUNT(*) FROM dbo.IkEgitimler WHERE CompanyId=@C AND Durum=N'Planlandı')PlanliEgitim;`);res.json({departments:q.recordsets[0],positions:q.recordsets[1],overtimes:q.recordsets[2],advances:q.recordsets[3],performance:q.recordsets[4],trainings:q.recordsets[5],summary:q.recordsets[6][0]});}catch(e){fail(res,e)}});
r.post('/departments',requirePermission('erp.write'),async(req,res)=>{try{const code=String(req.body?.code||'').trim(),name=String(req.body?.name||'').trim();if(!code||!name)return res.status(400).json({success:false,error:'Departman kodu ve adı zorunludur.'});const p=await poolPromise,q=await p.request().input('C',sql.Int,req.companyId).input('K',sql.NVarChar(40),code).input('A',sql.NVarChar(160),name).input('Y',sql.Int,req.body?.managerPersonnelId||null).input('U',sql.Int,req.auth.userId).query('INSERT dbo.IkDepartmanlar(CompanyId,DepartmanKodu,DepartmanAdi,YoneticiPersonelId,CreatedBy) OUTPUT INSERTED.DepartmanId VALUES(@C,@K,@A,@Y,@U)');const id=q.recordset[0].DepartmanId;await writeAudit({poolPromise,sql,companyId:req.companyId,userId:req.auth.userId,actionCode:'HR_DEPARTMENT_CREATE',entityType:'IkDepartman',entityId:id,after:{code,name},req});res.status(201).json({success:true,departmentId:id});}catch(e){fail(res,e)}});
r.post('/positions',requirePermission('erp.write'),async(req,res)=>{try{const departmentId=Number(req.body?.departmentId),code=String(req.body?.code||'').trim(),name=String(req.body?.name||'').trim();if(!Number.isInteger(departmentId)||!code||!name)return res.status(400).json({success:false,error:'Departman, görev kodu ve adı zorunludur.'});const p=await poolPromise,q=await p.request().input('C',sql.Int,req.companyId).input('D',sql.BigInt,departmentId).input('K',sql.NVarChar(40),code).input('A',sql.NVarChar(160),name).input('N',sql.NVarChar(600),req.body?.description||null).input('U',sql.Int,req.auth.userId).query(`IF NOT EXISTS(SELECT 1 FROM dbo.IkDepartmanlar WHERE CompanyId=@C AND DepartmanId=@D)THROW 52401,N'Departman bulunamadı.',1;INSERT dbo.IkGorevler(CompanyId,DepartmanId,GorevKodu,GorevAdi,Aciklama,CreatedBy)OUTPUT INSERTED.GorevId VALUES(@C,@D,@K,@A,@N,@U)`);res.status(201).json({success:true,positionId:q.recordset[0].GorevId});}catch(e){fail(res,e)}});
r.post('/assignments',requirePermission('erp.write'),async(req,res)=>{try{const person=Number(req.body?.personnelId),dep=Number(req.body?.departmentId),pos=req.body?.positionId?Number(req.body.positionId):null,start=new Date(req.body?.startDate);if(!Number.isInteger(person)||!Number.isInteger(dep)||Number.isNaN(start.getTime()))return res.status(400).json({success:false,error:'Personel, departman ve başlangıç tarihi zorunludur.'});const p=await poolPromise,t=new sql.Transaction(p);await t.begin();try{await new sql.Request(t).input('C',sql.Int,req.companyId).input('P',sql.Int,person).input('D',sql.BigInt,dep).input('G',sql.BigInt,pos).input('B',sql.Date,start).input('N',sql.NVarChar(500),req.body?.description||null).input('U',sql.Int,req.auth.userId).query(`UPDATE dbo.IkPersonelAtamalari SET IsActive=0,BitisTarihi=DATEADD(DAY,-1,@B) WHERE CompanyId=@C AND PersonelId=@P AND IsActive=1;INSERT dbo.IkPersonelAtamalari(CompanyId,PersonelId,DepartmanId,GorevId,BaslangicTarihi,Aciklama,CreatedBy)VALUES(@C,@P,@D,@G,@B,@N,@U)`);await t.commit();res.status(201).json({success:true});}catch(e){await t.rollback();throw e}}catch(e){fail(res,e)}});
r.post('/overtimes',requirePermission('erp.write'),async(req,res)=>{try{const person=Number(req.body?.personnelId),date=new Date(req.body?.date),hours=Number(req.body?.hours),rate=Number(req.body?.hourlyRate||0);if(!Number.isInteger(person)||Number.isNaN(date.getTime())||hours<=0||hours>24||rate<0)return res.status(400).json({success:false,error:'Geçerli personel, tarih, süre ve ücret zorunludur.'});const p=await poolPromise,q=await p.request().input('C',sql.Int,req.companyId).input('P',sql.Int,person).input('T',sql.Date,date).input('S',sql.Decimal(8,2),hours).input('R',sql.Decimal(18,2),rate).input('M',sql.NVarChar(30),req.body?.type||'Normal').input('N',sql.NVarChar(500),req.body?.description||null).input('U',sql.Int,req.auth.userId).query('INSERT dbo.IkMesailer(CompanyId,PersonelId,Tarih,SureSaat,SaatUcreti,MesaiTuru,Aciklama,CreatedBy)OUTPUT INSERTED.MesaiId,INSERTED.Tutar VALUES(@C,@P,@T,@S,@R,@M,@N,@U)');res.status(201).json({success:true,...q.recordset[0]});}catch(e){fail(res,e)}});
r.post('/overtimes/:id/decision',requirePermission('erp.approve'),async(req,res)=>{try{const id=Number(req.params.id),status=req.body?.approved?'Onaylandı':'Reddedildi',p=await poolPromise,q=await p.request().input('C',sql.Int,req.companyId).input('I',sql.BigInt,id).input('D',sql.NVarChar(24),status).input('U',sql.Int,req.auth.userId).query(`UPDATE dbo.IkMesailer SET OnayDurumu=@D,ApprovedBy=@U,ApprovedAt=SYSUTCDATETIME() OUTPUT INSERTED.MesaiId WHERE CompanyId=@C AND MesaiId=@I AND OnayDurumu=N'Bekliyor'`);if(!q.recordset[0])return res.status(409).json({success:false,error:'Mesai bulunamadı veya daha önce karara bağlandı.'});res.json({success:true,status});}catch(e){fail(res,e)}});
r.post('/advances',requirePermission('erp.write'),async(req,res)=>{try{const person=Number(req.body?.personnelId),date=new Date(req.body?.requestDate),amount=Number(req.body?.amount);if(!Number.isInteger(person)||Number.isNaN(date.getTime())||amount<=0)return res.status(400).json({success:false,error:'Geçerli personel, tarih ve tutar zorunludur.'});const p=await poolPromise,q=await p.request().input('C',sql.Int,req.companyId).input('P',sql.Int,person).input('T',sql.Date,date).input('A',sql.Decimal(18,2),amount).input('N',sql.NVarChar(500),req.body?.description||null).input('U',sql.Int,req.auth.userId).query('INSERT dbo.IkAvanslar(CompanyId,PersonelId,TalepTarihi,Tutar,Aciklama,CreatedBy)OUTPUT INSERTED.AvansId VALUES(@C,@P,@T,@A,@N,@U)');res.status(201).json({success:true,advanceId:q.recordset[0].AvansId});}catch(e){fail(res,e)}});
r.post('/advances/:id/decision',requirePermission('erp.approve'),async(req,res)=>{
  const id=Number(req.params.id);
  const approved=!!req.body?.approved;
  const channel=req.body?.channel==='Banka'?'Banka':'Kasa';
  const account=channel==='Kasa'?'100':'102';
  const p=await poolPromise,t=new sql.Transaction(p);
  try{
    await t.begin(sql.ISOLATION_LEVEL.SERIALIZABLE);
    const q=await new sql.Request(t).input('C',sql.Int,req.companyId).input('I',sql.BigInt,id)
      .query(`SELECT a.*,pr.AdSoyad FROM dbo.IkAvanslar a WITH(UPDLOCK,HOLDLOCK) LEFT JOIN dbo.Personeller pr ON pr.PersonelId=a.PersonelId WHERE a.CompanyId=@C AND a.AvansId=@I AND a.Durum=N'Bekliyor';`);
    const advance=q.recordset[0];
    if(!advance) throw err('Avans bulunamadı veya daha önce karara bağlandı.',409);

    if(!approved){
      await new sql.Request(t).input('C',sql.Int,req.companyId).input('I',sql.BigInt,id).input('U',sql.Int,req.auth.userId)
        .query(`UPDATE dbo.IkAvanslar SET Durum=N'Reddedildi',ApprovedBy=@U,ApprovedAt=SYSUTCDATETIME() WHERE CompanyId=@C AND AvansId=@I;`);
      await writeAudit({poolPromise,sql,companyId:req.companyId,userId:req.auth.userId,actionCode:'HR_ADVANCE_REJECTED',entityType:'IkAvans',entityId:id,req,transaction:t});
      await t.commit();
      return res.json({success:true,status:'Reddedildi'});
    }

    // Onaylanan avans: 195-Personel Avansları'na borç, Kasa/Banka'ya alacak
    // yazan bir muhasebe fişi kesilir - avans artık kasa/banka hareketlerinde
    // ve muhasebede görünür (bkz. ALYA-ERP-VERI-AKISI-HARITASI.md, bulgu #3).
    await assertPeriodOpen({poolPromise,sql,companyId:req.companyId,operationDate:new Date(),moduleCode:'HR'});
    const avansNo=await nextDocumentNumber({poolPromise,sql,companyId:req.companyId,documentType:'IK_AVANS',transaction:t});
    const journalNo=await nextDocumentNumber({poolPromise,sql,companyId:req.companyId,documentType:'MUHASEBE_FISI',transaction:t});
    const aciklama=`Personel avansı - ${advance.AdSoyad||('Personel #'+advance.PersonelId)}`;

    const fisResult=await new sql.Request(t).input('C',sql.Int,req.companyId).input('JN',sql.NVarChar(80),journalNo).input('I',sql.BigInt,id).input('A',sql.NVarChar(500),aciklama).input('U',sql.Int,req.auth.userId)
      .query(`INSERT dbo.MuhasebeFisleri(CompanyId,FisNo,FisTarihi,FisTipi,KaynakTip,KaynakId,Aciklama,CreatedBy)
              OUTPUT INSERTED.FisId VALUES(@C,@JN,SYSUTCDATETIME(),N'Avans Ödeme',N'IK_AVANS',@I,@A,@U);`);
    const fisId=fisResult.recordset[0].FisId;

    await new sql.Request(t).input('C',sql.Int,req.companyId).input('J',sql.BigInt,fisId).input('T',sql.Decimal(18,2),advance.Tutar).input('H',sql.NVarChar(30),account)
      .query(`INSERT dbo.MuhasebeFisSatirlari(CompanyId,FisId,HesapKodu,Aciklama,Borc,Alacak)VALUES(@C,@J,N'195',N'Personel avansı',@T,0),(@C,@J,@H,N'Avans ödemesi',0,@T);`);

    await new sql.Request(t).input('C',sql.Int,req.companyId).input('I',sql.BigInt,id).input('U',sql.Int,req.auth.userId).input('F',sql.BigInt,fisId).input('CH',sql.NVarChar(30),channel).input('AN',sql.NVarChar(80),avansNo)
      .query(`UPDATE dbo.IkAvanslar SET Durum=N'Onaylandı',ApprovedBy=@U,ApprovedAt=SYSUTCDATETIME(),MuhasebeFisId=@F,OdemeKanali=@CH,AvansNo=@AN WHERE CompanyId=@C AND AvansId=@I;`);

    await writeAudit({poolPromise,sql,companyId:req.companyId,userId:req.auth.userId,actionCode:'HR_ADVANCE_APPROVED',entityType:'IkAvans',entityId:id,after:{avansNo,journalNo,channel,amount:advance.Tutar},req,transaction:t});
    await t.commit();
    res.json({success:true,status:'Onaylandı',avansNo,journalNo,fisId});
  }catch(e){try{await t.rollback();}catch(_){} res.status(e.statusCode||500).json({success:false,error:e.message});}
});
r.post('/performance',requirePermission('erp.write'),async(req,res)=>{try{const person=Number(req.body?.personnelId),period=String(req.body?.period||'').trim(),scores=['targetScore','competencyScore','behaviorScore'].map(k=>Number(req.body?.[k]));if(!Number.isInteger(person)||!period||scores.some(x=>x<0||x>100))return res.status(400).json({success:false,error:'Personel, dönem ve 0-100 arası puanlar zorunludur.'});const p=await poolPromise,q=await p.request().input('C',sql.Int,req.companyId).input('P',sql.Int,person).input('D',sql.NVarChar(30),period).input('H',sql.Decimal(5,2),scores[0]).input('Y',sql.Decimal(5,2),scores[1]).input('B',sql.Decimal(5,2),scores[2]).input('N',sql.NVarChar(1000),req.body?.notes||null).input('U',sql.Int,req.auth.userId).query('INSERT dbo.IkPerformansDegerlendirmeleri(CompanyId,PersonelId,Donem,HedefPuani,YetkinlikPuani,DavranisPuani,Notlar,CreatedBy)OUTPUT INSERTED.DegerlendirmeId,INSERTED.GenelPuan VALUES(@C,@P,@D,@H,@Y,@B,@N,@U)');res.status(201).json({success:true,...q.recordset[0]});}catch(e){fail(res,e)}});
r.post('/trainings',requirePermission('erp.write'),async(req,res)=>{try{const name=String(req.body?.name||'').trim(),start=new Date(req.body?.startDate),end=req.body?.endDate?new Date(req.body.endDate):null,cost=Number(req.body?.cost||0);if(!name||Number.isNaN(start.getTime())||(end&&Number.isNaN(end.getTime()))||cost<0)return res.status(400).json({success:false,error:'Eğitim adı, tarih ve geçerli maliyet zorunludur.'});const p=await poolPromise,q=await p.request().input('C',sql.Int,req.companyId).input('A',sql.NVarChar(200),name).input('T',sql.NVarChar(50),req.body?.type||null).input('B',sql.Date,start).input('E',sql.Date,end).input('G',sql.NVarChar(160),req.body?.trainer||null).input('M',sql.Decimal(18,2),cost).input('N',sql.NVarChar(800),req.body?.description||null).input('U',sql.Int,req.auth.userId).query('INSERT dbo.IkEgitimler(CompanyId,EgitimAdi,EgitimTuru,BaslangicTarihi,BitisTarihi,Egitmen,Maliyet,Aciklama,CreatedBy)OUTPUT INSERTED.EgitimId VALUES(@C,@A,@T,@B,@E,@G,@M,@N,@U)');res.status(201).json({success:true,trainingId:q.recordset[0].EgitimId});}catch(e){fail(res,e)}});
r.post('/trainings/:id/participants',requirePermission('erp.write'),async(req,res)=>{try{const training=Number(req.params.id),person=Number(req.body?.personnelId);if(!Number.isInteger(training)||!Number.isInteger(person))return res.status(400).json({success:false,error:'Eğitim ve personel zorunludur.'});const p=await poolPromise;await p.request().input('C',sql.Int,req.companyId).input('E',sql.BigInt,training).input('P',sql.Int,person).query(`IF NOT EXISTS(SELECT 1 FROM dbo.IkEgitimler WHERE CompanyId=@C AND EgitimId=@E)THROW 52420,N'Eğitim bulunamadı.',1;IF NOT EXISTS(SELECT 1 FROM dbo.IkEgitimKatilimlari WHERE CompanyId=@C AND EgitimId=@E AND PersonelId=@P)INSERT dbo.IkEgitimKatilimlari(CompanyId,EgitimId,PersonelId)VALUES(@C,@E,@P)`);res.status(201).json({success:true});}catch(e){fail(res,e)}});
app.use('/api/hr',r)};
