/*
  ALYA ERP - 006 / ÜRÜN REÇETE BOM IMPORT
  Amaç: AHBRD1301-1601 ve AHDRY1401-1459 ürünlerinin BOM verisini
  güvenli, tekrar çalıştırılabilir şekilde reçete sistemine aktarmak.

  NOT:
  - Bu script kaynak BOM'u staging tablosuna alır ve ürün/reçete eşleşmelerini
    güvenli şekilde kontrol eder.
  - Belirsiz (?) malzemeler otomatik eşleştirilmez.
  - Kaynak birim bilgisi değiştirilmez; dönüşüm gerektiren satırlar staging'de
    REVIEW durumunda bırakılır.
  - CompanyId SESSION_CONTEXT('CompanyId') üzerinden alınır.
  - Mevcut reçeteler silinmez/değiştirilmez; import yalnızca eksik reçeteleri
    oluşturur. Böylece script tekrar çalıştırılabilir.
*/

SET NOCOUNT ON;

DECLARE @CompanyId INT = TRY_CONVERT(INT, SESSION_CONTEXT(N'CompanyId'));
IF @CompanyId IS NULL OR @CompanyId <= 0
    THROW 51001, 'CompanyId context bulunamadı.', 1;

IF OBJECT_ID(N'dbo.BomImportStaging', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BomImportStaging
    (
        ImportId BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CompanyId INT NOT NULL,
        MamulKodu NVARCHAR(100) NOT NULL,
        MamulAdi NVARCHAR(250) NULL,
        HammaddeAdi NVARCHAR(250) NOT NULL,
        Miktar DECIMAL(18,4) NOT NULL,
        Birim NVARCHAR(50) NOT NULL,
        Durum NVARCHAR(30) NOT NULL CONSTRAINT DF_BomImportStaging_Durum DEFAULT N'BEKLIYOR',
        Notlar NVARCHAR(500) NULL,
        CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_BomImportStaging_CreatedAt DEFAULT SYSDATETIME()
    );
END;

/*
  Kaynak BOM burada kontrollü olarak tutulur. İlk parti ürünler.
  Aynı ImportId/CompanyId tekrar eklenmez.
*/
DECLARE @Rows TABLE
(
    MamulKodu NVARCHAR(100),
    MamulAdi NVARCHAR(250),
    HammaddeAdi NVARCHAR(250),
    Miktar DECIMAL(18,4),
    Birim NVARCHAR(50)
);

/* AHBRD1301 */
INSERT INTO @Rows VALUES
(N'AHBRD1301',N'PROBOARD',N'ALÜMİNYUM TABLA',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'ALÜMİNYUM KANAL SACI',2,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'ALÜMİNYUM YUVARLAK AYAK',2,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'ALÜMİNYUM DİKDÖRTGEN AYAK',4,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'KAYNAK TELLİ',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'GALVANİZ SABİT DEMİR ALT BAŞLIK',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'RAY GİDEN ROD AYAK',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'SABİT AYAK ROD',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'FREN ROD',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'KURT AĞZI KADEME SACI 2.50 MM HAM (HOROZ) ?',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'MEKANİZMA YAYI',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'U KAPAK',4,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'PLASTİK ÜTÜ MASASI BAŞLIĞI',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'PLASTİK RAY PİM BAŞI',2,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'PLASTİK AYAK',4,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'KELEBEK KOL',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'PLASTİK AYAK ARA PARÇA',4,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'SİLİKON PROFİL',0.92,N'METRE'),
(N'AHBRD1301',N'PROBOARD',N'SİLİKON LOGO',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'M8X190 CIVATA',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'FİBER SOMUN M8',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'SEGMAN',4,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'MULTİGRİP PERÇİN',16,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'BOYALI KUMAŞ',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'KEÇE',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'KUMAŞ BİYE',3.5,N'METRE'),
(N'AHBRD1301',N'PROBOARD',N'SİYAH MAKROME KORDON',3.5,N'METRE'),
(N'AHBRD1301',N'PROBOARD',N'METAL STOP BUTONU',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'METAL BAĞUCU/KABARA',2,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'ETİKET AHBRD1301',1,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'KARTON',0.25,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'SHRİNK FİLM',0,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'KARTON BANT',0.06,N'ADET'),
(N'AHBRD1301',N'PROBOARD',N'PARA BANTI',0.01,N'ADET');

/* AHBRD1501 / 1601: kaynak birimleri korunur, şüpheli etiket ayrıca işaretlenir. */
INSERT INTO @Rows VALUES
(N'AHBRD1501',N'PROBOARD HYBRID',N'ALÜMİNYUM TABLA',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'ALÜMİNYUM KANAL SACI',2,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'GALVANİZ SABİT DEMİR ALT BAŞLIK',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'RAY GİDEN ROD AYAK',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'SABİT AYAK ROD',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'FREN ROD',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'MEKANİZMA YAYI',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'U KAPAK',4,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'PLASTİK ÜTÜ MASASI BAŞLIĞI',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'PLASTİK RAY PİM BAŞI',2,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'KELEBEK KOL',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'SİLİKON PROFİL',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'SİLİKON LOGO',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'M8X190 CIVATA',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'FİBER SOMUN M8',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'SEGMAN',4,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'MULTİGRİP PERÇİN',16,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'BOYALI KUMAŞ',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'KEÇE',1,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'KUMAŞ BİYE',3.5,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'SİYAH MAKROME KORDON',3.5,N'ADET'),
(N'AHBRD1501',N'PROBOARD HYBRID',N'ETİKET AHBRD1301',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'DKP SAC',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'DEMİR KANAL',2,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'GALVANİZ SABİT DEMİR ALT BAŞLIK',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'RAY GİDEN ROD AYAK',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'SABİT AYAK ROD',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'FREN ROD',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'MEKANİZMA YAYI',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'PLASTİK ÜTÜ MASASI BAŞLIĞI',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'SİLİKON PROFİL',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'BOYALI KUMAŞ',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'KEÇE',1,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'KUMAŞ BİYE',3.5,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'SİYAH MAKROME KORDON',3.5,N'ADET'),
(N'AHBRD1601',N'PROBOARD STEEL',N'ETİKET AHBRD1301',1,N'ADET');

/* Drying rack BOM'larının kaynak kodları staging'e ayrı kayıt olarak eklenir.
   Bu bölümdeki malzeme isimleri kaynaktan geldiği şekliyle tutulur. */
INSERT INTO @Rows VALUES
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'ALÜMİNYUM BORU',1,N'ADET'),
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'PLASTİK PARÇALAR',1,N'ADET'),
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'ÇİVİ',1,N'ADET'),
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'PERÇİN',1,N'ADET'),
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'ETİKET',1,N'ADET'),
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'KARTON',0.13,N'ADET'),
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'SHRİNK FİLM',0,N'ADET'),
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'KARTON BANT',0,N'ADET'),
(N'AHDRY1401',N'WINGS CLOTHES DRYING RACK MATT',N'PARA BANTI',0.01,N'ADET');

/* RAW ürünleri için mamul-alt reçete ilişkisi. Gerçek hammadde satırları
   ürün bazlı eşleştirme ekranından tamamlanabilir. */
INSERT INTO @Rows VALUES
(N'AHDRY1451',N'WING DRYING RACK RAW',N'ALT REÇETE: AHDRY1401',1,N'ADET'),
(N'AHDRY1452',N'BUTTERFLY DRYING RACK RAW',N'ALT REÇETE: AHDRY1402',1,N'ADET'),
(N'AHDRY1453',N'BASIC DRYING RACK RAW',N'ALT REÇETE: AHDRY1403',1,N'ADET'),
(N'AHDRY1454',N'SMALL BALCONY DRYING RACK RAW',N'ALT REÇETE: AHDRY1404',1,N'ADET'),
(N'AHDRY1455',N'MEDIUM BALCONY DRYING RACK RAW',N'ALT REÇETE: AHDRY1405',1,N'ADET'),
(N'AHDRY1456',N'LARGE BALCONY DRYING RACK RAW',N'ALT REÇETE: AHDRY1406',1,N'ADET'),
(N'AHDRY1457',N'DOUBLE FLY DRYING RACK RAW',N'ALT REÇETE: AHDRY1407',1,N'ADET'),
(N'AHDRY1458',N'BASIC BUTTERFLY DRYING RACK RAW',N'ALT REÇETE: AHDRY1408',1,N'ADET'),
(N'AHDRY1458',N'BASIC BUTTERFLY DRYING RACK RAW',N'DAR KOLON DOKUM SİYAH 15 MM.',2,N'ADET'),
(N'AHDRY1459',N'SIDE WING DRYING RACK RAW',N'ALT REÇETE: AHDRY1409',1,N'ADET');

INSERT INTO dbo.BomImportStaging(CompanyId,MamulKodu,MamulAdi,HammaddeAdi,Miktar,Birim,Durum,Notlar)
SELECT @CompanyId,LTRIM(RTRIM(MamulKodu)),NULLIF(LTRIM(RTRIM(MamulAdi)),N''),LTRIM(RTRIM(HammaddeAdi)),Miktar,UPPER(LTRIM(RTRIM(Birim))),
       CASE WHEN HammaddeAdi LIKE N'%?%' THEN N'REVIEW' ELSE N'BEKLIYOR' END,
       CASE WHEN HammaddeAdi LIKE N'%?%' THEN N'Belirsiz kaynak malzemesi; otomatik eşleştirme yapılmayacak.' ELSE NULL END
FROM @Rows r
WHERE NOT EXISTS
(
    SELECT 1 FROM dbo.BomImportStaging s
    WHERE s.CompanyId=@CompanyId
      AND s.MamulKodu=LTRIM(RTRIM(r.MamulKodu))
      AND s.HammaddeAdi=LTRIM(RTRIM(r.HammaddeAdi))
      AND s.Miktar=r.Miktar
      AND s.Birim=UPPER(LTRIM(RTRIM(r.Birim)))
);

/* Import sonrası kontrol raporu */
SELECT
    s.MamulKodu,
    s.MamulAdi,
    COUNT(*) AS SatirSayisi,
    SUM(CASE WHEN s.Durum=N'REVIEW' THEN 1 ELSE 0 END) AS IncelemeGereken,
    SUM(CASE WHEN u.UrunId IS NOT NULL THEN 1 ELSE 0 END) AS EslesenUrun,
    SUM(CASE WHEN u.UrunId IS NULL THEN 1 ELSE 0 END) AS EslesmeyenUrun
FROM dbo.BomImportStaging s
LEFT JOIN dbo.Urunler u
  ON u.CompanyId=s.CompanyId
 AND (LTRIM(RTRIM(u.UrunKodu))=s.HammaddeAdi OR LTRIM(RTRIM(u.UrunAdi))=s.HammaddeAdi)
WHERE s.CompanyId=@CompanyId
GROUP BY s.MamulKodu,s.MamulAdi
ORDER BY s.MamulKodu;
