/* ALYA ERP 015 - Fatura > Cari > Tahsilat > Muhasebe. Veri silmez. */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.Faturalar',N'U') IS NULL OR OBJECT_ID(N'dbo.FaturaDetay',N'U') IS NULL THROW 51501,N'Fatura tabloları bulunamadı.',1;
IF OBJECT_ID(N'dbo.BelgeBaglantilari',N'U') IS NULL THROW 51502,N'Önce Faz 2 migrationını çalıştırın.',1;
IF OBJECT_ID(N'dbo.MuhasebeHesaplari',N'U') IS NULL CREATE TABLE dbo.MuhasebeHesaplari(HesapId INT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,HesapKodu NVARCHAR(30) NOT NULL,HesapAdi NVARCHAR(200) NOT NULL,HesapTipi NVARCHAR(30) NOT NULL,IsActive BIT NOT NULL DEFAULT 1,CONSTRAINT UQ_MuhasebeHesaplari UNIQUE(CompanyId,HesapKodu),CONSTRAINT FK_MuhasebeHesaplari_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.MuhasebeFisleri',N'U') IS NULL CREATE TABLE dbo.MuhasebeFisleri(FisId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FisNo NVARCHAR(80) NOT NULL,FisTarihi DATETIME2(3) NOT NULL,FisTipi NVARCHAR(30) NOT NULL,KaynakTip NVARCHAR(40) NOT NULL,KaynakId BIGINT NOT NULL,Aciklama NVARCHAR(500),Durum NVARCHAR(20) NOT NULL DEFAULT N'Kesinleşti',CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_MuhasebeFisleri_Kaynak UNIQUE(CompanyId,KaynakTip,KaynakId),CONSTRAINT FK_MuhasebeFisleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.MuhasebeFisSatirlari',N'U') IS NULL CREATE TABLE dbo.MuhasebeFisSatirlari(SatirId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FisId BIGINT NOT NULL,HesapKodu NVARCHAR(30) NOT NULL,Aciklama NVARCHAR(500),Borc DECIMAL(18,2) NOT NULL DEFAULT 0,Alacak DECIMAL(18,2) NOT NULL DEFAULT 0,CariKodu NVARCHAR(100),CONSTRAINT CK_MuhasebeFisSatirlari CHECK((Borc>0 AND Alacak=0)OR(Alacak>0 AND Borc=0)),CONSTRAINT FK_MuhasebeFisSatirlari_Fis FOREIGN KEY(FisId) REFERENCES dbo.MuhasebeFisleri(FisId),CONSTRAINT FK_MuhasebeFisSatirlari_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));CREATE INDEX IX_MuhasebeFisSatirlari_Fis ON dbo.MuhasebeFisSatirlari(CompanyId,FisId);
IF OBJECT_ID(N'dbo.CariDefterHareketleri',N'U') IS NULL CREATE TABLE dbo.CariDefterHareketleri(HareketId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,CariKodu NVARCHAR(100) NOT NULL,HareketTarihi DATETIME2(3) NOT NULL,BelgeTipi NVARCHAR(40) NOT NULL,BelgeId BIGINT NOT NULL,BelgeNo NVARCHAR(100),Borc DECIMAL(18,2) NOT NULL DEFAULT 0,Alacak DECIMAL(18,2) NOT NULL DEFAULT 0,Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_CariDefter_Kaynak UNIQUE(CompanyId,CariKodu,BelgeTipi,BelgeId),CONSTRAINT CK_CariDefter_Tutar CHECK((Borc>0 AND Alacak=0)OR(Alacak>0 AND Borc=0)),CONSTRAINT FK_CariDefter_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));CREATE INDEX IX_CariDefter_Cari ON dbo.CariDefterHareketleri(CompanyId,CariKodu,HareketTarihi);
IF OBJECT_ID(N'dbo.Tahsilatlar',N'U') IS NULL CREATE TABLE dbo.Tahsilatlar(TahsilatId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,TahsilatNo NVARCHAR(80) NOT NULL,FaturaId INT NOT NULL,CariKodu NVARCHAR(100) NOT NULL,TahsilatTarihi DATETIME2(3) NOT NULL,Tutar DECIMAL(18,2) NOT NULL,OdemeKanali NVARCHAR(30) NOT NULL,HesapKodu NVARCHAR(30) NOT NULL,Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_Tahsilatlar_No UNIQUE(CompanyId,TahsilatNo),CONSTRAINT CK_Tahsilatlar_Tutar CHECK(Tutar>0),CONSTRAINT FK_Tahsilatlar_Fatura FOREIGN KEY(FaturaId) REFERENCES dbo.Faturalar(FaturaId),CONSTRAINT FK_Tahsilatlar_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF COL_LENGTH(N'dbo.Faturalar',N'MuhasebeDurumu') IS NULL ALTER TABLE dbo.Faturalar ADD MuhasebeDurumu NVARCHAR(20) NOT NULL CONSTRAINT DF_Faturalar_MuhasebeDurumu DEFAULT N'Bekliyor' WITH VALUES;
IF COL_LENGTH(N'dbo.Faturalar',N'TahsilEdilenTutar') IS NULL ALTER TABLE dbo.Faturalar ADD TahsilEdilenTutar DECIMAL(18,2) NOT NULL CONSTRAINT DF_Faturalar_Tahsil DEFAULT 0 WITH VALUES;
INSERT dbo.MuhasebeHesaplari(CompanyId,HesapKodu,HesapAdi,HesapTipi) SELECT s.CompanyId,x.Kod,x.Ad,x.Tip FROM dbo.Sirketler s CROSS JOIN(VALUES(N'100',N'Kasa',N'Varlık'),(N'102',N'Bankalar',N'Varlık'),(N'120',N'Alıcılar',N'Varlık'),(N'600',N'Yurt İçi Satışlar',N'Gelir'),(N'391',N'Hesaplanan KDV',N'Yükümlülük'))x(Kod,Ad,Tip) WHERE NOT EXISTS(SELECT 1 FROM dbo.MuhasebeHesaplari h WHERE h.CompanyId=s.CompanyId AND h.HesapKodu=x.Kod);
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'FATURA',N'FAT-'),(N'MUHASEBE_FISI',N'MF-'),(N'TAHSILAT',N'THS-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'015 finans ve muhasebe zinciri tamamlandı.' Result;
