/* ALYA ERP 016 - Üretim Talebi > MRP > Malzeme İhtiyacı > Satın Alma Talebi */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.Receteler',N'U') IS NULL OR OBJECT_ID(N'dbo.ReceteDetay',N'U') IS NULL THROW 51601,N'Reçete tabloları bulunamadı.',1;
IF OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL THROW 51602,N'Faz 1 stok çekirdeği kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.UretimTalepleri',N'U') IS NULL CREATE TABLE dbo.UretimTalepleri(TalepId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,TalepNo NVARCHAR(80) NOT NULL,MamulUrunId INT NOT NULL,ReceteId INT NOT NULL,KaynakTip NVARCHAR(40),KaynakId BIGINT,TalepMiktari DECIMAL(18,4) NOT NULL,IhtiyacTarihi DATE NOT NULL,Oncelik NVARCHAR(20) NOT NULL DEFAULT N'Normal',Durum NVARCHAR(30) NOT NULL DEFAULT N'Yeni',Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_UretimTalepleri_No UNIQUE(CompanyId,TalepNo),CONSTRAINT CK_UretimTalepleri_Miktar CHECK(TalepMiktari>0),CONSTRAINT FK_UretimTalepleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_UretimTalepleri_Recete FOREIGN KEY(ReceteId) REFERENCES dbo.Receteler(ReceteId));
IF OBJECT_ID(N'dbo.MRPPlanlari',N'U') IS NULL CREATE TABLE dbo.MRPPlanlari(PlanId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,PlanNo NVARCHAR(80) NOT NULL,TalepId BIGINT NOT NULL,PlanTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),PlanlananMiktar DECIMAL(18,4) NOT NULL,Durum NVARCHAR(30) NOT NULL DEFAULT N'Hesaplandı',ToplamKalem INT NOT NULL DEFAULT 0,EksikKalem INT NOT NULL DEFAULT 0,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_MRPPlanlari_No UNIQUE(CompanyId,PlanNo),CONSTRAINT UQ_MRPPlanlari_Talep UNIQUE(CompanyId,TalepId),CONSTRAINT FK_MRPPlanlari_Talep FOREIGN KEY(TalepId) REFERENCES dbo.UretimTalepleri(TalepId),CONSTRAINT FK_MRPPlanlari_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.MRPMalzemeIhtiyaclari',N'U') IS NULL CREATE TABLE dbo.MRPMalzemeIhtiyaclari(IhtiyacId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,PlanId BIGINT NOT NULL,UrunId INT NOT NULL,UrunAdi NVARCHAR(250),Birim NVARCHAR(30),DepoAdi NVARCHAR(100),BrutIhtiyac DECIMAL(18,4) NOT NULL,MevcutStok DECIMAL(18,4) NOT NULL DEFAULT 0,RezerveStok DECIMAL(18,4) NOT NULL DEFAULT 0,NetIhtiyac DECIMAL(18,4) NOT NULL DEFAULT 0,Durum NVARCHAR(30) NOT NULL,CONSTRAINT UQ_MRPMalzemeIhtiyaclari UNIQUE(CompanyId,PlanId,UrunId,DepoAdi),CONSTRAINT FK_MRPMalzemeIhtiyaclari_Plan FOREIGN KEY(PlanId) REFERENCES dbo.MRPPlanlari(PlanId),CONSTRAINT FK_MRPMalzemeIhtiyaclari_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));CREATE INDEX IX_MRPMalzemeIhtiyaclari_Eksik ON dbo.MRPMalzemeIhtiyaclari(CompanyId,Durum,PlanId) INCLUDE(UrunId,NetIhtiyac);
IF OBJECT_ID(N'dbo.SatinAlmaTalepleri',N'U') IS NULL CREATE TABLE dbo.SatinAlmaTalepleri(SatinAlmaTalepId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,TalepNo NVARCHAR(80) NOT NULL,MRPPlanId BIGINT NOT NULL,TalepTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),IhtiyacTarihi DATE NOT NULL,Durum NVARCHAR(30) NOT NULL DEFAULT N'Onay Bekliyor',Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_SatinAlmaTalepleri_No UNIQUE(CompanyId,TalepNo),CONSTRAINT UQ_SatinAlmaTalepleri_MRP UNIQUE(CompanyId,MRPPlanId),CONSTRAINT FK_SatinAlmaTalepleri_MRP FOREIGN KEY(MRPPlanId) REFERENCES dbo.MRPPlanlari(PlanId),CONSTRAINT FK_SatinAlmaTalepleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.SatinAlmaTalepKalemleri',N'U') IS NULL CREATE TABLE dbo.SatinAlmaTalepKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,SatinAlmaTalepId BIGINT NOT NULL,MRPIhtiyacId BIGINT NOT NULL,UrunId INT NOT NULL,UrunAdi NVARCHAR(250),Miktar DECIMAL(18,4) NOT NULL,Birim NVARCHAR(30),HedefDepo NVARCHAR(100),Durum NVARCHAR(30) NOT NULL DEFAULT N'Açık',CONSTRAINT CK_SatinAlmaTalepKalemleri_Miktar CHECK(Miktar>0),CONSTRAINT FK_SatinAlmaTalepKalemleri_Talep FOREIGN KEY(SatinAlmaTalepId) REFERENCES dbo.SatinAlmaTalepleri(SatinAlmaTalepId),CONSTRAINT FK_SatinAlmaTalepKalemleri_Ihtiyac FOREIGN KEY(MRPIhtiyacId) REFERENCES dbo.MRPMalzemeIhtiyaclari(IhtiyacId),CONSTRAINT FK_SatinAlmaTalepKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'URETIM_TALEBI',N'UT-'),(N'MRP_PLANI',N'MRP-'),(N'SATINALMA_TALEBI',N'SAT-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
IF OBJECT_ID(N'dbo.BelgeBaglantilari',N'U') IS NOT NULL BEGIN INSERT dbo.BelgeBaglantilari(CompanyId,KaynakTip,KaynakId,HedefTip,HedefId) SELECT CompanyId,KaynakTip,KaynakId,N'URETIM_TALEBI',TalepId FROM dbo.UretimTalepleri WHERE KaynakTip IS NOT NULL AND KaynakId IS NOT NULL AND NOT EXISTS(SELECT 1 FROM dbo.BelgeBaglantilari b WHERE b.CompanyId=UretimTalepleri.CompanyId AND b.KaynakTip=UretimTalepleri.KaynakTip AND b.KaynakId=UretimTalepleri.KaynakId AND b.HedefTip=N'URETIM_TALEBI' AND b.HedefId=UretimTalepleri.TalepId);END;
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'016 MRP ve satın alma talep zinciri tamamlandı.' Result;
