/* ALYA ERP 017 - Satın Alma Talebi > Teklif > Sipariş > Mal Kabul > Stok */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.SatinAlmaTalepleri',N'U') IS NULL OR OBJECT_ID(N'dbo.SatinAlmaTalepKalemleri',N'U') IS NULL THROW 51701,N'Önce Faz 4 kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL THROW 51702,N'Faz 1 stok çekirdeği bulunamadı.',1;
IF OBJECT_ID(N'dbo.TedarikciTeklifleri',N'U') IS NULL CREATE TABLE dbo.TedarikciTeklifleri(TeklifId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,TeklifNo NVARCHAR(80) NOT NULL,SatinAlmaTalepId BIGINT NOT NULL,TedarikciKodu NVARCHAR(100) NOT NULL,TedarikciAdi NVARCHAR(250) NOT NULL,TeklifTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),GecerlilikTarihi DATE,TeslimSuresiGun INT NOT NULL DEFAULT 0,AraToplam DECIMAL(18,2) NOT NULL DEFAULT 0,KdvToplam DECIMAL(18,2) NOT NULL DEFAULT 0,GenelToplam DECIMAL(18,2) NOT NULL DEFAULT 0,ParaBirimi NVARCHAR(10) NOT NULL DEFAULT N'TRY',Durum NVARCHAR(30) NOT NULL DEFAULT N'Bekliyor',CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_TedarikciTeklifleri_No UNIQUE(CompanyId,TeklifNo),CONSTRAINT FK_TedarikciTeklifleri_Talep FOREIGN KEY(SatinAlmaTalepId) REFERENCES dbo.SatinAlmaTalepleri(SatinAlmaTalepId),CONSTRAINT FK_TedarikciTeklifleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.TedarikciTeklifKalemleri',N'U') IS NULL CREATE TABLE dbo.TedarikciTeklifKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,TeklifId BIGINT NOT NULL,SatinAlmaTalepKalemId BIGINT NOT NULL,UrunId INT NOT NULL,UrunAdi NVARCHAR(250),Miktar DECIMAL(18,4) NOT NULL,Birim NVARCHAR(30),BirimFiyat DECIMAL(18,4) NOT NULL,KdvOrani DECIMAL(9,2) NOT NULL DEFAULT 20,SatirToplam DECIMAL(18,2) NOT NULL,CONSTRAINT UQ_TedarikciTeklifKalemleri UNIQUE(CompanyId,TeklifId,SatinAlmaTalepKalemId),CONSTRAINT CK_TedarikciTeklifKalemleri_Miktar CHECK(Miktar>0),CONSTRAINT FK_TedarikciTeklifKalemleri_Teklif FOREIGN KEY(TeklifId) REFERENCES dbo.TedarikciTeklifleri(TeklifId),CONSTRAINT FK_TedarikciTeklifKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.SatinAlmaSiparisleriV2',N'U') IS NULL CREATE TABLE dbo.SatinAlmaSiparisleriV2(SiparisId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,SiparisNo NVARCHAR(80) NOT NULL,TeklifId BIGINT NOT NULL,SatinAlmaTalepId BIGINT NOT NULL,TedarikciKodu NVARCHAR(100) NOT NULL,TedarikciAdi NVARCHAR(250) NOT NULL,SiparisTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),BeklenenTeslimTarihi DATE,ParaBirimi NVARCHAR(10) NOT NULL,AraToplam DECIMAL(18,2) NOT NULL,KdvToplam DECIMAL(18,2) NOT NULL,GenelToplam DECIMAL(18,2) NOT NULL,Durum NVARCHAR(30) NOT NULL DEFAULT N'Açık',CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_SatinAlmaSiparisleriV2_No UNIQUE(CompanyId,SiparisNo),CONSTRAINT UQ_SatinAlmaSiparisleriV2_Teklif UNIQUE(CompanyId,TeklifId),CONSTRAINT FK_SatinAlmaSiparisleriV2_Teklif FOREIGN KEY(TeklifId) REFERENCES dbo.TedarikciTeklifleri(TeklifId),CONSTRAINT FK_SatinAlmaSiparisleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.SatinAlmaSiparisKalemleriV2',N'U') IS NULL CREATE TABLE dbo.SatinAlmaSiparisKalemleriV2(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,SiparisId BIGINT NOT NULL,SatinAlmaTalepKalemId BIGINT NOT NULL,UrunId INT NOT NULL,UrunAdi NVARCHAR(250),SiparisMiktari DECIMAL(18,4) NOT NULL,TeslimAlinanMiktar DECIMAL(18,4) NOT NULL DEFAULT 0,Birim NVARCHAR(30),BirimFiyat DECIMAL(18,4) NOT NULL,KdvOrani DECIMAL(9,2) NOT NULL,SatirToplam DECIMAL(18,2) NOT NULL,HedefDepo NVARCHAR(100),Durum NVARCHAR(30) NOT NULL DEFAULT N'Açık',CONSTRAINT CK_SatinAlmaSiparisKalemleriV2_Miktar CHECK(SiparisMiktari>0 AND TeslimAlinanMiktar>=0 AND TeslimAlinanMiktar<=SiparisMiktari),CONSTRAINT FK_SatinAlmaSiparisKalemleriV2_Siparis FOREIGN KEY(SiparisId) REFERENCES dbo.SatinAlmaSiparisleriV2(SiparisId),CONSTRAINT FK_SatinAlmaSiparisKalemleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));CREATE INDEX IX_SatinAlmaSiparisKalemleriV2_Acik ON dbo.SatinAlmaSiparisKalemleriV2(CompanyId,SiparisId,Durum) INCLUDE(UrunId,SiparisMiktari,TeslimAlinanMiktar);
IF OBJECT_ID(N'dbo.MalKabulFisleri',N'U') IS NULL CREATE TABLE dbo.MalKabulFisleri(MalKabulId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,MalKabulNo NVARCHAR(80) NOT NULL,SiparisId BIGINT NOT NULL,DepoId INT NOT NULL,LokasyonId INT NOT NULL,KabulTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),IrsaliyeNo NVARCHAR(100),KaliteDurumu NVARCHAR(30) NOT NULL DEFAULT N'Onaylı',Durum NVARCHAR(30) NOT NULL DEFAULT N'Tamamlandı',IslemAnahtari NVARCHAR(100) NOT NULL,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_MalKabulFisleri_No UNIQUE(CompanyId,MalKabulNo),CONSTRAINT UQ_MalKabulFisleri_Islem UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT FK_MalKabulFisleri_Siparis FOREIGN KEY(SiparisId) REFERENCES dbo.SatinAlmaSiparisleriV2(SiparisId),CONSTRAINT FK_MalKabulFisleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.MalKabulKalemleri',N'U') IS NULL CREATE TABLE dbo.MalKabulKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,MalKabulId BIGINT NOT NULL,SiparisKalemId BIGINT NOT NULL,UrunId INT NOT NULL,Miktar DECIMAL(18,4) NOT NULL,Birim NVARCHAR(30),BirimFiyat DECIMAL(18,4) NOT NULL,LotNo NVARCHAR(100) NOT NULL DEFAULT N'',SeriNo NVARCHAR(100) NOT NULL DEFAULT N'',KaliteDurumu NVARCHAR(30) NOT NULL,CONSTRAINT CK_MalKabulKalemleri_Miktar CHECK(Miktar>0),CONSTRAINT FK_MalKabulKalemleri_Fis FOREIGN KEY(MalKabulId) REFERENCES dbo.MalKabulFisleri(MalKabulId),CONSTRAINT FK_MalKabulKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF COL_LENGTH(N'dbo.SatinAlmaTalepKalemleri',N'SipariseDonusenMiktar') IS NULL ALTER TABLE dbo.SatinAlmaTalepKalemleri ADD SipariseDonusenMiktar DECIMAL(18,4) NOT NULL CONSTRAINT DF_SATK_SiparisMiktari DEFAULT 0 WITH VALUES;
IF COL_LENGTH(N'dbo.SatinAlmaTalepKalemleri',N'TeslimAlinanMiktar') IS NULL ALTER TABLE dbo.SatinAlmaTalepKalemleri ADD TeslimAlinanMiktar DECIMAL(18,4) NOT NULL CONSTRAINT DF_SATK_TeslimMiktari DEFAULT 0 WITH VALUES;
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'TEDARIKCI_TEKLIFI',N'TTK-'),(N'SATINALMA_SIPARISI',N'SAS-'),(N'MAL_KABUL',N'MK-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'017 satın alma ve mal kabul zinciri tamamlandı.' Result;
