/* ALYA ERP 018 - Mal Kabul > Kalite Kontrol > Serbest Bırakma / Tedarikçiye İade */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.MalKabulFisleri',N'U') IS NULL OR OBJECT_ID(N'dbo.MalKabulKalemleri',N'U') IS NULL THROW 51801,N'Önce Faz 5 kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL THROW 51802,N'Faz 1 stok çekirdeği bulunamadı.',1;
IF OBJECT_ID(N'dbo.KaliteKontrolFisleri',N'U') IS NULL CREATE TABLE dbo.KaliteKontrolFisleri(KaliteKontrolId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KontrolNo NVARCHAR(80) NOT NULL,MalKabulId BIGINT NOT NULL,KontrolTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),KontrolTipi NVARCHAR(30) NOT NULL DEFAULT N'Girdi Kontrol',Durum NVARCHAR(30) NOT NULL DEFAULT N'Kontrol Bekliyor',Karar NVARCHAR(30),Aciklama NVARCHAR(500),KontrolEdenId INT,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_KaliteKontrolFisleri_No UNIQUE(CompanyId,KontrolNo),CONSTRAINT UQ_KaliteKontrolFisleri_MalKabul UNIQUE(CompanyId,MalKabulId),CONSTRAINT FK_KaliteKontrolFisleri_MalKabul FOREIGN KEY(MalKabulId) REFERENCES dbo.MalKabulFisleri(MalKabulId),CONSTRAINT FK_KaliteKontrolFisleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.KaliteKontrolKalemleri',N'U') IS NULL CREATE TABLE dbo.KaliteKontrolKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KaliteKontrolId BIGINT NOT NULL,MalKabulKalemId BIGINT NOT NULL,UrunId INT NOT NULL,KontrolMiktari DECIMAL(18,4) NOT NULL,NumuneMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,KabulMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,RedMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,IadeMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,Karar NVARCHAR(30) NOT NULL DEFAULT N'Bekliyor',RedNedeni NVARCHAR(500),Notlar NVARCHAR(1000),CONSTRAINT UQ_KaliteKontrolKalemleri UNIQUE(CompanyId,KaliteKontrolId,MalKabulKalemId),CONSTRAINT CK_KaliteKontrolKalemleri_Miktar CHECK(KontrolMiktari>0 AND NumuneMiktari>=0 AND KabulMiktari>=0 AND RedMiktari>=0 AND IadeMiktari>=0 AND KabulMiktari+RedMiktari<=KontrolMiktari AND IadeMiktari<=RedMiktari),CONSTRAINT FK_KaliteKontrolKalemleri_Fis FOREIGN KEY(KaliteKontrolId) REFERENCES dbo.KaliteKontrolFisleri(KaliteKontrolId),CONSTRAINT FK_KaliteKontrolKalemleri_MalKabul FOREIGN KEY(MalKabulKalemId) REFERENCES dbo.MalKabulKalemleri(KalemId),CONSTRAINT FK_KaliteKontrolKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.TedarikciIadeFisleri',N'U') IS NULL CREATE TABLE dbo.TedarikciIadeFisleri(IadeId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,IadeNo NVARCHAR(80) NOT NULL,KaliteKontrolId BIGINT NOT NULL,MalKabulId BIGINT NOT NULL,SiparisId BIGINT NOT NULL,TedarikciKodu NVARCHAR(100),TedarikciAdi NVARCHAR(250),IadeTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),IrsaliyeNo NVARCHAR(100),Durum NVARCHAR(30) NOT NULL DEFAULT N'Tamamlandı',IslemAnahtari NVARCHAR(100) NOT NULL,Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_TedarikciIadeFisleri_No UNIQUE(CompanyId,IadeNo),CONSTRAINT UQ_TedarikciIadeFisleri_Kontrol UNIQUE(CompanyId,KaliteKontrolId),CONSTRAINT UQ_TedarikciIadeFisleri_Islem UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT FK_TedarikciIadeFisleri_Kontrol FOREIGN KEY(KaliteKontrolId) REFERENCES dbo.KaliteKontrolFisleri(KaliteKontrolId),CONSTRAINT FK_TedarikciIadeFisleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.TedarikciIadeKalemleri',N'U') IS NULL CREATE TABLE dbo.TedarikciIadeKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,IadeId BIGINT NOT NULL,KaliteKontrolKalemId BIGINT NOT NULL,UrunId INT NOT NULL,DepoId INT NOT NULL,LokasyonId INT NOT NULL,Miktar DECIMAL(18,4) NOT NULL,Birim NVARCHAR(30),LotNo NVARCHAR(100) NOT NULL DEFAULT N'',SeriNo NVARCHAR(100) NOT NULL DEFAULT N'',RedNedeni NVARCHAR(500),CONSTRAINT CK_TedarikciIadeKalemleri_Miktar CHECK(Miktar>0),CONSTRAINT FK_TedarikciIadeKalemleri_Iade FOREIGN KEY(IadeId) REFERENCES dbo.TedarikciIadeFisleri(IadeId),CONSTRAINT FK_TedarikciIadeKalemleri_Kontrol FOREIGN KEY(KaliteKontrolKalemId) REFERENCES dbo.KaliteKontrolKalemleri(KalemId),CONSTRAINT FK_TedarikciIadeKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF COL_LENGTH(N'dbo.MalKabulFisleri',N'KaliteKontrolId') IS NULL ALTER TABLE dbo.MalKabulFisleri ADD KaliteKontrolId BIGINT NULL;
IF COL_LENGTH(N'dbo.MalKabulKalemleri',N'KabulMiktari') IS NULL ALTER TABLE dbo.MalKabulKalemleri ADD KabulMiktari DECIMAL(18,4) NOT NULL CONSTRAINT DF_MKK_Kabul DEFAULT 0 WITH VALUES;
IF COL_LENGTH(N'dbo.MalKabulKalemleri',N'RedMiktari') IS NULL ALTER TABLE dbo.MalKabulKalemleri ADD RedMiktari DECIMAL(18,4) NOT NULL CONSTRAINT DF_MKK_Red DEFAULT 0 WITH VALUES;
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'KALITE_KONTROL',N'KK-'),(N'TEDARIKCI_IADE',N'TI-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'018 kalite kontrol ve tedarikçi iade zinciri tamamlandı.' Result;
