/* ALYA ERP 019 - MRP > Üretim Emri > Rezervasyon > Sarf > Mamul Girişi */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.MRPPlanlari',N'U') IS NULL OR OBJECT_ID(N'dbo.MRPMalzemeIhtiyaclari',N'U') IS NULL THROW 51901,N'Önce Faz 4 kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL THROW 51902,N'Faz 1 stok çekirdeği bulunamadı.',1;
IF OBJECT_ID(N'dbo.UretimEmirleriV2',N'U') IS NULL CREATE TABLE dbo.UretimEmirleriV2(EmirId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,EmirNo NVARCHAR(80) NOT NULL,MRPPlanId BIGINT NOT NULL,UretimTalepId BIGINT NOT NULL,ReceteId INT NOT NULL,MamulUrunId INT NOT NULL,PlanlananMiktar DECIMAL(18,4) NOT NULL,UretilenMiktar DECIMAL(18,4) NOT NULL DEFAULT 0,FireMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,HedefDepoId INT NOT NULL,HedefLokasyonId INT NOT NULL,PlanlananBaslangic DATETIME2(3),PlanlananBitis DATETIME2(3),GercekBaslangic DATETIME2(3),GercekBitis DATETIME2(3),Durum NVARCHAR(30) NOT NULL DEFAULT N'Serbest',Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_UretimEmirleriV2_No UNIQUE(CompanyId,EmirNo),CONSTRAINT UQ_UretimEmirleriV2_MRP UNIQUE(CompanyId,MRPPlanId),CONSTRAINT CK_UretimEmirleriV2_Miktar CHECK(PlanlananMiktar>0 AND UretilenMiktar>=0 AND FireMiktari>=0),CONSTRAINT FK_UretimEmirleriV2_MRP FOREIGN KEY(MRPPlanId) REFERENCES dbo.MRPPlanlari(PlanId),CONSTRAINT FK_UretimEmirleriV2_Talep FOREIGN KEY(UretimTalepId) REFERENCES dbo.UretimTalepleri(TalepId),CONSTRAINT FK_UretimEmirleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.UretimEmriMalzemeleri',N'U') IS NULL CREATE TABLE dbo.UretimEmriMalzemeleri(MalzemeId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,EmirId BIGINT NOT NULL,MRPIhtiyacId BIGINT NOT NULL,UrunId INT NOT NULL,UrunAdi NVARCHAR(250),Birim NVARCHAR(30),GerekliMiktar DECIMAL(18,4) NOT NULL,RezerveMiktar DECIMAL(18,4) NOT NULL DEFAULT 0,TuketilenMiktar DECIMAL(18,4) NOT NULL DEFAULT 0,Durum NVARCHAR(30) NOT NULL DEFAULT N'Rezerve',CONSTRAINT UQ_UretimEmriMalzemeleri UNIQUE(CompanyId,EmirId,MRPIhtiyacId),CONSTRAINT CK_UretimEmriMalzemeleri_Miktar CHECK(GerekliMiktar>0 AND RezerveMiktar>=0 AND TuketilenMiktar>=0 AND TuketilenMiktar<=RezerveMiktar),CONSTRAINT FK_UretimEmriMalzemeleri_Emir FOREIGN KEY(EmirId) REFERENCES dbo.UretimEmirleriV2(EmirId),CONSTRAINT FK_UretimEmriMalzemeleri_Ihtiyac FOREIGN KEY(MRPIhtiyacId) REFERENCES dbo.MRPMalzemeIhtiyaclari(IhtiyacId),CONSTRAINT FK_UretimEmriMalzemeleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.UretimMalzemeRezervasyonlari',N'U') IS NULL CREATE TABLE dbo.UretimMalzemeRezervasyonlari(RezervasyonId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,MalzemeId BIGINT NOT NULL,StokBakiyeId BIGINT NOT NULL,UrunId INT NOT NULL,DepoId INT NOT NULL,LokasyonId INT NOT NULL,LotNo NVARCHAR(100) NOT NULL DEFAULT N'',SeriNo NVARCHAR(100) NOT NULL DEFAULT N'',Miktar DECIMAL(18,4) NOT NULL,TuketilenMiktar DECIMAL(18,4) NOT NULL DEFAULT 0,Durum NVARCHAR(30) NOT NULL DEFAULT N'Aktif',CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT CK_UretimMalzemeRezervasyonlari_Miktar CHECK(Miktar>0 AND TuketilenMiktar>=0 AND TuketilenMiktar<=Miktar),CONSTRAINT FK_UretimMalzemeRezervasyonlari_Malzeme FOREIGN KEY(MalzemeId) REFERENCES dbo.UretimEmriMalzemeleri(MalzemeId),CONSTRAINT FK_UretimMalzemeRezervasyonlari_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));CREATE INDEX IX_UretimMalzemeRezervasyonlari_Aktif ON dbo.UretimMalzemeRezervasyonlari(CompanyId,Durum,MalzemeId) INCLUDE(StokBakiyeId,Miktar,TuketilenMiktar);
IF OBJECT_ID(N'dbo.UretimGerceklesmeleriV2',N'U') IS NULL CREATE TABLE dbo.UretimGerceklesmeleriV2(GerceklesmeId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,GerceklesmeNo NVARCHAR(80) NOT NULL,EmirId BIGINT NOT NULL,UretimTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UretilenMiktar DECIMAL(18,4) NOT NULL,FireMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,LotNo NVARCHAR(100) NOT NULL DEFAULT N'',KaliteDurumu NVARCHAR(30) NOT NULL DEFAULT N'Onaylı',IslemAnahtari NVARCHAR(100) NOT NULL,Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_UretimGerceklesmeleriV2_No UNIQUE(CompanyId,GerceklesmeNo),CONSTRAINT UQ_UretimGerceklesmeleriV2_Emir UNIQUE(CompanyId,EmirId),CONSTRAINT UQ_UretimGerceklesmeleriV2_Islem UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT CK_UretimGerceklesmeleriV2_Miktar CHECK(UretilenMiktar>0 AND FireMiktari>=0),CONSTRAINT FK_UretimGerceklesmeleriV2_Emir FOREIGN KEY(EmirId) REFERENCES dbo.UretimEmirleriV2(EmirId),CONSTRAINT FK_UretimGerceklesmeleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'URETIM_EMRI',N'UE-'),(N'URETIM_GERCEKLESME',N'UG-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'019 üretim yürütme zinciri tamamlandı.' Result;
