/* ALYA ERP 020 - Üretim maliyeti, stok değerleme ve maliyet muhasebesi */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.UretimGerceklesmeleriV2',N'U') IS NULL OR OBJECT_ID(N'dbo.UretimEmirleriV2',N'U') IS NULL THROW 52001,N'Önce Faz 7 kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL THROW 52002,N'Faz 1 stok çekirdeği bulunamadı.',1;
IF OBJECT_ID(N'dbo.UrunMaliyetleri',N'U') IS NULL CREATE TABLE dbo.UrunMaliyetleri(MaliyetId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,UrunId INT NOT NULL,StandartMaliyet DECIMAL(18,6) NOT NULL DEFAULT 0,OrtalamaMaliyet DECIMAL(18,6) NOT NULL DEFAULT 0,SonAlisMaliyeti DECIMAL(18,6) NOT NULL DEFAULT 0,ParaBirimi NVARCHAR(10) NOT NULL DEFAULT N'TRY',Kaynak NVARCHAR(40),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),RowVersion ROWVERSION,CONSTRAINT UQ_UrunMaliyetleri UNIQUE(CompanyId,UrunId),CONSTRAINT CK_UrunMaliyetleri_Tutar CHECK(StandartMaliyet>=0 AND OrtalamaMaliyet>=0 AND SonAlisMaliyeti>=0),CONSTRAINT FK_UrunMaliyetleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.UretimMaliyetFisleri',N'U') IS NULL CREATE TABLE dbo.UretimMaliyetFisleri(MaliyetFisId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FisNo NVARCHAR(80) NOT NULL,GerceklesmeId BIGINT NOT NULL,EmirId BIGINT NOT NULL,MamulUrunId INT NOT NULL,UretilenMiktar DECIMAL(18,4) NOT NULL,MalzemeMaliyeti DECIMAL(18,2) NOT NULL,DirektIscilikMaliyeti DECIMAL(18,2) NOT NULL DEFAULT 0,GenelUretimGideri DECIMAL(18,2) NOT NULL DEFAULT 0,ToplamFiiliMaliyet DECIMAL(18,2) NOT NULL,FiiliBirimMaliyet DECIMAL(18,6) NOT NULL,StandartBirimMaliyet DECIMAL(18,6) NOT NULL DEFAULT 0,SapmaTutari DECIMAL(18,2) NOT NULL DEFAULT 0,MuhasebeFisId BIGINT,Durum NVARCHAR(30) NOT NULL DEFAULT N'Kesinleşti',CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_UretimMaliyetFisleri_No UNIQUE(CompanyId,FisNo),CONSTRAINT UQ_UretimMaliyetFisleri_Gerceklesme UNIQUE(CompanyId,GerceklesmeId),CONSTRAINT CK_UretimMaliyetFisleri_Tutar CHECK(UretilenMiktar>0 AND MalzemeMaliyeti>=0 AND DirektIscilikMaliyeti>=0 AND GenelUretimGideri>=0 AND ToplamFiiliMaliyet>=0),CONSTRAINT FK_UretimMaliyetFisleri_Gerceklesme FOREIGN KEY(GerceklesmeId) REFERENCES dbo.UretimGerceklesmeleriV2(GerceklesmeId),CONSTRAINT FK_UretimMaliyetFisleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.UretimMaliyetKalemleri',N'U') IS NULL CREATE TABLE dbo.UretimMaliyetKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,MaliyetFisId BIGINT NOT NULL,KalemTipi NVARCHAR(30) NOT NULL,UrunId INT,Aciklama NVARCHAR(250),Miktar DECIMAL(18,4) NOT NULL DEFAULT 0,BirimMaliyet DECIMAL(18,6) NOT NULL DEFAULT 0,ToplamMaliyet DECIMAL(18,2) NOT NULL,CONSTRAINT CK_UretimMaliyetKalemleri_Tutar CHECK(Miktar>=0 AND BirimMaliyet>=0 AND ToplamMaliyet>=0),CONSTRAINT FK_UretimMaliyetKalemleri_Fis FOREIGN KEY(MaliyetFisId) REFERENCES dbo.UretimMaliyetFisleri(MaliyetFisId),CONSTRAINT FK_UretimMaliyetKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.StokDegerlemeFisleri',N'U') IS NULL CREATE TABLE dbo.StokDegerlemeFisleri(DegerlemeId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,DegerlemeNo NVARCHAR(80) NOT NULL,DegerlemeTarihi DATETIME2(3) NOT NULL,ToplamMiktar DECIMAL(18,4) NOT NULL,ToplamDeger DECIMAL(18,2) NOT NULL,IslemAnahtari NVARCHAR(100) NOT NULL,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_StokDegerlemeFisleri_No UNIQUE(CompanyId,DegerlemeNo),CONSTRAINT UQ_StokDegerlemeFisleri_Islem UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT FK_StokDegerlemeFisleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.StokDegerlemeKalemleri',N'U') IS NULL CREATE TABLE dbo.StokDegerlemeKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,DegerlemeId BIGINT NOT NULL,UrunId INT NOT NULL,DepoId INT NOT NULL,Miktar DECIMAL(18,4) NOT NULL,BirimMaliyet DECIMAL(18,6) NOT NULL,StokDegeri DECIMAL(18,2) NOT NULL,CONSTRAINT FK_StokDegerlemeKalemleri_Fis FOREIGN KEY(DegerlemeId) REFERENCES dbo.StokDegerlemeFisleri(DegerlemeId),CONSTRAINT FK_StokDegerlemeKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));CREATE INDEX IX_StokDegerlemeKalemleri_Urun ON dbo.StokDegerlemeKalemleri(CompanyId,UrunId,DegerlemeId);
IF COL_LENGTH(N'dbo.UretimGerceklesmeleriV2',N'BirimMaliyet') IS NULL ALTER TABLE dbo.UretimGerceklesmeleriV2 ADD BirimMaliyet DECIMAL(18,6) NULL;
IF COL_LENGTH(N'dbo.UretimGerceklesmeleriV2',N'ToplamMaliyet') IS NULL ALTER TABLE dbo.UretimGerceklesmeleriV2 ADD ToplamMaliyet DECIMAL(18,2) NULL;
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'URETIM_MALIYET',N'UM-'),(N'STOK_DEGERLEME',N'SD-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
IF OBJECT_ID(N'dbo.MuhasebeHesaplari',N'U') IS NOT NULL INSERT dbo.MuhasebeHesaplari(CompanyId,HesapKodu,HesapAdi,HesapTipi) SELECT s.CompanyId,x.Kod,x.Ad,x.Tip FROM dbo.Sirketler s CROSS JOIN(VALUES(N'150',N'İlk Madde ve Malzeme',N'Varlık'),(N'152',N'Mamuller',N'Varlık'),(N'720',N'Direkt İşçilik Giderleri',N'Gider'),(N'730',N'Genel Üretim Giderleri',N'Gider'))x(Kod,Ad,Tip) WHERE NOT EXISTS(SELECT 1 FROM dbo.MuhasebeHesaplari h WHERE h.CompanyId=s.CompanyId AND h.HesapKodu=x.Kod);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'020 maliyet ve stok değerleme zinciri tamamlandı.' Result;
