/* ALYA ERP 021 V2 - Bütçe, gerçekleşen sapma ve nakit akış tahmini. Tekrar çalıştırılabilir. */
SET NOCOUNT ON;SET XACT_ABORT ON;
BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.MuhasebeFisleri',N'U') IS NULL OR OBJECT_ID(N'dbo.MuhasebeFisSatirlari',N'U') IS NULL THROW 52101,N'Önce Faz 3 finans ve muhasebe zinciri kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.SatinAlmaSiparisleriV2',N'U') IS NULL THROW 52102,N'Önce Faz 5 satın alma zinciri kurulmalıdır.',1;
IF COL_LENGTH(N'dbo.Faturalar',N'VadeTarihi') IS NULL THROW 52103,N'Faturalar.VadeTarihi alanı bulunamadı.',1;
IF OBJECT_ID(N'dbo.ButceSenaryolari',N'U') IS NULL CREATE TABLE dbo.ButceSenaryolari(ButceId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,ButceNo NVARCHAR(80) NOT NULL,ButceAdi NVARCHAR(180) NOT NULL,ButceYili INT NOT NULL,Senaryo NVARCHAR(30) NOT NULL DEFAULT N'Baz',ParaBirimi NVARCHAR(10) NOT NULL DEFAULT N'TRY',Durum NVARCHAR(20) NOT NULL DEFAULT N'Taslak',OnaylayanId INT,OnayTarihi DATETIME2(3),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_ButceSenaryolari_No UNIQUE(CompanyId,ButceNo),CONSTRAINT UQ_ButceSenaryolari_Yil_Senaryo UNIQUE(CompanyId,ButceYili,Senaryo),CONSTRAINT CK_ButceSenaryolari_Yil CHECK(ButceYili BETWEEN 2000 AND 2200),CONSTRAINT CK_ButceSenaryolari_Senaryo CHECK(Senaryo IN(N'Baz',N'İyimser',N'Kötümser')),CONSTRAINT CK_ButceSenaryolari_Durum CHECK(Durum IN(N'Taslak',N'Onaylı',N'Kapalı')),CONSTRAINT FK_ButceSenaryolari_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.ButceKalemleri',N'U') IS NULL CREATE TABLE dbo.ButceKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,ButceId BIGINT NOT NULL,AyNo TINYINT NOT NULL,KalemTipi NVARCHAR(20) NOT NULL,HesapKodu NVARCHAR(30) NOT NULL,HesapAdi NVARCHAR(180) NOT NULL,PlanlananTutar DECIMAL(18,2) NOT NULL DEFAULT 0,Aciklama NVARCHAR(300),UpdatedBy INT,UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_ButceKalemleri UNIQUE(CompanyId,ButceId,AyNo,KalemTipi,HesapKodu),CONSTRAINT CK_ButceKalemleri_Ay CHECK(AyNo BETWEEN 1 AND 12),CONSTRAINT CK_ButceKalemleri_Tip CHECK(KalemTipi IN(N'GELİR',N'GİDER',N'NAKİT GİRİŞ',N'NAKİT ÇIKIŞ')),CONSTRAINT CK_ButceKalemleri_Tutar CHECK(PlanlananTutar>=0),CONSTRAINT FK_ButceKalemleri_Butce FOREIGN KEY(ButceId) REFERENCES dbo.ButceSenaryolari(ButceId),CONSTRAINT FK_ButceKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.ButceKalemleri') AND name=N'IX_ButceKalemleri_Rapor') EXEC sys.sp_executesql N'CREATE INDEX IX_ButceKalemleri_Rapor ON dbo.ButceKalemleri(CompanyId,ButceId,AyNo,KalemTipi) INCLUDE(HesapKodu,PlanlananTutar);';
IF OBJECT_ID(N'dbo.NakitTahminleri',N'U') IS NULL CREATE TABLE dbo.NakitTahminleri(TahminId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,TahminNo NVARCHAR(80) NOT NULL,TahminTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),BaslangicTarihi DATE NOT NULL,BitisTarihi DATE NOT NULL,ToplamGiris DECIMAL(18,2) NOT NULL DEFAULT 0,ToplamCikis DECIMAL(18,2) NOT NULL DEFAULT 0,NetNakit DECIMAL(18,2) NOT NULL DEFAULT 0,IslemAnahtari NVARCHAR(100) NOT NULL,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_NakitTahminleri_No UNIQUE(CompanyId,TahminNo),CONSTRAINT UQ_NakitTahminleri_Islem UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT CK_NakitTahminleri_Tarih CHECK(BaslangicTarihi<=BitisTarihi),CONSTRAINT FK_NakitTahminleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.NakitTahminKalemleri',N'U') IS NULL CREATE TABLE dbo.NakitTahminKalemleri(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,TahminId BIGINT NOT NULL,BeklenenTarih DATE NOT NULL,Yon NVARCHAR(10) NOT NULL,KaynakTip NVARCHAR(40) NOT NULL,KaynakId BIGINT,KaynakNo NVARCHAR(100),CariKodu NVARCHAR(100),CariAdi NVARCHAR(250),Aciklama NVARCHAR(300),Tutar DECIMAL(18,2) NOT NULL,OlasilikYuzde DECIMAL(5,2) NOT NULL DEFAULT 100,AgirlikliTutar AS CAST(Tutar*OlasilikYuzde/100.0 AS DECIMAL(18,2)) PERSISTED,CONSTRAINT CK_NakitTahminKalemleri_Yon CHECK(Yon IN(N'GİRİŞ',N'ÇIKIŞ')),CONSTRAINT CK_NakitTahminKalemleri_Tutar CHECK(Tutar>0 AND OlasilikYuzde BETWEEN 0 AND 100),CONSTRAINT FK_NakitTahminKalemleri_Tahmin FOREIGN KEY(TahminId) REFERENCES dbo.NakitTahminleri(TahminId),CONSTRAINT FK_NakitTahminKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.NakitTahminKalemleri') AND name=N'IX_NakitTahminKalemleri_Tarih') EXEC sys.sp_executesql N'CREATE INDEX IX_NakitTahminKalemleri_Tarih ON dbo.NakitTahminKalemleri(CompanyId,TahminId,BeklenenTarih,Yon) INCLUDE(Tutar,AgirlikliTutar);';
IF OBJECT_ID(N'dbo.NakitTahminManuelKalemleri',N'U') IS NULL CREATE TABLE dbo.NakitTahminManuelKalemleri(ManuelKalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,BeklenenTarih DATE NOT NULL,Yon NVARCHAR(10) NOT NULL,Baslik NVARCHAR(180) NOT NULL,Tutar DECIMAL(18,2) NOT NULL,OlasilikYuzde DECIMAL(5,2) NOT NULL DEFAULT 100,IsActive BIT NOT NULL DEFAULT 1,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT CK_NakitTahminManuelKalemleri CHECK(Yon IN(N'GİRİŞ',N'ÇIKIŞ') AND Tutar>0 AND OlasilikYuzde BETWEEN 0 AND 100),CONSTRAINT FK_NakitTahminManuelKalemleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'BUTCE',N'BTC-'),(N'NAKIT_TAHMIN',N'NT-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'021 V2 bütçe ve nakit tahmin zinciri tamamlandı.' Result;
