/* ALYA ERP 023 - CRM aday müşteri, fırsat, aktivite ve kampanya zinciri. Veri silmez. */
SET NOCOUNT ON;SET XACT_ABORT ON;
BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.Siparisler',N'U') IS NULL OR OBJECT_ID(N'dbo.BelgeBaglantilari',N'U') IS NULL THROW 52301,N'Önce Faz 2 satış zinciri kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.CrmAsamalar',N'U') IS NULL CREATE TABLE dbo.CrmAsamalar(AsamaId INT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,AsamaKodu NVARCHAR(40) NOT NULL,AsamaAdi NVARCHAR(100) NOT NULL,SiraNo INT NOT NULL,OlasilikYuzde DECIMAL(5,2) NOT NULL,AsamaTipi NVARCHAR(20) NOT NULL DEFAULT N'Açık',RenkKodu NVARCHAR(20),IsActive BIT NOT NULL DEFAULT 1,CONSTRAINT UQ_CrmAsamalar UNIQUE(CompanyId,AsamaKodu),CONSTRAINT UQ_CrmAsamalar_CompanyId UNIQUE(CompanyId,AsamaId),CONSTRAINT CK_CrmAsamalar CHECK(SiraNo>0 AND OlasilikYuzde BETWEEN 0 AND 100 AND AsamaTipi IN(N'Açık',N'Kazanıldı',N'Kaybedildi')),CONSTRAINT FK_CrmAsamalar_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.CrmAdayMusteriler',N'U') IS NULL CREATE TABLE dbo.CrmAdayMusteriler(AdayId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,AdayNo NVARCHAR(80) NOT NULL,FirmaAdi NVARCHAR(200) NOT NULL,YetkiliAdi NVARCHAR(160),Eposta NVARCHAR(200),Telefon NVARCHAR(60),Kaynak NVARCHAR(80),Sektor NVARCHAR(100),Durum NVARCHAR(30) NOT NULL DEFAULT N'Yeni',Skor TINYINT NOT NULL DEFAULT 0,CariKodu NVARCHAR(100),SorumluKullaniciId INT,SonrakiAksiyonTarihi DATETIME2(3),Notlar NVARCHAR(1000),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_CrmAdayMusteriler_No UNIQUE(CompanyId,AdayNo),CONSTRAINT UQ_CrmAdayMusteriler_CompanyId UNIQUE(CompanyId,AdayId),CONSTRAINT CK_CrmAdayMusteriler_Durum CHECK(Durum IN(N'Yeni',N'İletişimde',N'Nitelikli',N'Dönüştürüldü',N'Kapalı')),CONSTRAINT CK_CrmAdayMusteriler_Skor CHECK(Skor BETWEEN 0 AND 100),CONSTRAINT FK_CrmAdayMusteriler_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.CrmFirsatlar',N'U') IS NULL CREATE TABLE dbo.CrmFirsatlar(FirsatId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FirsatNo NVARCHAR(80) NOT NULL,AdayId BIGINT,CariKodu NVARCHAR(100),CariAdi NVARCHAR(250) NOT NULL,Baslik NVARCHAR(240) NOT NULL,AsamaId INT NOT NULL,BeklenenTutar DECIMAL(18,2) NOT NULL,OlasilikYuzde DECIMAL(5,2) NOT NULL,AgirlikliTutar AS CAST(BeklenenTutar*OlasilikYuzde/100.0 AS DECIMAL(18,2)) PERSISTED,TahminiKapanisTarihi DATE NOT NULL,Durum NVARCHAR(20) NOT NULL DEFAULT N'Açık',KaybedilmeNedeni NVARCHAR(300),SiparisId INT,SorumluKullaniciId INT,Aciklama NVARCHAR(1000),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_CrmFirsatlar_No UNIQUE(CompanyId,FirsatNo),CONSTRAINT UQ_CrmFirsatlar_CompanyId UNIQUE(CompanyId,FirsatId),CONSTRAINT CK_CrmFirsatlar CHECK(BeklenenTutar>=0 AND OlasilikYuzde BETWEEN 0 AND 100 AND Durum IN(N'Açık',N'Kazanıldı',N'Kaybedildi')),CONSTRAINT FK_CrmFirsatlar_Asama FOREIGN KEY(CompanyId,AsamaId) REFERENCES dbo.CrmAsamalar(CompanyId,AsamaId),CONSTRAINT FK_CrmFirsatlar_Aday FOREIGN KEY(CompanyId,AdayId) REFERENCES dbo.CrmAdayMusteriler(CompanyId,AdayId),CONSTRAINT FK_CrmFirsatlar_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.CrmFirsatlar') AND name=N'IX_CrmFirsatlar_Pipeline') EXEC sys.sp_executesql N'CREATE INDEX IX_CrmFirsatlar_Pipeline ON dbo.CrmFirsatlar(CompanyId,Durum,AsamaId,TahminiKapanisTarihi) INCLUDE(BeklenenTutar,OlasilikYuzde,AgirlikliTutar,CariAdi);';
IF OBJECT_ID(N'dbo.CrmAktiviteler',N'U') IS NULL CREATE TABLE dbo.CrmAktiviteler(AktiviteId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,AdayId BIGINT,FirsatId BIGINT,AktiviteTipi NVARCHAR(30) NOT NULL,Konu NVARCHAR(240) NOT NULL,PlanlananTarih DATETIME2(3) NOT NULL,TamamlanmaTarihi DATETIME2(3),Durum NVARCHAR(20) NOT NULL DEFAULT N'Planlandı',Oncelik NVARCHAR(20) NOT NULL DEFAULT N'Normal',Sonuc NVARCHAR(1000),SorumluKullaniciId INT,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT CK_CrmAktiviteler_Baglanti CHECK(AdayId IS NOT NULL OR FirsatId IS NOT NULL),CONSTRAINT CK_CrmAktiviteler_Tip CHECK(AktiviteTipi IN(N'Arama',N'Toplantı',N'E-posta',N'Görev',N'Not')),CONSTRAINT CK_CrmAktiviteler_Durum CHECK(Durum IN(N'Planlandı',N'Tamamlandı',N'İptal')),CONSTRAINT CK_CrmAktiviteler_Oncelik CHECK(Oncelik IN(N'Düşük',N'Normal',N'Yüksek',N'Acil')),CONSTRAINT FK_CrmAktiviteler_Aday FOREIGN KEY(CompanyId,AdayId) REFERENCES dbo.CrmAdayMusteriler(CompanyId,AdayId),CONSTRAINT FK_CrmAktiviteler_Firsat FOREIGN KEY(CompanyId,FirsatId) REFERENCES dbo.CrmFirsatlar(CompanyId,FirsatId),CONSTRAINT FK_CrmAktiviteler_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.CrmAktiviteler') AND name=N'IX_CrmAktiviteler_Ajanda') EXEC sys.sp_executesql N'CREATE INDEX IX_CrmAktiviteler_Ajanda ON dbo.CrmAktiviteler(CompanyId,Durum,PlanlananTarih,Oncelik) INCLUDE(AdayId,FirsatId,Konu,AktiviteTipi);';
IF OBJECT_ID(N'dbo.CrmAsamaGecmisi',N'U') IS NULL CREATE TABLE dbo.CrmAsamaGecmisi(GecmisId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FirsatId BIGINT NOT NULL,OncekiAsamaId INT,YeniAsamaId INT NOT NULL,DegisimTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),Aciklama NVARCHAR(400),CreatedBy INT,CONSTRAINT FK_CrmAsamaGecmisi_Firsat FOREIGN KEY(CompanyId,FirsatId) REFERENCES dbo.CrmFirsatlar(CompanyId,FirsatId),CONSTRAINT FK_CrmAsamaGecmisi_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.CrmKampanyalar',N'U') IS NULL CREATE TABLE dbo.CrmKampanyalar(KampanyaId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KampanyaNo NVARCHAR(80) NOT NULL,KampanyaAdi NVARCHAR(200) NOT NULL,Kanal NVARCHAR(60) NOT NULL,BaslangicTarihi DATE NOT NULL,BitisTarihi DATE NOT NULL,Butce DECIMAL(18,2) NOT NULL DEFAULT 0,HedefAdaySayisi INT NOT NULL DEFAULT 0,Durum NVARCHAR(20) NOT NULL DEFAULT N'Taslak',Aciklama NVARCHAR(600),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_CrmKampanyalar_No UNIQUE(CompanyId,KampanyaNo),CONSTRAINT UQ_CrmKampanyalar_CompanyId UNIQUE(CompanyId,KampanyaId),CONSTRAINT CK_CrmKampanyalar CHECK(BaslangicTarihi<=BitisTarihi AND Butce>=0 AND HedefAdaySayisi>=0 AND Durum IN(N'Taslak',N'Aktif',N'Tamamlandı',N'İptal')),CONSTRAINT FK_CrmKampanyalar_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.CrmKampanyaAdaylari',N'U') IS NULL CREATE TABLE dbo.CrmKampanyaAdaylari(KampanyaAdayId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KampanyaId BIGINT NOT NULL,AdayId BIGINT NOT NULL,KatilimTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),Durum NVARCHAR(30) NOT NULL DEFAULT N'Hedef',CONSTRAINT UQ_CrmKampanyaAdaylari UNIQUE(CompanyId,KampanyaId,AdayId),CONSTRAINT FK_CrmKampanyaAdaylari_Kampanya FOREIGN KEY(CompanyId,KampanyaId) REFERENCES dbo.CrmKampanyalar(CompanyId,KampanyaId),CONSTRAINT FK_CrmKampanyaAdaylari_Aday FOREIGN KEY(CompanyId,AdayId) REFERENCES dbo.CrmAdayMusteriler(CompanyId,AdayId),CONSTRAINT FK_CrmKampanyaAdaylari_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
INSERT dbo.CrmAsamalar(CompanyId,AsamaKodu,AsamaAdi,SiraNo,OlasilikYuzde,AsamaTipi,RenkKodu) SELECT s.CompanyId,x.Kod,x.Ad,x.Sira,x.Olasilik,x.Tip,x.Renk FROM dbo.Sirketler s CROSS JOIN(VALUES(N'ADAY',N'Aday',10,10,N'Açık',N'#64748b'),(N'IHTIYAC',N'İhtiyaç Analizi',20,25,N'Açık',N'#0284c7'),(N'TEKLIF',N'Teklif',30,50,N'Açık',N'#7c3aed'),(N'MUZAKERE',N'Müzakere',40,75,N'Açık',N'#ea580c'),(N'KAZANILDI',N'Kazanıldı',50,100,N'Kazanıldı',N'#16a34a'),(N'KAYBEDILDI',N'Kaybedildi',60,0,N'Kaybedildi',N'#dc2626'))x(Kod,Ad,Sira,Olasilik,Tip,Renk) WHERE NOT EXISTS(SELECT 1 FROM dbo.CrmAsamalar a WHERE a.CompanyId=s.CompanyId AND a.AsamaKodu=x.Kod);
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'CRM_ADAY',N'CRM-A-'),(N'CRM_FIRSAT',N'CRM-F-'),(N'CRM_KAMPANYA',N'CRM-K-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'023 CRM satış hunisi zinciri tamamlandı.' Result;
