/* ALYA ERP 025 - Fason iş emri, malzeme sevki, kabul ve maliyet zinciri */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL OR OBJECT_ID(N'dbo.StokHareketleri',N'U') IS NULL THROW 52501,N'Önce Faz 1 stok çekirdeği kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.CariListesi',N'U') IS NULL OR OBJECT_ID(N'dbo.Urunler',N'U') IS NULL THROW 52502,N'Cari veya ürün çekirdeği bulunamadı.',1;
IF OBJECT_ID(N'dbo.FasonIsEmirleriV2',N'U') IS NULL CREATE TABLE dbo.FasonIsEmirleriV2(FasonEmirId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,EmirNo NVARCHAR(80) NOT NULL,TedarikciCariId INT NOT NULL,MamulUrunId INT NOT NULL,PlanlananMiktar DECIMAL(18,4) NOT NULL,KabulMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,RedMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,Birim NVARCHAR(30) NOT NULL DEFAULT N'Adet',FasonBirimFiyat DECIMAL(18,6) NOT NULL DEFAULT 0,ParaBirimi NVARCHAR(10) NOT NULL DEFAULT N'TRY',HedefDepoId INT NOT NULL,HedefLokasyonId INT NOT NULL,PlanBaslangic DATE,TerminTarihi DATE,Durum NVARCHAR(30) NOT NULL DEFAULT N'Planlandı',IslemAnahtari NVARCHAR(100) NOT NULL,Aciklama NVARCHAR(600),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_FasonIsEmirleriV2_No UNIQUE(CompanyId,EmirNo),CONSTRAINT UQ_FasonIsEmirleriV2_Islem UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT CK_FasonIsEmirleriV2_Miktar CHECK(PlanlananMiktar>0 AND KabulMiktari>=0 AND RedMiktari>=0 AND KabulMiktari+RedMiktari<=PlanlananMiktar),CONSTRAINT FK_FasonIsEmirleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_FasonIsEmirleriV2_Urun FOREIGN KEY(MamulUrunId) REFERENCES dbo.Urunler(UrunId),CONSTRAINT FK_FasonIsEmirleriV2_Depo FOREIGN KEY(HedefDepoId) REFERENCES dbo.Depolar(DepoId),CONSTRAINT FK_FasonIsEmirleriV2_Lokasyon FOREIGN KEY(HedefLokasyonId) REFERENCES dbo.DepoLokasyonlari(LokasyonId));
IF OBJECT_ID(N'dbo.FasonMalzemeleriV2',N'U') IS NULL CREATE TABLE dbo.FasonMalzemeleriV2(FasonMalzemeId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FasonEmirId BIGINT NOT NULL,UrunId INT NOT NULL,UrunAdi NVARCHAR(250),Birim NVARCHAR(30) NOT NULL DEFAULT N'Adet',PlanlananMiktar DECIMAL(18,4) NOT NULL,SevkMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,IadeMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,CONSTRAINT UQ_FasonMalzemeleriV2 UNIQUE(CompanyId,FasonEmirId,UrunId),CONSTRAINT CK_FasonMalzemeleriV2_Miktar CHECK(PlanlananMiktar>0 AND SevkMiktari>=0 AND IadeMiktari>=0 AND IadeMiktari<=SevkMiktari),CONSTRAINT FK_FasonMalzemeleriV2_Emir FOREIGN KEY(FasonEmirId) REFERENCES dbo.FasonIsEmirleriV2(FasonEmirId),CONSTRAINT FK_FasonMalzemeleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_FasonMalzemeleriV2_Urun FOREIGN KEY(UrunId) REFERENCES dbo.Urunler(UrunId));
IF OBJECT_ID(N'dbo.FasonSevkleriV2',N'U') IS NULL CREATE TABLE dbo.FasonSevkleriV2(FasonSevkId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FasonEmirId BIGINT NOT NULL,SevkNo NVARCHAR(80) NOT NULL,SevkTarihi DATETIME2(3) NOT NULL,IslemAnahtari NVARCHAR(100) NOT NULL,Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_FasonSevkleriV2_No UNIQUE(CompanyId,SevkNo),CONSTRAINT UQ_FasonSevkleriV2_Islem UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT FK_FasonSevkleriV2_Emir FOREIGN KEY(FasonEmirId) REFERENCES dbo.FasonIsEmirleriV2(FasonEmirId),CONSTRAINT FK_FasonSevkleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.FasonSevkKalemleriV2',N'U') IS NULL CREATE TABLE dbo.FasonSevkKalemleriV2(FasonSevkKalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FasonSevkId BIGINT NOT NULL,FasonMalzemeId BIGINT NOT NULL,StokBakiyeId BIGINT NOT NULL,UrunId INT NOT NULL,DepoId INT NOT NULL,LokasyonId INT NOT NULL,LotNo NVARCHAR(100) NOT NULL DEFAULT N'',SeriNo NVARCHAR(100) NOT NULL DEFAULT N'',Miktar DECIMAL(18,4) NOT NULL,CONSTRAINT CK_FasonSevkKalemleriV2_Miktar CHECK(Miktar>0),CONSTRAINT FK_FasonSevkKalemleriV2_Sevk FOREIGN KEY(FasonSevkId) REFERENCES dbo.FasonSevkleriV2(FasonSevkId),CONSTRAINT FK_FasonSevkKalemleriV2_Malzeme FOREIGN KEY(FasonMalzemeId) REFERENCES dbo.FasonMalzemeleriV2(FasonMalzemeId),CONSTRAINT FK_FasonSevkKalemleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.FasonKabulleriV2',N'U') IS NULL CREATE TABLE dbo.FasonKabulleriV2(FasonKabulId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,FasonEmirId BIGINT NOT NULL,KabulNo NVARCHAR(80) NOT NULL,KabulTarihi DATETIME2(3) NOT NULL,KabulMiktari DECIMAL(18,4) NOT NULL,RedMiktari DECIMAL(18,4) NOT NULL DEFAULT 0,LotNo NVARCHAR(100) NOT NULL DEFAULT N'',KaliteDurumu NVARCHAR(30) NOT NULL DEFAULT N'Beklemede',FasonHizmetMaliyeti DECIMAL(18,2) NOT NULL DEFAULT 0,IslemAnahtari NVARCHAR(100) NOT NULL,Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_FasonKabulleriV2_No UNIQUE(CompanyId,KabulNo),CONSTRAINT UQ_FasonKabulleriV2_Islem UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT CK_FasonKabulleriV2_Miktar CHECK(KabulMiktari>=0 AND RedMiktari>=0 AND KabulMiktari+RedMiktari>0),CONSTRAINT FK_FasonKabulleriV2_Emir FOREIGN KEY(FasonEmirId) REFERENCES dbo.FasonIsEmirleriV2(FasonEmirId),CONSTRAINT FK_FasonKabulleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.FasonIsEmirleriV2') AND name=N'IX_FasonIsEmirleriV2_Takip')CREATE INDEX IX_FasonIsEmirleriV2_Takip ON dbo.FasonIsEmirleriV2(CompanyId,Durum,TerminTarihi) INCLUDE(TedarikciCariId,MamulUrunId,PlanlananMiktar,KabulMiktari);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.FasonMalzemeleriV2') AND name=N'IX_FasonMalzemeleriV2_Emir')CREATE INDEX IX_FasonMalzemeleriV2_Emir ON dbo.FasonMalzemeleriV2(CompanyId,FasonEmirId) INCLUDE(UrunId,PlanlananMiktar,SevkMiktari);
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding) SELECT s.CompanyId,x.Tip,x.OnEk,6 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'FASON_EMRI',N'FE-'),(N'FASON_SEVK',N'FS-'),(N'FASON_KABUL',N'FK-'))x(Tip,OnEk) WHERE NOT EXISTS(SELECT 1 FROM dbo.NumberSeries n WHERE n.CompanyId=s.CompanyId AND n.DocumentType=x.Tip);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'025 fason üretim zinciri tamamlandı.' Result;
