/* ALYA ERP 026 - Satılabilir stok, ATP ve yeniden sipariş politikası */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL THROW 52601,N'Faz 1 stok çekirdeği bulunamadı.',1;
IF OBJECT_ID(N'dbo.SiparisDetay',N'U') IS NULL OR OBJECT_ID(N'dbo.SatinAlmaSiparisKalemleriV2',N'U') IS NULL OR OBJECT_ID(N'dbo.UretimEmirleriV2',N'U') IS NULL THROW 52602,N'Önce satış, satın alma ve üretim fazları kurulmalıdır.',1;
IF OBJECT_ID(N'dbo.StokPolitikalariV2',N'U') IS NULL CREATE TABLE dbo.StokPolitikalariV2(PolitikaId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,UrunId INT NOT NULL,EmniyetStoku DECIMAL(18,4) NOT NULL DEFAULT 0,MinimumStok DECIMAL(18,4) NOT NULL DEFAULT 0,MaksimumStok DECIMAL(18,4),YenidenSiparisNoktasi DECIMAL(18,4) NOT NULL DEFAULT 0,TedarikTipi NVARCHAR(20) NOT NULL DEFAULT N'Satın Alma',TedarikSuresiGun INT NOT NULL DEFAULT 0,IsActive BIT NOT NULL DEFAULT 1,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_StokPolitikalariV2 UNIQUE(CompanyId,UrunId),CONSTRAINT CK_StokPolitikalariV2_Miktar CHECK(EmniyetStoku>=0 AND MinimumStok>=0 AND (MaksimumStok IS NULL OR MaksimumStok>=MinimumStok) AND YenidenSiparisNoktasi>=0 AND TedarikSuresiGun>=0),CONSTRAINT FK_StokPolitikalariV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_StokPolitikalariV2_Urun FOREIGN KEY(UrunId) REFERENCES dbo.Urunler(UrunId));
IF OBJECT_ID(N'dbo.AtpKontrolleriV2',N'U') IS NULL CREATE TABLE dbo.AtpKontrolleriV2(AtpKontrolId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,UrunId INT NOT NULL,TalepMiktari DECIMAL(18,4) NOT NULL,AnindaKarsilanabilirMiktar DECIMAL(18,4) NOT NULL,SozVerilenMiktar DECIMAL(18,4) NOT NULL,SozVerilenTarih DATE,Sonuc NVARCHAR(30) NOT NULL,ReferansTipi NVARCHAR(40),ReferansId NVARCHAR(100),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT CK_AtpKontrolleriV2_Miktar CHECK(TalepMiktari>0 AND AnindaKarsilanabilirMiktar>=0 AND SozVerilenMiktar>=0),CONSTRAINT FK_AtpKontrolleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_AtpKontrolleriV2_Urun FOREIGN KEY(UrunId) REFERENCES dbo.Urunler(UrunId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.AtpKontrolleriV2') AND name=N'IX_AtpKontrolleriV2_Tarih')CREATE INDEX IX_AtpKontrolleriV2_Tarih ON dbo.AtpKontrolleriV2(CompanyId,CreatedAt DESC) INCLUDE(UrunId,TalepMiktari,Sonuc);
EXEC(N'CREATE OR ALTER VIEW dbo.vw_SatilabilirStokV2 AS WITH B AS(SELECT CompanyId,UrunId,SUM(Miktar)FizikselStok,SUM(RezerveMiktar)RezerveStok,SUM(BlokeMiktar)BlokeStok,SUM(BeklenenGiris)ManuelBeklenenGiris,SUM(BeklenenCikis)ManuelBeklenenCikis FROM dbo.StokBakiyeleri GROUP BY CompanyId,UrunId),S AS(SELECT d.CompanyId,d.UrunId,SUM(CASE WHEN d.Miktar>d.SevkEdilenMiktar THEN d.Miktar-d.SevkEdilenMiktar ELSE 0 END)AcikSatisMiktari FROM dbo.SiparisDetay d JOIN dbo.Siparisler h ON h.CompanyId=d.CompanyId AND h.SiparisId=d.SiparisId WHERE d.UrunId IS NOT NULL AND d.Miktar>d.SevkEdilenMiktar AND ISNULL(h.Durum,N'''') NOT IN(N''İptal'',N''Tamamlandı'') GROUP BY d.CompanyId,d.UrunId),P AS(SELECT k.CompanyId,k.UrunId,SUM(k.SiparisMiktari-k.TeslimAlinanMiktar)AcikSatinAlmaMiktari,MIN(h.BeklenenTeslimTarihi)IlkSatinAlmaTarihi FROM dbo.SatinAlmaSiparisKalemleriV2 k JOIN dbo.SatinAlmaSiparisleriV2 h ON h.CompanyId=k.CompanyId AND h.SiparisId=k.SiparisId WHERE k.SiparisMiktari>k.TeslimAlinanMiktar AND h.Durum NOT IN(N''İptal'',N''Tamamlandı'') GROUP BY k.CompanyId,k.UrunId),U AS(SELECT CompanyId,MamulUrunId UrunId,SUM(PlanlananMiktar-UretilenMiktar)AcikUretimMiktari,MIN(CAST(PlanlananBitis AS DATE))IlkUretimTarihi FROM dbo.UretimEmirleriV2 WHERE PlanlananMiktar>UretilenMiktar AND Durum NOT IN(N''İptal'',N''Tamamlandı'') GROUP BY CompanyId,MamulUrunId)SELECT b.CompanyId,b.UrunId,r.UrunKodu,r.UrunAdi,r.Birim,b.FizikselStok,b.RezerveStok,b.BlokeStok,CAST(b.FizikselStok-b.RezerveStok-b.BlokeStok AS DECIMAL(18,4))SatilabilirStok,ISNULL(s.AcikSatisMiktari,0)AcikSatisMiktari,ISNULL(p.AcikSatinAlmaMiktari,0)AcikSatinAlmaMiktari,ISNULL(u.AcikUretimMiktari,0)AcikUretimMiktari,b.ManuelBeklenenGiris,b.ManuelBeklenenCikis,CAST(b.FizikselStok-b.RezerveStok-b.BlokeStok-s.AcikSatisMiktari+ISNULL(p.AcikSatinAlmaMiktari,0)+ISNULL(u.AcikUretimMiktari,0)+b.ManuelBeklenenGiris-b.ManuelBeklenenCikis AS DECIMAL(18,4))ProjeksiyonStok,p.IlkSatinAlmaTarihi,u.IlkUretimTarihi,ISNULL(x.EmniyetStoku,0)EmniyetStoku,ISNULL(x.MinimumStok,0)MinimumStok,x.MaksimumStok,ISNULL(x.YenidenSiparisNoktasi,0)YenidenSiparisNoktasi,ISNULL(x.TedarikTipi,N''Satın Alma'')TedarikTipi,ISNULL(x.TedarikSuresiGun,0)TedarikSuresiGun FROM B b JOIN dbo.Urunler r ON r.CompanyId=b.CompanyId AND r.UrunId=b.UrunId LEFT JOIN S s ON s.CompanyId=b.CompanyId AND s.UrunId=b.UrunId LEFT JOIN P p ON p.CompanyId=b.CompanyId AND p.UrunId=b.UrunId LEFT JOIN U u ON u.CompanyId=b.CompanyId AND u.UrunId=b.UrunId LEFT JOIN dbo.StokPolitikalariV2 x ON x.CompanyId=b.CompanyId AND x.UrunId=b.UrunId AND x.IsActive=1;');
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;
SELECT N'026 satılabilir stok ve ATP zinciri tamamlandı.' Result;
