/* ALYA ERP 027 - Pazaryeri omnichannel çekirdeği */
SET NOCOUNT ON;SET XACT_ABORT ON;BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.Urunler',N'U') IS NULL OR OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL THROW 52701,N'Ürün ve stok çekirdeği bulunamadı.',1;
IF OBJECT_ID(N'dbo.PazaryeriKanallariV2',N'U') IS NULL CREATE TABLE dbo.PazaryeriKanallariV2(KanalId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KanalKodu NVARCHAR(40) NOT NULL,KanalAdi NVARCHAR(100) NOT NULL,MagazaKodu NVARCHAR(100),StokPayiYuzde DECIMAL(5,2) NOT NULL DEFAULT 100,FiyatCarpani DECIMAL(9,4) NOT NULL DEFAULT 1,IsActive BIT NOT NULL DEFAULT 1,SonSiparisSenkronu DATETIME2(3),SonStokSenkronu DATETIME2(3),CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_PazaryeriKanallariV2 UNIQUE(CompanyId,KanalKodu),CONSTRAINT CK_PazaryeriKanallariV2_Oran CHECK(StokPayiYuzde>=0 AND StokPayiYuzde<=100 AND FiyatCarpani>0),CONSTRAINT FK_PazaryeriKanallariV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.PazaryeriUrunEslemeleriV2',N'U') IS NULL CREATE TABLE dbo.PazaryeriUrunEslemeleriV2(EslemeId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KanalId BIGINT NOT NULL,HariciSku NVARCHAR(120) NOT NULL,UrunId INT NOT NULL,HariciBarkod NVARCHAR(120),IsActive BIT NOT NULL DEFAULT 1,UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_PazaryeriUrunEslemeleriV2 UNIQUE(CompanyId,KanalId,HariciSku),CONSTRAINT FK_PazaryeriUrunEslemeleriV2_Kanal FOREIGN KEY(KanalId) REFERENCES dbo.PazaryeriKanallariV2(KanalId),CONSTRAINT FK_PazaryeriUrunEslemeleriV2_Urun FOREIGN KEY(UrunId) REFERENCES dbo.Urunler(UrunId),CONSTRAINT FK_PazaryeriUrunEslemeleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.PazaryeriSiparisleriV2',N'U') IS NULL CREATE TABLE dbo.PazaryeriSiparisleriV2(PazaryeriSiparisId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KanalId BIGINT NOT NULL,HariciSiparisNo NVARCHAR(120) NOT NULL,HariciPaketNo NVARCHAR(120),MusteriAdi NVARCHAR(250),SiparisTarihi DATETIME2(3) NOT NULL,ParaBirimi NVARCHAR(10) NOT NULL DEFAULT N'TRY',GenelToplam DECIMAL(18,2) NOT NULL DEFAULT 0,HariciDurum NVARCHAR(60),ErpDurumu NVARCHAR(30) NOT NULL DEFAULT N'Yeni',RawJson NVARCHAR(MAX),CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_PazaryeriSiparisleriV2 UNIQUE(CompanyId,KanalId,HariciSiparisNo),CONSTRAINT FK_PazaryeriSiparisleriV2_Kanal FOREIGN KEY(KanalId) REFERENCES dbo.PazaryeriKanallariV2(KanalId),CONSTRAINT FK_PazaryeriSiparisleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.PazaryeriSiparisKalemleriV2',N'U') IS NULL CREATE TABLE dbo.PazaryeriSiparisKalemleriV2(KalemId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,PazaryeriSiparisId BIGINT NOT NULL,HariciSatirId NVARCHAR(120),HariciSku NVARCHAR(120) NOT NULL,UrunId INT,UrunAdi NVARCHAR(250),Miktar DECIMAL(18,4) NOT NULL,BirimFiyat DECIMAL(18,4) NOT NULL,SatirToplam DECIMAL(18,2) NOT NULL,EslemeDurumu NVARCHAR(30) NOT NULL DEFAULT N'Bekliyor',CONSTRAINT CK_PazaryeriSiparisKalemleriV2_Miktar CHECK(Miktar>0),CONSTRAINT FK_PazaryeriSiparisKalemleriV2_Siparis FOREIGN KEY(PazaryeriSiparisId) REFERENCES dbo.PazaryeriSiparisleriV2(PazaryeriSiparisId),CONSTRAINT FK_PazaryeriSiparisKalemleriV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
IF OBJECT_ID(N'dbo.PazaryeriSenkronizasyonlariV2',N'U') IS NULL CREATE TABLE dbo.PazaryeriSenkronizasyonlariV2(SenkronId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KanalId BIGINT NOT NULL,IslemTipi NVARCHAR(30) NOT NULL,Durum NVARCHAR(20) NOT NULL DEFAULT N'Bekliyor',KayitSayisi INT NOT NULL DEFAULT 0,HataMesaji NVARCHAR(1000),IslemAnahtari NVARCHAR(100) NOT NULL,CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CompletedAt DATETIME2(3),CONSTRAINT UQ_PazaryeriSenkronizasyonlariV2 UNIQUE(CompanyId,IslemAnahtari),CONSTRAINT FK_PazaryeriSenkronizasyonlariV2_Kanal FOREIGN KEY(KanalId) REFERENCES dbo.PazaryeriKanallariV2(KanalId),CONSTRAINT FK_PazaryeriSenkronizasyonlariV2_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
INSERT dbo.PazaryeriKanallariV2(CompanyId,KanalKodu,KanalAdi)SELECT s.CompanyId,v.Kod,v.Ad FROM dbo.Sirketler s CROSS JOIN(VALUES(N'TRENDYOL',N'Trendyol'),(N'HEPSIBURADA',N'Hepsiburada'),(N'N11',N'N11'),(N'AMAZON',N'Amazon'),(N'PAZARAMA',N'Pazarama'),(N'PTTAVM',N'PttAVM'),(N'CICEKSEPETI',N'ÇiçekSepeti'))v(Kod,Ad)WHERE NOT EXISTS(SELECT 1 FROM dbo.PazaryeriKanallariV2 k WHERE k.CompanyId=s.CompanyId AND k.KanalKodu=v.Kod);
COMMIT;END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK;THROW;END CATCH;SELECT N'027 pazaryeri omnichannel zinciri tamamlandı.' Result;
