/* 031 - KolayBi ham aynasını ALYA ürün/fatura tablolarına dönüştürme eşlemeleri */
SET NOCOUNT ON;SET XACT_ABORT ON;
IF OBJECT_ID(N'dbo.KolaybiRawMirror',N'U') IS NULL THROW 53101,N'Önce 030_KOLAYBI_FULL_MIRROR.sql çalıştırın.',1;
IF OBJECT_ID(N'dbo.Urunler',N'U') IS NULL OR OBJECT_ID(N'dbo.Faturalar',N'U') IS NULL OR OBJECT_ID(N'dbo.FaturaDetay',N'U') IS NULL THROW 53102,N'Ürün ve fatura tabloları eksik.',1;
IF OBJECT_ID(N'dbo.KolaybiUrunEslemeleri',N'U') IS NULL EXEC sys.sp_executesql N'CREATE TABLE dbo.KolaybiUrunEslemeleri(CompanyId INT NOT NULL,KolaybiProductId NVARCHAR(255) NOT NULL,UrunId INT NOT NULL,LastMirrorId BIGINT NULL,LastSyncedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT PK_KolaybiUrunEslemeleri PRIMARY KEY(CompanyId,KolaybiProductId),CONSTRAINT FK_KolaybiUrunEslemeleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));';
IF OBJECT_ID(N'dbo.KolaybiFaturaEslemeleri',N'U') IS NULL EXEC sys.sp_executesql N'CREATE TABLE dbo.KolaybiFaturaEslemeleri(CompanyId INT NOT NULL,ResourceType NVARCHAR(80) NOT NULL,KolaybiDocumentId NVARCHAR(255) NOT NULL,FaturaId INT NOT NULL,LastMirrorId BIGINT NULL,LastSyncedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT PK_KolaybiFaturaEslemeleri PRIMARY KEY(CompanyId,ResourceType,KolaybiDocumentId),CONSTRAINT FK_KolaybiFaturaEslemeleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));';
IF EXISTS(SELECT 1 FROM sys.security_policies WHERE object_id=OBJECT_ID(N'dbo.SecurityPolicy_CompanyIsolation')) AND OBJECT_ID(N'dbo.fn_CompanyIsolationPredicate',N'IF') IS NOT NULL BEGIN DECLARE @T TABLE(N SYSNAME);INSERT @T VALUES(N'KolaybiUrunEslemeleri'),(N'KolaybiFaturaEslemeleri');DECLARE @N SYSNAME,@S NVARCHAR(MAX);DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT N FROM @T;OPEN c;FETCH NEXT FROM c INTO @N;WHILE @@FETCH_STATUS=0 BEGIN IF NOT EXISTS(SELECT 1 FROM sys.security_predicates WHERE object_id=OBJECT_ID(N'dbo.SecurityPolicy_CompanyIsolation') AND target_object_id=OBJECT_ID(N'dbo.'+@N) AND predicate_type=0)BEGIN SET @S=N'ALTER SECURITY POLICY dbo.SecurityPolicy_CompanyIsolation ADD FILTER PREDICATE dbo.fn_CompanyIsolationPredicate(CompanyId) ON dbo.'+QUOTENAME(@N)+N';';EXEC sys.sp_executesql @S;END;IF NOT EXISTS(SELECT 1 FROM sys.security_predicates WHERE object_id=OBJECT_ID(N'dbo.SecurityPolicy_CompanyIsolation') AND target_object_id=OBJECT_ID(N'dbo.'+@N) AND predicate_type=1 AND operation=1)BEGIN SET @S=N'ALTER SECURITY POLICY dbo.SecurityPolicy_CompanyIsolation ADD BLOCK PREDICATE dbo.fn_CompanyIsolationPredicate(CompanyId) ON dbo.'+QUOTENAME(@N)+N' AFTER INSERT;';EXEC sys.sp_executesql @S;END;IF NOT EXISTS(SELECT 1 FROM sys.security_predicates WHERE object_id=OBJECT_ID(N'dbo.SecurityPolicy_CompanyIsolation') AND target_object_id=OBJECT_ID(N'dbo.'+@N) AND predicate_type=1 AND operation=2)BEGIN SET @S=N'ALTER SECURITY POLICY dbo.SecurityPolicy_CompanyIsolation ADD BLOCK PREDICATE dbo.fn_CompanyIsolationPredicate(CompanyId) ON dbo.'+QUOTENAME(@N)+N' AFTER UPDATE;';EXEC sys.sp_executesql @S;END;FETCH NEXT FROM c INTO @N;END;CLOSE c;DEALLOCATE c;END;
PRINT N'031 KolayBi operasyonel dönüşüm altyapısı tamamlandı.';
GO
