import React, { useState } from "react";
import axios from "axios";
const ROOT = process.env.REACT_APP_API_URL || "http:" + "//localhost:5000/api", API = `${ROOT}/kolaybi-live`;
export default function KolaybiEverythingPanel({ enabled }) {
 const [plan,setPlan]=useState(null),[rows,setRows]=useState([]),[resources,setResources]=useState([]),[filter,setFilter]=useState(""),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 const loadPlan=async()=>{try{setBusy("plan");setError("");const{data}=await axios.get(`${API}/everything/plan`);setPlan(data)}catch(e){setError(e.response?.data?.error||e.message)}finally{setBusy("")}};
 const records=async(resource="")=>{try{const{data}=await axios.get(`${API}/everything/records`,{params:{resource,page:1,size:100}});setRows(data.rows);setResources(data.resources);setFilter(resource)}catch(e){setError(e.response?.data?.error||e.message)}};
 const run=async()=>{if(!plan||!window.confirm(`KolayBi'den indirilen ${plan.total} kaydın TAMAMI ALYA'ya aktarılsın mı?`))return;setBusy("run");setError("");const notes=[];for(const step of[
  {name:"Tüm kayıtlar",url:"everything/run",confirmation:"YAMANKAYA_EVERYTHING"},
  {name:"Cariler",url:"associates/import",confirmation:"YAMANKAYA_CARI_IMPORT"},
  {name:"Ürün ve faturalar",url:"materialize/run",confirmation:"YAMANKAYA_MATERIALIZE"},
  {name:"Sipariş, proforma ve finans",url:"business/run",confirmation:"YAMANKAYA_BUSINESS"},
  {name:"Cari hareketleri",url:"cari-movements/run",confirmation:"YAMANKAYA_CARI_MOVEMENTS"}
 ]){try{const{data}=await axios.post(`${API}/${step.url}`,{confirmation:step.confirmation});notes.push(data.message||`${step.name}: tamam`)}catch(e){notes.push(`${step.name}: ${e.response?.data?.error||e.message}`)}}setMessage(notes.join(" · "));await loadPlan();await records();setBusy("")};
 return <article className="klive-card"><div className="klive-title"><div><h2>KolayBi — tüm verileri ALYA'ya aktar</h2><p>Carileri, ürünleri, faturaları, siparişleri, proformaları, kasa/bankaları, finans ve cari ekstre hareketlerini kendi modüllerine; kalan bütün kayıtları aranabilir veri merkezine aktarır.</p></div><div className="klive-actions"><button disabled={!enabled||busy} onClick={loadPlan}>Toplamı kontrol et</button><button className="activate" disabled={!plan||busy} onClick={run}>{busy==="run"?"Tüm veriler işleniyor…":"TÜMÜNÜ ALYA'YA AKTAR"}</button></div></div>{error&&<div className="klive-error">{/KolaybiOperationalRecords/i.test(error)?"031, 032, 033 ve 034 KolayBi migrationlarını sırayla çalıştırın.":error}</div>}{plan&&<div className="klive-preview-meta">KolayBi ham kayıt: {plan.total} · ALYA veri merkezinde: {plan.operational}</div>}{message&&<div className="klive-success">{message}</div>}{resources.length>0&&<><div className="klive-actions"><button onClick={()=>records("")}>Tümü</button>{resources.map(x=><button key={x.ResourceType} onClick={()=>records(x.ResourceType)}>{x.ResourceType} ({x.RecordCount})</button>)}</div><div className="klive-preview-meta">Gösterilen kaynak: {filter||"Tümü"} · İlk 100 kayıt</div><div className="klive-table"><table><thead><tr><th>Kaynak</th><th>Belge No</th><th>Ad/Açıklama</th><th>Tarih</th><th>Tutar</th><th>Para</th><th>Durum</th></tr></thead><tbody>{rows.map(x=><tr key={x.RecordId}><td>{x.ResourceType}</td><td>{x.DocumentNo||x.ExternalId}</td><td>{x.DisplayName||"—"}</td><td>{x.RecordDate?new Date(x.RecordDate).toLocaleDateString("tr-TR"):"—"}</td><td>{x.Amount??"—"}</td><td>{x.Currency||"—"}</td><td>{x.RecordStatus||"—"}</td></tr>)}</tbody></table></div></>}</article>;
}
