/* ALYA ERP - 011 / Faz 0: yetki, mali dönem, numara, audit ve workflow çekirdeği. Mevcut iş verisini silmez. */
SET NOCOUNT ON; SET XACT_ABORT ON;
BEGIN TRY
BEGIN TRAN;
IF OBJECT_ID(N'dbo.Sirketler',N'U') IS NULL THROW 51101,N'dbo.Sirketler bulunamadı.',1;
IF OBJECT_ID(N'dbo.Kullanicilar',N'U') IS NULL THROW 51102,N'dbo.Kullanicilar bulunamadı.',1;

IF OBJECT_ID(N'dbo.Roles',N'U') IS NULL BEGIN
 CREATE TABLE dbo.Roles(RoleId INT IDENTITY PRIMARY KEY,RoleCode NVARCHAR(64) NOT NULL UNIQUE,RoleName NVARCHAR(120) NOT NULL,Description NVARCHAR(500),IsSystem BIT NOT NULL DEFAULT(0),IsActive BIT NOT NULL DEFAULT(1),CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
END;
IF OBJECT_ID(N'dbo.Permissions',N'U') IS NULL BEGIN
 CREATE TABLE dbo.Permissions(PermissionId INT IDENTITY PRIMARY KEY,PermissionCode NVARCHAR(120) NOT NULL UNIQUE,PermissionName NVARCHAR(180) NOT NULL,ModuleCode NVARCHAR(64) NOT NULL,OperationCode NVARCHAR(32) NOT NULL,Description NVARCHAR(500),IsActive BIT NOT NULL DEFAULT(1),CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
END;
IF OBJECT_ID(N'dbo.RolePermissions',N'U') IS NULL BEGIN
 CREATE TABLE dbo.RolePermissions(RoleId INT NOT NULL,PermissionId INT NOT NULL,GrantedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT PK_RolePermissions PRIMARY KEY(RoleId,PermissionId),CONSTRAINT FK_RolePermissions_Role FOREIGN KEY(RoleId) REFERENCES dbo.Roles(RoleId),CONSTRAINT FK_RolePermissions_Permission FOREIGN KEY(PermissionId) REFERENCES dbo.Permissions(PermissionId));
END;
IF OBJECT_ID(N'dbo.UserCompanies',N'U') IS NULL BEGIN
 CREATE TABLE dbo.UserCompanies(UserCompanyId BIGINT IDENTITY PRIMARY KEY,KullaniciId INT NOT NULL,CompanyId INT NOT NULL,IsDefault BIT NOT NULL DEFAULT(0),IsActive BIT NOT NULL DEFAULT(1),CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_UserCompanies UNIQUE(KullaniciId,CompanyId),CONSTRAINT FK_UserCompanies_User FOREIGN KEY(KullaniciId) REFERENCES dbo.Kullanicilar(KullaniciId),CONSTRAINT FK_UserCompanies_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
 CREATE INDEX IX_UserCompanies_Company_User ON dbo.UserCompanies(CompanyId,KullaniciId) INCLUDE(IsActive,IsDefault);
END;
IF OBJECT_ID(N'dbo.UserRoles',N'U') IS NULL BEGIN
 CREATE TABLE dbo.UserRoles(UserRoleId BIGINT IDENTITY PRIMARY KEY,KullaniciId INT NOT NULL,CompanyId INT NOT NULL,RoleId INT NOT NULL,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_UserRoles UNIQUE(KullaniciId,CompanyId),CONSTRAINT FK_UserRoles_User FOREIGN KEY(KullaniciId) REFERENCES dbo.Kullanicilar(KullaniciId),CONSTRAINT FK_UserRoles_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_UserRoles_Role FOREIGN KEY(RoleId) REFERENCES dbo.Roles(RoleId));
 CREATE INDEX IX_UserRoles_Company_Role ON dbo.UserRoles(CompanyId,RoleId,KullaniciId);
END;
IF OBJECT_ID(N'dbo.FiscalPeriods',N'U') IS NULL BEGIN
 CREATE TABLE dbo.FiscalPeriods(PeriodId INT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,PeriodCode NVARCHAR(32) NOT NULL,PeriodName NVARCHAR(120) NOT NULL,StartDate DATE NOT NULL,EndDate DATE NOT NULL,Status NVARCHAR(16) NOT NULL DEFAULT(N'Open'),ClosedAt DATETIME2(3),ClosedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_FiscalPeriods UNIQUE(CompanyId,PeriodCode),CONSTRAINT CK_FiscalPeriods_Dates CHECK(StartDate<=EndDate),CONSTRAINT CK_FiscalPeriods_Status CHECK(Status IN(N'Open',N'Locked',N'Closed')),CONSTRAINT FK_FiscalPeriods_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_FiscalPeriods_User FOREIGN KEY(ClosedBy) REFERENCES dbo.Kullanicilar(KullaniciId));
 CREATE INDEX IX_FiscalPeriods_Company_Dates ON dbo.FiscalPeriods(CompanyId,StartDate,EndDate,Status);
END;
IF OBJECT_ID(N'dbo.PeriodLocks',N'U') IS NULL BEGIN
 CREATE TABLE dbo.PeriodLocks(PeriodLockId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,PeriodId INT,ModuleCode NVARCHAR(64),LockStartDate DATE NOT NULL,LockEndDate DATE NOT NULL,Reason NVARCHAR(500),IsActive BIT NOT NULL DEFAULT(1),LockedBy INT,LockedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT CK_PeriodLocks_Dates CHECK(LockStartDate<=LockEndDate),CONSTRAINT FK_PeriodLocks_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_PeriodLocks_Period FOREIGN KEY(PeriodId) REFERENCES dbo.FiscalPeriods(PeriodId),CONSTRAINT FK_PeriodLocks_User FOREIGN KEY(LockedBy) REFERENCES dbo.Kullanicilar(KullaniciId));
 CREATE INDEX IX_PeriodLocks_Check ON dbo.PeriodLocks(CompanyId,LockStartDate,LockEndDate,IsActive,ModuleCode);
END;
IF OBJECT_ID(N'dbo.NumberSeries',N'U') IS NULL BEGIN
 CREATE TABLE dbo.NumberSeries(NumberSeriesId INT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,DocumentType NVARCHAR(64) NOT NULL,Prefix NVARCHAR(24) NOT NULL DEFAULT(N''),Suffix NVARCHAR(24) NOT NULL DEFAULT(N''),Padding INT NOT NULL DEFAULT(6),ResetYearly BIT NOT NULL DEFAULT(1),CurrentYear INT NOT NULL DEFAULT(YEAR(GETDATE())),LastNumber BIGINT NOT NULL DEFAULT(0),IsActive BIT NOT NULL DEFAULT(1),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),RowVersion ROWVERSION,CONSTRAINT UQ_NumberSeries UNIQUE(CompanyId,DocumentType),CONSTRAINT CK_NumberSeries_Padding CHECK(Padding BETWEEN 1 AND 18),CONSTRAINT FK_NumberSeries_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
END;
IF OBJECT_ID(N'dbo.AuditLogs',N'U') IS NULL BEGIN
 CREATE TABLE dbo.AuditLogs(AuditLogId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,KullaniciId INT,ActionCode NVARCHAR(64) NOT NULL,EntityType NVARCHAR(120) NOT NULL,EntityId NVARCHAR(120),BeforeJson NVARCHAR(MAX),AfterJson NVARCHAR(MAX),CorrelationId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),IpAddress NVARCHAR(64),UserAgent NVARCHAR(500),CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT FK_AuditLogs_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_AuditLogs_User FOREIGN KEY(KullaniciId) REFERENCES dbo.Kullanicilar(KullaniciId),CONSTRAINT CK_AuditLogs_BeforeJson CHECK(BeforeJson IS NULL OR ISJSON(BeforeJson)=1),CONSTRAINT CK_AuditLogs_AfterJson CHECK(AfterJson IS NULL OR ISJSON(AfterJson)=1));
 CREATE INDEX IX_AuditLogs_Company_Date ON dbo.AuditLogs(CompanyId,CreatedAt DESC) INCLUDE(KullaniciId,ActionCode,EntityType,EntityId);
END;
IF OBJECT_ID(N'dbo.Workflows',N'U') IS NULL BEGIN
 CREATE TABLE dbo.Workflows(WorkflowId INT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,WorkflowCode NVARCHAR(64) NOT NULL,WorkflowName NVARCHAR(160) NOT NULL,EntityType NVARCHAR(120) NOT NULL,IsActive BIT NOT NULL DEFAULT(1),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_Workflows UNIQUE(CompanyId,WorkflowCode),CONSTRAINT FK_Workflows_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_Workflows_User FOREIGN KEY(CreatedBy) REFERENCES dbo.Kullanicilar(KullaniciId));
END;
IF OBJECT_ID(N'dbo.WorkflowSteps',N'U') IS NULL BEGIN
 CREATE TABLE dbo.WorkflowSteps(WorkflowStepId INT IDENTITY PRIMARY KEY,WorkflowId INT NOT NULL,StepOrder INT NOT NULL,StepName NVARCHAR(160) NOT NULL,ApproverRoleId INT,ApproverUserId INT,MinimumApprovals INT NOT NULL DEFAULT(1),IsFinal BIT NOT NULL DEFAULT(0),CONSTRAINT UQ_WorkflowSteps UNIQUE(WorkflowId,StepOrder),CONSTRAINT CK_WorkflowSteps_Order CHECK(StepOrder>0),CONSTRAINT CK_WorkflowSteps_Approver CHECK(ApproverRoleId IS NOT NULL OR ApproverUserId IS NOT NULL),CONSTRAINT FK_WorkflowSteps_Workflow FOREIGN KEY(WorkflowId) REFERENCES dbo.Workflows(WorkflowId),CONSTRAINT FK_WorkflowSteps_Role FOREIGN KEY(ApproverRoleId) REFERENCES dbo.Roles(RoleId),CONSTRAINT FK_WorkflowSteps_User FOREIGN KEY(ApproverUserId) REFERENCES dbo.Kullanicilar(KullaniciId));
END;
IF OBJECT_ID(N'dbo.WorkflowInstances',N'U') IS NULL BEGIN
 CREATE TABLE dbo.WorkflowInstances(WorkflowInstanceId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,WorkflowId INT NOT NULL,EntityType NVARCHAR(120) NOT NULL,EntityId NVARCHAR(120) NOT NULL,Status NVARCHAR(20) NOT NULL DEFAULT(N'Pending'),CurrentStepOrder INT NOT NULL DEFAULT(1),RequestedBy INT NOT NULL,RequestedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CompletedAt DATETIME2(3),CONSTRAINT CK_WorkflowInstances_Status CHECK(Status IN(N'Pending',N'Approved',N'Rejected',N'Cancelled')),CONSTRAINT UQ_WorkflowInstances UNIQUE(CompanyId,WorkflowId,EntityType,EntityId),CONSTRAINT FK_WorkflowInstances_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_WorkflowInstances_Workflow FOREIGN KEY(WorkflowId) REFERENCES dbo.Workflows(WorkflowId),CONSTRAINT FK_WorkflowInstances_User FOREIGN KEY(RequestedBy) REFERENCES dbo.Kullanicilar(KullaniciId));
 CREATE INDEX IX_WorkflowInstances_Inbox ON dbo.WorkflowInstances(CompanyId,Status,CurrentStepOrder,RequestedAt);
END;
IF OBJECT_ID(N'dbo.WorkflowApprovals',N'U') IS NULL BEGIN
 CREATE TABLE dbo.WorkflowApprovals(WorkflowApprovalId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,WorkflowInstanceId BIGINT NOT NULL,WorkflowStepId INT NOT NULL,ApproverUserId INT NOT NULL,Decision NVARCHAR(16) NOT NULL,Comment NVARCHAR(1000),DecidedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_WorkflowApprovals UNIQUE(WorkflowInstanceId,WorkflowStepId,ApproverUserId),CONSTRAINT CK_WorkflowApprovals_Decision CHECK(Decision IN(N'Approved',N'Rejected')),CONSTRAINT FK_WorkflowApprovals_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_WorkflowApprovals_Instance FOREIGN KEY(WorkflowInstanceId) REFERENCES dbo.WorkflowInstances(WorkflowInstanceId),CONSTRAINT FK_WorkflowApprovals_Step FOREIGN KEY(WorkflowStepId) REFERENCES dbo.WorkflowSteps(WorkflowStepId),CONSTRAINT FK_WorkflowApprovals_User FOREIGN KEY(ApproverUserId) REFERENCES dbo.Kullanicilar(KullaniciId));
END;

MERGE dbo.Roles t USING(VALUES(N'ADMIN',N'Yönetici',N'Tüm çekirdek yönetim yetkileri',1),(N'USER',N'Kullanıcı',N'Standart işlem kullanıcısı',1),(N'VIEWER',N'Sadece Görüntüleme',N'Salt okunur kullanıcı',1))s(RoleCode,RoleName,Description,IsSystem) ON t.RoleCode=s.RoleCode WHEN MATCHED THEN UPDATE SET RoleName=s.RoleName,Description=s.Description,IsActive=1,UpdatedAt=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(RoleCode,RoleName,Description,IsSystem)VALUES(s.RoleCode,s.RoleName,s.Description,s.IsSystem);
MERGE dbo.Permissions t USING(VALUES(N'core.admin',N'Çekirdek yönetimi',N'CORE',N'ADMIN'),(N'core.audit.read',N'Denetim kayıtlarını görüntüleme',N'AUDIT',N'READ'),(N'core.period.manage',N'Mali dönem yönetimi',N'FISCAL_PERIOD',N'MANAGE'),(N'core.numberSeries.manage',N'Belge numara serisi yönetimi',N'NUMBER_SERIES',N'MANAGE'),(N'core.numberSeries.next',N'Belge numarası üretme',N'NUMBER_SERIES',N'EXECUTE'),(N'core.workflow.manage',N'Onay akışı yönetimi',N'WORKFLOW',N'MANAGE'),(N'core.workflow.approve',N'İşlem onaylama',N'WORKFLOW',N'APPROVE'),(N'core.user.manage',N'Kullanıcı ve şirket erişimi yönetimi',N'USER',N'MANAGE'),(N'erp.read',N'ERP kayıtlarını görüntüleme',N'ERP',N'READ'),(N'erp.write',N'ERP kayıtlarını değiştirme',N'ERP',N'WRITE'))s(PermissionCode,PermissionName,ModuleCode,OperationCode) ON t.PermissionCode=s.PermissionCode WHEN MATCHED THEN UPDATE SET PermissionName=s.PermissionName,ModuleCode=s.ModuleCode,OperationCode=s.OperationCode,IsActive=1 WHEN NOT MATCHED THEN INSERT(PermissionCode,PermissionName,ModuleCode,OperationCode)VALUES(s.PermissionCode,s.PermissionName,s.ModuleCode,s.OperationCode);
INSERT dbo.RolePermissions(RoleId,PermissionId) SELECT r.RoleId,p.PermissionId FROM dbo.Roles r CROSS JOIN dbo.Permissions p WHERE r.RoleCode=N'ADMIN' AND NOT EXISTS(SELECT 1 FROM dbo.RolePermissions x WHERE x.RoleId=r.RoleId AND x.PermissionId=p.PermissionId);
INSERT dbo.RolePermissions(RoleId,PermissionId) SELECT r.RoleId,p.PermissionId FROM dbo.Roles r JOIN dbo.Permissions p ON p.PermissionCode IN(N'erp.read',N'erp.write',N'core.numberSeries.next',N'core.workflow.approve') WHERE r.RoleCode=N'USER' AND NOT EXISTS(SELECT 1 FROM dbo.RolePermissions x WHERE x.RoleId=r.RoleId AND x.PermissionId=p.PermissionId);
INSERT dbo.RolePermissions(RoleId,PermissionId) SELECT r.RoleId,p.PermissionId FROM dbo.Roles r JOIN dbo.Permissions p ON p.PermissionCode=N'erp.read' WHERE r.RoleCode=N'VIEWER' AND NOT EXISTS(SELECT 1 FROM dbo.RolePermissions x WHERE x.RoleId=r.RoleId AND x.PermissionId=p.PermissionId);
INSERT dbo.UserCompanies(KullaniciId,CompanyId,IsDefault,IsActive) SELECT k.KullaniciId,s.CompanyId,CASE WHEN s.CompanyId=(SELECT MIN(CompanyId) FROM dbo.Sirketler WHERE IsActive=1) THEN 1 ELSE 0 END,1 FROM dbo.Kullanicilar k CROSS JOIN dbo.Sirketler s WHERE s.IsActive=1 AND NOT EXISTS(SELECT 1 FROM dbo.UserCompanies x WHERE x.KullaniciId=k.KullaniciId AND x.CompanyId=s.CompanyId);
INSERT dbo.UserRoles(KullaniciId,CompanyId,RoleId) SELECT k.KullaniciId,s.CompanyId,CASE WHEN k.Rol=N'Yönetici' THEN ra.RoleId WHEN k.Rol=N'Sadece Görüntüleme' THEN rv.RoleId ELSE ru.RoleId END FROM dbo.Kullanicilar k CROSS JOIN dbo.Sirketler s CROSS JOIN(SELECT RoleId FROM dbo.Roles WHERE RoleCode=N'ADMIN')ra CROSS JOIN(SELECT RoleId FROM dbo.Roles WHERE RoleCode=N'USER')ru CROSS JOIN(SELECT RoleId FROM dbo.Roles WHERE RoleCode=N'VIEWER')rv WHERE s.IsActive=1 AND NOT EXISTS(SELECT 1 FROM dbo.UserRoles x WHERE x.KullaniciId=k.KullaniciId AND x.CompanyId=s.CompanyId);
INSERT dbo.FiscalPeriods(CompanyId,PeriodCode,PeriodName,StartDate,EndDate,Status) SELECT s.CompanyId,CONVERT(NVARCHAR(4),YEAR(GETDATE())),CONVERT(NVARCHAR(4),YEAR(GETDATE()))+N' Mali Yılı',DATEFROMPARTS(YEAR(GETDATE()),1,1),DATEFROMPARTS(YEAR(GETDATE()),12,31),N'Open' FROM dbo.Sirketler s WHERE s.IsActive=1 AND NOT EXISTS(SELECT 1 FROM dbo.FiscalPeriods x WHERE x.CompanyId=s.CompanyId AND x.PeriodCode=CONVERT(NVARCHAR(4),YEAR(GETDATE())));
INSERT dbo.NumberSeries(CompanyId,DocumentType,Prefix,Padding,ResetYearly) SELECT s.CompanyId,d.DocumentType,d.Prefix,6,1 FROM dbo.Sirketler s CROSS JOIN(VALUES(N'SIPARIS',N'SPR-'),(N'FATURA',N'FTR-'),(N'IRSALIYE',N'IRS-'),(N'URETIM_EMRI',N'URT-'))d(DocumentType,Prefix) WHERE s.IsActive=1 AND NOT EXISTS(SELECT 1 FROM dbo.NumberSeries x WHERE x.CompanyId=s.CompanyId AND x.DocumentType=d.DocumentType);
COMMIT;
END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK; THROW; END CATCH;
SELECT N'ALYA ERP Faz 0 migration tamamlandı.' AS Result;
