/* ALYA ERP 012 - Faz 1 stok/depo çekirdeği. Mevcut veriyi silmez. */
SET NOCOUNT ON; SET XACT_ABORT ON;
BEGIN TRY BEGIN TRAN;
IF OBJECT_ID(N'dbo.Sirketler',N'U') IS NULL THROW 51201,N'Sirketler bulunamadı.',1;
IF OBJECT_ID(N'dbo.Urunler',N'U') IS NULL THROW 51202,N'Urunler bulunamadı.',1;
IF OBJECT_ID(N'dbo.StokHareketleri',N'U') IS NULL THROW 51203,N'Önce 004_STOK_HAREKETLERI çalıştırılmalıdır.',1;
IF OBJECT_ID(N'dbo.Depolar',N'U') IS NULL BEGIN
 CREATE TABLE dbo.Depolar(DepoId INT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,DepoKodu NVARCHAR(32) NOT NULL,DepoAdi NVARCHAR(120) NOT NULL,DepoTipi NVARCHAR(24) NOT NULL DEFAULT N'GENEL',IsActive BIT NOT NULL DEFAULT 1,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_Depolar UNIQUE(CompanyId,DepoKodu),CONSTRAINT FK_Depolar_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId));
END;
IF OBJECT_ID(N'dbo.DepoLokasyonlari',N'U') IS NULL BEGIN
 CREATE TABLE dbo.DepoLokasyonlari(LokasyonId INT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,DepoId INT NOT NULL,LokasyonKodu NVARCHAR(48) NOT NULL,LokasyonAdi NVARCHAR(120) NOT NULL,RafKodu NVARCHAR(48),Koridor NVARCHAR(32),IsPickable BIT NOT NULL DEFAULT 1,IsActive BIT NOT NULL DEFAULT 1,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_DepoLokasyonlari UNIQUE(CompanyId,DepoId,LokasyonKodu),CONSTRAINT FK_DepoLokasyonlari_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_DepoLokasyonlari_Depo FOREIGN KEY(DepoId) REFERENCES dbo.Depolar(DepoId));
END;
IF OBJECT_ID(N'dbo.StokBakiyeleri',N'U') IS NULL BEGIN
 CREATE TABLE dbo.StokBakiyeleri(StokBakiyeId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,UrunId INT NOT NULL,DepoId INT NOT NULL,LokasyonId INT NOT NULL,LotNo NVARCHAR(80) NOT NULL DEFAULT N'',SeriNo NVARCHAR(120) NOT NULL DEFAULT N'',Miktar DECIMAL(18,4) NOT NULL DEFAULT 0,RezerveMiktar DECIMAL(18,4) NOT NULL DEFAULT 0,BlokeMiktar DECIMAL(18,4) NOT NULL DEFAULT 0,BeklenenGiris DECIMAL(18,4) NOT NULL DEFAULT 0,BeklenenCikis DECIMAL(18,4) NOT NULL DEFAULT 0,MinimumStok DECIMAL(18,4) NOT NULL DEFAULT 0,MaksimumStok DECIMAL(18,4),YenidenSiparisNoktasi DECIMAL(18,4) NOT NULL DEFAULT 0,UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),RowVersion ROWVERSION,CONSTRAINT UQ_StokBakiyeleri UNIQUE(CompanyId,UrunId,DepoId,LokasyonId,LotNo,SeriNo),CONSTRAINT CK_StokBakiyeleri_Positive CHECK(Miktar>=0 AND RezerveMiktar>=0 AND BlokeMiktar>=0),CONSTRAINT CK_StokBakiyeleri_Reserve CHECK(RezerveMiktar+BlokeMiktar<=Miktar),CONSTRAINT FK_StokBakiyeleri_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_StokBakiyeleri_Urun FOREIGN KEY(UrunId) REFERENCES dbo.Urunler(UrunId),CONSTRAINT FK_StokBakiyeleri_Depo FOREIGN KEY(DepoId) REFERENCES dbo.Depolar(DepoId),CONSTRAINT FK_StokBakiyeleri_Lokasyon FOREIGN KEY(LokasyonId) REFERENCES dbo.DepoLokasyonlari(LokasyonId));
 CREATE INDEX IX_StokBakiyeleri_Urun ON dbo.StokBakiyeleri(CompanyId,UrunId) INCLUDE(Miktar,RezerveMiktar,BlokeMiktar,BeklenenGiris,BeklenenCikis);
END;
IF OBJECT_ID(N'dbo.StokRezervasyonlari',N'U') IS NULL BEGIN
 CREATE TABLE dbo.StokRezervasyonlari(RezervasyonId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,UrunId INT NOT NULL,DepoId INT NOT NULL,LokasyonId INT NOT NULL,ReferansTipi NVARCHAR(40) NOT NULL,ReferansId NVARCHAR(120) NOT NULL,Miktar DECIMAL(18,4) NOT NULL,KarsilananMiktar DECIMAL(18,4) NOT NULL DEFAULT 0,Durum NVARCHAR(20) NOT NULL DEFAULT N'ACTIVE',SonGecerlilik DATETIME2(3),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT CK_StokRezervasyon_Miktar CHECK(Miktar>0 AND KarsilananMiktar>=0 AND KarsilananMiktar<=Miktar),CONSTRAINT CK_StokRezervasyon_Durum CHECK(Durum IN(N'ACTIVE',N'RELEASED',N'FULFILLED',N'CANCELLED')),CONSTRAINT UQ_StokRezervasyon UNIQUE(CompanyId,ReferansTipi,ReferansId,UrunId,DepoId,LokasyonId),CONSTRAINT FK_StokRezervasyon_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_StokRezervasyon_Urun FOREIGN KEY(UrunId) REFERENCES dbo.Urunler(UrunId),CONSTRAINT FK_StokRezervasyon_Depo FOREIGN KEY(DepoId) REFERENCES dbo.Depolar(DepoId),CONSTRAINT FK_StokRezervasyon_Lokasyon FOREIGN KEY(LokasyonId) REFERENCES dbo.DepoLokasyonlari(LokasyonId));
END;
IF OBJECT_ID(N'dbo.StokTransferleri',N'U') IS NULL BEGIN
 CREATE TABLE dbo.StokTransferleri(TransferId BIGINT IDENTITY PRIMARY KEY,CompanyId INT NOT NULL,TransferNo NVARCHAR(64) NOT NULL,KaynakDepoId INT NOT NULL,HedefDepoId INT NOT NULL,Durum NVARCHAR(20) NOT NULL DEFAULT N'Taslak',TransferTarihi DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),Aciklama NVARCHAR(500),CreatedBy INT,CreatedAt DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),CONSTRAINT UQ_StokTransferleri UNIQUE(CompanyId,TransferNo),CONSTRAINT CK_StokTransfer_Depo CHECK(KaynakDepoId<>HedefDepoId),CONSTRAINT FK_StokTransfer_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Sirketler(CompanyId),CONSTRAINT FK_StokTransfer_Kaynak FOREIGN KEY(KaynakDepoId) REFERENCES dbo.Depolar(DepoId),CONSTRAINT FK_StokTransfer_Hedef FOREIGN KEY(HedefDepoId) REFERENCES dbo.Depolar(DepoId));
 CREATE TABLE dbo.StokTransferKalemleri(TransferKalemId BIGINT IDENTITY PRIMARY KEY,TransferId BIGINT NOT NULL,UrunId INT NOT NULL,KaynakLokasyonId INT NOT NULL,HedefLokasyonId INT NOT NULL,Miktar DECIMAL(18,4) NOT NULL,LotNo NVARCHAR(80) NOT NULL DEFAULT N'',SeriNo NVARCHAR(120) NOT NULL DEFAULT N'',CONSTRAINT CK_StokTransferKalem_Miktar CHECK(Miktar>0),CONSTRAINT FK_StokTransferKalem_Transfer FOREIGN KEY(TransferId) REFERENCES dbo.StokTransferleri(TransferId),CONSTRAINT FK_StokTransferKalem_Urun FOREIGN KEY(UrunId) REFERENCES dbo.Urunler(UrunId));
END;
IF COL_LENGTH(N'dbo.StokHareketleri',N'DepoId') IS NULL ALTER TABLE dbo.StokHareketleri ADD DepoId INT NULL;
IF COL_LENGTH(N'dbo.StokHareketleri',N'LokasyonId') IS NULL ALTER TABLE dbo.StokHareketleri ADD LokasyonId INT NULL;
IF COL_LENGTH(N'dbo.StokHareketleri',N'HedefDepoId') IS NULL ALTER TABLE dbo.StokHareketleri ADD HedefDepoId INT NULL;
IF COL_LENGTH(N'dbo.StokHareketleri',N'HedefLokasyonId') IS NULL ALTER TABLE dbo.StokHareketleri ADD HedefLokasyonId INT NULL;
IF COL_LENGTH(N'dbo.StokHareketleri',N'IslemTarihi') IS NULL ALTER TABLE dbo.StokHareketleri ADD IslemTarihi DATETIME2(3) NOT NULL CONSTRAINT DF_StokHareketleri_IslemTarihi DEFAULT SYSUTCDATETIME() WITH VALUES;
IF COL_LENGTH(N'dbo.StokHareketleri',N'CreatedBy') IS NULL ALTER TABLE dbo.StokHareketleri ADD CreatedBy INT NULL;
MERGE dbo.Depolar t USING(SELECT s.CompanyId,v.Kod,v.Ad,v.Tip FROM dbo.Sirketler s CROSS JOIN(VALUES(N'MERKEZ',N'Merkez Depo',N'GENEL'),(N'URETIM',N'Üretim Deposu',N'URETIM'),(N'SEVKIYAT',N'Sevkiyat Deposu',N'SEVKIYAT'))v(Kod,Ad,Tip) WHERE s.IsActive=1)x ON t.CompanyId=x.CompanyId AND t.DepoKodu=x.Kod WHEN NOT MATCHED THEN INSERT(CompanyId,DepoKodu,DepoAdi,DepoTipi)VALUES(x.CompanyId,x.Kod,x.Ad,x.Tip);
INSERT dbo.DepoLokasyonlari(CompanyId,DepoId,LokasyonKodu,LokasyonAdi) SELECT d.CompanyId,d.DepoId,N'GENEL',d.DepoAdi+N' / Genel' FROM dbo.Depolar d WHERE NOT EXISTS(SELECT 1 FROM dbo.DepoLokasyonlari l WHERE l.CompanyId=d.CompanyId AND l.DepoId=d.DepoId AND l.LokasyonKodu=N'GENEL');
MERGE dbo.StokBakiyeleri t USING(SELECT u.CompanyId,u.UrunId,d.DepoId,l.LokasyonId,CAST(ISNULL(u.StokMiktari,0) AS DECIMAL(18,4)) Miktar,CAST(ISNULL(u.KritikStokSeviyesi,0) AS DECIMAL(18,4)) MinStok FROM dbo.Urunler u JOIN dbo.Depolar d ON d.CompanyId=u.CompanyId AND d.DepoKodu=N'MERKEZ' JOIN dbo.DepoLokasyonlari l ON l.DepoId=d.DepoId AND l.LokasyonKodu=N'GENEL' WHERE ISNULL(u.IsActive,1)=1 AND ISNULL(u.Tur,N'Ürün')<>N'Hizmet')s ON t.CompanyId=s.CompanyId AND t.UrunId=s.UrunId AND t.DepoId=s.DepoId AND t.LokasyonId=s.LokasyonId AND t.LotNo=N'' AND t.SeriNo=N'' WHEN NOT MATCHED THEN INSERT(CompanyId,UrunId,DepoId,LokasyonId,Miktar,MinimumStok,YenidenSiparisNoktasi)VALUES(s.CompanyId,s.UrunId,s.DepoId,s.LokasyonId,s.Miktar,s.MinStok,s.MinStok);
EXEC(N'CREATE OR ALTER VIEW dbo.vw_StokDurumu AS SELECT b.StokBakiyeId,b.CompanyId,b.UrunId,u.UrunKodu,u.UrunAdi,u.Birim,b.DepoId,d.DepoKodu,d.DepoAdi,b.LokasyonId,l.LokasyonKodu,l.LokasyonAdi,b.Miktar,b.RezerveMiktar,b.BlokeMiktar,b.BeklenenGiris,b.BeklenenCikis,CAST(b.Miktar-b.RezerveMiktar-b.BlokeMiktar AS DECIMAL(18,4)) KullanilabilirStok,b.MinimumStok,b.MaksimumStok,b.YenidenSiparisNoktasi,CASE WHEN b.Miktar-b.RezerveMiktar-b.BlokeMiktar<=b.YenidenSiparisNoktasi THEN 1 ELSE 0 END Kritik FROM dbo.StokBakiyeleri b JOIN dbo.Urunler u ON u.UrunId=b.UrunId JOIN dbo.Depolar d ON d.DepoId=b.DepoId JOIN dbo.DepoLokasyonlari l ON l.LokasyonId=b.LokasyonId;');
COMMIT; END TRY BEGIN CATCH IF XACT_STATE()<>0 ROLLBACK; THROW; END CATCH;
SELECT N'Faz 1 stok/depo çekirdeği tamamlandı.' Result;
